// Code generated by MockGen. DO NOT EDIT.
// Source: history.go
//
// Generated by this command:
//
//	mockgen -source=history.go -destination=history_mock_test.go -package=password_test -typed
//

// Package password_test is a generated GoMock package.
package password_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockHistory is a mock of History interface.
type MockHistory struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryMockRecorder
	isgomock struct{}
}

// MockHistoryMockRecorder is the mock recorder for MockHistory.
type MockHistoryMockRecorder struct {
	mock *MockHistory
}

// NewMockHistory creates a new mock instance.
func NewMockHistory(ctrl *gomock.Controller) *MockHistory {
	mock := &MockHistory{ctrl: ctrl}
	mock.recorder = &MockHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistory) EXPECT() *MockHistoryMockRecorder {
	return m.recorder
}

// ForgetPasswords mocks base method.
func (m *MockHistory) ForgetPasswords(ctx context.Context, user identity.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgetPasswords", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForgetPasswords indicates an expected call of ForgetPasswords.
func (mr *MockHistoryMockRecorder) ForgetPasswords(ctx, user any) *MockHistoryForgetPasswordsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgetPasswords", reflect.TypeOf((*MockHistory)(nil).ForgetPasswords), ctx, user)
	return &MockHistoryForgetPasswordsCall{Call: call}
}

// MockHistoryForgetPasswordsCall wrap *gomock.Call
type MockHistoryForgetPasswordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHistoryForgetPasswordsCall) Return(arg0 error) *MockHistoryForgetPasswordsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHistoryForgetPasswordsCall) Do(f func(context.Context, identity.UserID) error) *MockHistoryForgetPasswordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHistoryForgetPasswordsCall) DoAndReturn(f func(context.Context, identity.UserID) error) *MockHistoryForgetPasswordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RecentPasswords mocks base method.
func (m *MockHistory) RecentPasswords(ctx context.Context, user identity.UserID, n int) ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentPasswords", ctx, user, n)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecentPasswords indicates an expected call of RecentPasswords.
func (mr *MockHistoryMockRecorder) RecentPasswords(ctx, user, n any) *MockHistoryRecentPasswordsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentPasswords", reflect.TypeOf((*MockHistory)(nil).RecentPasswords), ctx, user, n)
	return &MockHistoryRecentPasswordsCall{Call: call}
}

// MockHistoryRecentPasswordsCall wrap *gomock.Call
type MockHistoryRecentPasswordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHistoryRecentPasswordsCall) Return(arg0 [][]byte, arg1 error) *MockHistoryRecentPasswordsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHistoryRecentPasswordsCall) Do(f func(context.Context, identity.UserID, int) ([][]byte, error)) *MockHistoryRecentPasswordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHistoryRecentPasswordsCall) DoAndReturn(f func(context.Context, identity.UserID, int) ([][]byte, error)) *MockHistoryRecentPasswordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RetirePassword mocks base method.
func (m *MockHistory) RetirePassword(ctx context.Context, user identity.UserID, hash []byte, keep int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetirePassword", ctx, user, hash, keep)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetirePassword indicates an expected call of RetirePassword.
func (mr *MockHistoryMockRecorder) RetirePassword(ctx, user, hash, keep any) *MockHistoryRetirePasswordCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetirePassword", reflect.TypeOf((*MockHistory)(nil).RetirePassword), ctx, user, hash, keep)
	return &MockHistoryRetirePasswordCall{Call: call}
}

// MockHistoryRetirePasswordCall wrap *gomock.Call
type MockHistoryRetirePasswordCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHistoryRetirePasswordCall) Return(arg0 error) *MockHistoryRetirePasswordCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHistoryRetirePasswordCall) Do(f func(context.Context, identity.UserID, []byte, int) error) *MockHistoryRetirePasswordCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHistoryRetirePasswordCall) DoAndReturn(f func(context.Context, identity.UserID, []byte, int) error) *MockHistoryRetirePasswordCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
