// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/mfa (interfaces: ChallengeMethod)
//
// Generated by this command:
//
//	mockgen -destination=challenge_mock_test.go -package=recovery_test -typed github.com/kartaladev/scrty/mfa ChallengeMethod
//

// Package recovery_test is a generated GoMock package.
package recovery_test

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	factor "github.com/kartaladev/scrty/factor"
	identity "github.com/kartaladev/scrty/identity"
	mfa "github.com/kartaladev/scrty/mfa"
	gomock "go.uber.org/mock/gomock"
)

// MockChallengeMethod is a mock of ChallengeMethod interface.
type MockChallengeMethod struct {
	ctrl     *gomock.Controller
	recorder *MockChallengeMethodMockRecorder
	isgomock struct{}
}

// MockChallengeMethodMockRecorder is the mock recorder for MockChallengeMethod.
type MockChallengeMethodMockRecorder struct {
	mock *MockChallengeMethod
}

// NewMockChallengeMethod creates a new mock instance.
func NewMockChallengeMethod(ctrl *gomock.Controller) *MockChallengeMethod {
	mock := &MockChallengeMethod{ctrl: ctrl}
	mock.recorder = &MockChallengeMethodMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChallengeMethod) EXPECT() *MockChallengeMethodMockRecorder {
	return m.recorder
}

// BeginChallenge mocks base method.
func (m *MockChallengeMethod) BeginChallenge(ctx context.Context, user identity.UserID, challenge string) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginChallenge", ctx, user, challenge)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginChallenge indicates an expected call of BeginChallenge.
func (mr *MockChallengeMethodMockRecorder) BeginChallenge(ctx, user, challenge any) *MockChallengeMethodBeginChallengeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginChallenge", reflect.TypeOf((*MockChallengeMethod)(nil).BeginChallenge), ctx, user, challenge)
	return &MockChallengeMethodBeginChallengeCall{Call: call}
}

// MockChallengeMethodBeginChallengeCall wrap *gomock.Call
type MockChallengeMethodBeginChallengeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChallengeMethodBeginChallengeCall) Return(arg0 json.RawMessage, arg1 error) *MockChallengeMethodBeginChallengeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChallengeMethodBeginChallengeCall) Do(f func(context.Context, identity.UserID, string) (json.RawMessage, error)) *MockChallengeMethodBeginChallengeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChallengeMethodBeginChallengeCall) DoAndReturn(f func(context.Context, identity.UserID, string) (json.RawMessage, error)) *MockChallengeMethodBeginChallengeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Channel mocks base method.
func (m *MockChallengeMethod) Channel() factor.Channel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Channel")
	ret0, _ := ret[0].(factor.Channel)
	return ret0
}

// Channel indicates an expected call of Channel.
func (mr *MockChallengeMethodMockRecorder) Channel() *MockChallengeMethodChannelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Channel", reflect.TypeOf((*MockChallengeMethod)(nil).Channel))
	return &MockChallengeMethodChannelCall{Call: call}
}

// MockChallengeMethodChannelCall wrap *gomock.Call
type MockChallengeMethodChannelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChallengeMethodChannelCall) Return(arg0 factor.Channel) *MockChallengeMethodChannelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChallengeMethodChannelCall) Do(f func() factor.Channel) *MockChallengeMethodChannelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChallengeMethodChannelCall) DoAndReturn(f func() factor.Channel) *MockChallengeMethodChannelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Enrolled mocks base method.
func (m *MockChallengeMethod) Enrolled(ctx context.Context, user identity.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enrolled", ctx, user)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enrolled indicates an expected call of Enrolled.
func (mr *MockChallengeMethodMockRecorder) Enrolled(ctx, user any) *MockChallengeMethodEnrolledCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enrolled", reflect.TypeOf((*MockChallengeMethod)(nil).Enrolled), ctx, user)
	return &MockChallengeMethodEnrolledCall{Call: call}
}

// MockChallengeMethodEnrolledCall wrap *gomock.Call
type MockChallengeMethodEnrolledCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChallengeMethodEnrolledCall) Return(arg0 bool, arg1 error) *MockChallengeMethodEnrolledCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChallengeMethodEnrolledCall) Do(f func(context.Context, identity.UserID) (bool, error)) *MockChallengeMethodEnrolledCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChallengeMethodEnrolledCall) DoAndReturn(f func(context.Context, identity.UserID) (bool, error)) *MockChallengeMethodEnrolledCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockChallengeMethod) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockChallengeMethodMockRecorder) Name() *MockChallengeMethodNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockChallengeMethod)(nil).Name))
	return &MockChallengeMethodNameCall{Call: call}
}

// MockChallengeMethodNameCall wrap *gomock.Call
type MockChallengeMethodNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChallengeMethodNameCall) Return(arg0 string) *MockChallengeMethodNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChallengeMethodNameCall) Do(f func() string) *MockChallengeMethodNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChallengeMethodNameCall) DoAndReturn(f func() string) *MockChallengeMethodNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PresentedChallenge mocks base method.
func (m *MockChallengeMethod) PresentedChallenge(response []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresentedChallenge", response)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresentedChallenge indicates an expected call of PresentedChallenge.
func (mr *MockChallengeMethodMockRecorder) PresentedChallenge(response any) *MockChallengeMethodPresentedChallengeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentedChallenge", reflect.TypeOf((*MockChallengeMethod)(nil).PresentedChallenge), response)
	return &MockChallengeMethodPresentedChallengeCall{Call: call}
}

// MockChallengeMethodPresentedChallengeCall wrap *gomock.Call
type MockChallengeMethodPresentedChallengeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChallengeMethodPresentedChallengeCall) Return(arg0 string, arg1 error) *MockChallengeMethodPresentedChallengeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChallengeMethodPresentedChallengeCall) Do(f func([]byte) (string, error)) *MockChallengeMethodPresentedChallengeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChallengeMethodPresentedChallengeCall) DoAndReturn(f func([]byte) (string, error)) *MockChallengeMethodPresentedChallengeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Response mocks base method.
func (m *MockChallengeMethod) Response() mfa.ResponseFormat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Response")
	ret0, _ := ret[0].(mfa.ResponseFormat)
	return ret0
}

// Response indicates an expected call of Response.
func (mr *MockChallengeMethodMockRecorder) Response() *MockChallengeMethodResponseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Response", reflect.TypeOf((*MockChallengeMethod)(nil).Response))
	return &MockChallengeMethodResponseCall{Call: call}
}

// MockChallengeMethodResponseCall wrap *gomock.Call
type MockChallengeMethodResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChallengeMethodResponseCall) Return(arg0 mfa.ResponseFormat) *MockChallengeMethodResponseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChallengeMethodResponseCall) Do(f func() mfa.ResponseFormat) *MockChallengeMethodResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChallengeMethodResponseCall) DoAndReturn(f func() mfa.ResponseFormat) *MockChallengeMethodResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Verify mocks base method.
func (m *MockChallengeMethod) Verify(ctx context.Context, user identity.UserID, response []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, user, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockChallengeMethodMockRecorder) Verify(ctx, user, response any) *MockChallengeMethodVerifyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockChallengeMethod)(nil).Verify), ctx, user, response)
	return &MockChallengeMethodVerifyCall{Call: call}
}

// MockChallengeMethodVerifyCall wrap *gomock.Call
type MockChallengeMethodVerifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChallengeMethodVerifyCall) Return(arg0 error) *MockChallengeMethodVerifyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChallengeMethodVerifyCall) Do(f func(context.Context, identity.UserID, []byte) error) *MockChallengeMethodVerifyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChallengeMethodVerifyCall) DoAndReturn(f func(context.Context, identity.UserID, []byte) error) *MockChallengeMethodVerifyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
