// Code generated by MockGen. DO NOT EDIT.
// Source: messages.go
//
// Generated by this command:
//
//	mockgen -source=messages.go -destination=messages_mock_test.go -package=recovery_test -typed
//

// Package recovery_test is a generated GoMock package.
package recovery_test

import (
	reflect "reflect"
	time "time"

	recovery "github.com/kartaladev/scrty/recovery"
	gomock "go.uber.org/mock/gomock"
)

// MockMessages is a mock of Messages interface.
type MockMessages struct {
	ctrl     *gomock.Controller
	recorder *MockMessagesMockRecorder
	isgomock struct{}
}

// MockMessagesMockRecorder is the mock recorder for MockMessages.
type MockMessagesMockRecorder struct {
	mock *MockMessages
}

// NewMockMessages creates a new mock instance.
func NewMockMessages(ctrl *gomock.Controller) *MockMessages {
	mock := &MockMessages{ctrl: ctrl}
	mock.recorder = &MockMessagesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessages) EXPECT() *MockMessagesMockRecorder {
	return m.recorder
}

// Cancelled mocks base method.
func (m *MockMessages) Cancelled(n recovery.Notice) (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancelled", n)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// Cancelled indicates an expected call of Cancelled.
func (mr *MockMessagesMockRecorder) Cancelled(n any) *MockMessagesCancelledCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancelled", reflect.TypeOf((*MockMessages)(nil).Cancelled), n)
	return &MockMessagesCancelledCall{Call: call}
}

// MockMessagesCancelledCall wrap *gomock.Call
type MockMessagesCancelledCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessagesCancelledCall) Return(subject, body string) *MockMessagesCancelledCall {
	c.Call = c.Call.Return(subject, body)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessagesCancelledCall) Do(f func(recovery.Notice) (string, string)) *MockMessagesCancelledCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessagesCancelledCall) DoAndReturn(f func(recovery.Notice) (string, string)) *MockMessagesCancelledCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Held mocks base method.
func (m *MockMessages) Held(n recovery.Notice, cancelLink string, until time.Time) (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Held", n, cancelLink, until)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// Held indicates an expected call of Held.
func (mr *MockMessagesMockRecorder) Held(n, cancelLink, until any) *MockMessagesHeldCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Held", reflect.TypeOf((*MockMessages)(nil).Held), n, cancelLink, until)
	return &MockMessagesHeldCall{Call: call}
}

// MockMessagesHeldCall wrap *gomock.Call
type MockMessagesHeldCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessagesHeldCall) Return(subject, body string) *MockMessagesHeldCall {
	c.Call = c.Call.Return(subject, body)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessagesHeldCall) Do(f func(recovery.Notice, string, time.Time) (string, string)) *MockMessagesHeldCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessagesHeldCall) DoAndReturn(f func(recovery.Notice, string, time.Time) (string, string)) *MockMessagesHeldCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IssuedCode mocks base method.
func (m *MockMessages) IssuedCode(code string, until time.Time) (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuedCode", code, until)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// IssuedCode indicates an expected call of IssuedCode.
func (mr *MockMessagesMockRecorder) IssuedCode(code, until any) *MockMessagesIssuedCodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuedCode", reflect.TypeOf((*MockMessages)(nil).IssuedCode), code, until)
	return &MockMessagesIssuedCodeCall{Call: call}
}

// MockMessagesIssuedCodeCall wrap *gomock.Call
type MockMessagesIssuedCodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessagesIssuedCodeCall) Return(subject, body string) *MockMessagesIssuedCodeCall {
	c.Call = c.Call.Return(subject, body)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessagesIssuedCodeCall) Do(f func(string, time.Time) (string, string)) *MockMessagesIssuedCodeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessagesIssuedCodeCall) DoAndReturn(f func(string, time.Time) (string, string)) *MockMessagesIssuedCodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Recovered mocks base method.
func (m *MockMessages) Recovered(n recovery.Notice) (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recovered", n)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// Recovered indicates an expected call of Recovered.
func (mr *MockMessagesMockRecorder) Recovered(n any) *MockMessagesRecoveredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recovered", reflect.TypeOf((*MockMessages)(nil).Recovered), n)
	return &MockMessagesRecoveredCall{Call: call}
}

// MockMessagesRecoveredCall wrap *gomock.Call
type MockMessagesRecoveredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessagesRecoveredCall) Return(subject, body string) *MockMessagesRecoveredCall {
	c.Call = c.Call.Return(subject, body)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessagesRecoveredCall) Do(f func(recovery.Notice) (string, string)) *MockMessagesRecoveredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessagesRecoveredCall) DoAndReturn(f func(recovery.Notice) (string, string)) *MockMessagesRecoveredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Regenerated mocks base method.
func (m *MockMessages) Regenerated(at time.Time) (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Regenerated", at)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// Regenerated indicates an expected call of Regenerated.
func (mr *MockMessagesMockRecorder) Regenerated(at any) *MockMessagesRegeneratedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Regenerated", reflect.TypeOf((*MockMessages)(nil).Regenerated), at)
	return &MockMessagesRegeneratedCall{Call: call}
}

// MockMessagesRegeneratedCall wrap *gomock.Call
type MockMessagesRegeneratedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessagesRegeneratedCall) Return(subject, body string) *MockMessagesRegeneratedCall {
	c.Call = c.Call.Return(subject, body)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessagesRegeneratedCall) Do(f func(time.Time) (string, string)) *MockMessagesRegeneratedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessagesRegeneratedCall) DoAndReturn(f func(time.Time) (string, string)) *MockMessagesRegeneratedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
