// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/mfa (interfaces: Method,EnrolmentRemover)
//
// Generated by this command:
//
//	mockgen -destination=mfamethod_mock_test.go -package=recovery_test -typed github.com/kartaladev/scrty/mfa Method,EnrolmentRemover
//

// Package recovery_test is a generated GoMock package.
package recovery_test

import (
	context "context"
	reflect "reflect"

	factor "github.com/kartaladev/scrty/factor"
	identity "github.com/kartaladev/scrty/identity"
	mfa "github.com/kartaladev/scrty/mfa"
	gomock "go.uber.org/mock/gomock"
)

// MockMethod is a mock of Method interface.
type MockMethod struct {
	ctrl     *gomock.Controller
	recorder *MockMethodMockRecorder
	isgomock struct{}
}

// MockMethodMockRecorder is the mock recorder for MockMethod.
type MockMethodMockRecorder struct {
	mock *MockMethod
}

// NewMockMethod creates a new mock instance.
func NewMockMethod(ctrl *gomock.Controller) *MockMethod {
	mock := &MockMethod{ctrl: ctrl}
	mock.recorder = &MockMethodMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMethod) EXPECT() *MockMethodMockRecorder {
	return m.recorder
}

// Channel mocks base method.
func (m *MockMethod) Channel() factor.Channel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Channel")
	ret0, _ := ret[0].(factor.Channel)
	return ret0
}

// Channel indicates an expected call of Channel.
func (mr *MockMethodMockRecorder) Channel() *MockMethodChannelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Channel", reflect.TypeOf((*MockMethod)(nil).Channel))
	return &MockMethodChannelCall{Call: call}
}

// MockMethodChannelCall wrap *gomock.Call
type MockMethodChannelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMethodChannelCall) Return(arg0 factor.Channel) *MockMethodChannelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMethodChannelCall) Do(f func() factor.Channel) *MockMethodChannelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMethodChannelCall) DoAndReturn(f func() factor.Channel) *MockMethodChannelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Enrolled mocks base method.
func (m *MockMethod) Enrolled(ctx context.Context, user identity.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enrolled", ctx, user)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enrolled indicates an expected call of Enrolled.
func (mr *MockMethodMockRecorder) Enrolled(ctx, user any) *MockMethodEnrolledCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enrolled", reflect.TypeOf((*MockMethod)(nil).Enrolled), ctx, user)
	return &MockMethodEnrolledCall{Call: call}
}

// MockMethodEnrolledCall wrap *gomock.Call
type MockMethodEnrolledCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMethodEnrolledCall) Return(arg0 bool, arg1 error) *MockMethodEnrolledCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMethodEnrolledCall) Do(f func(context.Context, identity.UserID) (bool, error)) *MockMethodEnrolledCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMethodEnrolledCall) DoAndReturn(f func(context.Context, identity.UserID) (bool, error)) *MockMethodEnrolledCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockMethod) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockMethodMockRecorder) Name() *MockMethodNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockMethod)(nil).Name))
	return &MockMethodNameCall{Call: call}
}

// MockMethodNameCall wrap *gomock.Call
type MockMethodNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMethodNameCall) Return(arg0 string) *MockMethodNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMethodNameCall) Do(f func() string) *MockMethodNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMethodNameCall) DoAndReturn(f func() string) *MockMethodNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Response mocks base method.
func (m *MockMethod) Response() mfa.ResponseFormat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Response")
	ret0, _ := ret[0].(mfa.ResponseFormat)
	return ret0
}

// Response indicates an expected call of Response.
func (mr *MockMethodMockRecorder) Response() *MockMethodResponseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Response", reflect.TypeOf((*MockMethod)(nil).Response))
	return &MockMethodResponseCall{Call: call}
}

// MockMethodResponseCall wrap *gomock.Call
type MockMethodResponseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMethodResponseCall) Return(arg0 mfa.ResponseFormat) *MockMethodResponseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMethodResponseCall) Do(f func() mfa.ResponseFormat) *MockMethodResponseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMethodResponseCall) DoAndReturn(f func() mfa.ResponseFormat) *MockMethodResponseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Verify mocks base method.
func (m *MockMethod) Verify(ctx context.Context, user identity.UserID, response []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, user, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockMethodMockRecorder) Verify(ctx, user, response any) *MockMethodVerifyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockMethod)(nil).Verify), ctx, user, response)
	return &MockMethodVerifyCall{Call: call}
}

// MockMethodVerifyCall wrap *gomock.Call
type MockMethodVerifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMethodVerifyCall) Return(arg0 error) *MockMethodVerifyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMethodVerifyCall) Do(f func(context.Context, identity.UserID, []byte) error) *MockMethodVerifyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMethodVerifyCall) DoAndReturn(f func(context.Context, identity.UserID, []byte) error) *MockMethodVerifyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEnrolmentRemover is a mock of EnrolmentRemover interface.
type MockEnrolmentRemover struct {
	ctrl     *gomock.Controller
	recorder *MockEnrolmentRemoverMockRecorder
	isgomock struct{}
}

// MockEnrolmentRemoverMockRecorder is the mock recorder for MockEnrolmentRemover.
type MockEnrolmentRemoverMockRecorder struct {
	mock *MockEnrolmentRemover
}

// NewMockEnrolmentRemover creates a new mock instance.
func NewMockEnrolmentRemover(ctrl *gomock.Controller) *MockEnrolmentRemover {
	mock := &MockEnrolmentRemover{ctrl: ctrl}
	mock.recorder = &MockEnrolmentRemoverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrolmentRemover) EXPECT() *MockEnrolmentRemoverMockRecorder {
	return m.recorder
}

// RemoveEnrolment mocks base method.
func (m *MockEnrolmentRemover) RemoveEnrolment(ctx context.Context, user identity.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveEnrolment", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEnrolment indicates an expected call of RemoveEnrolment.
func (mr *MockEnrolmentRemoverMockRecorder) RemoveEnrolment(ctx, user any) *MockEnrolmentRemoverRemoveEnrolmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEnrolment", reflect.TypeOf((*MockEnrolmentRemover)(nil).RemoveEnrolment), ctx, user)
	return &MockEnrolmentRemoverRemoveEnrolmentCall{Call: call}
}

// MockEnrolmentRemoverRemoveEnrolmentCall wrap *gomock.Call
type MockEnrolmentRemoverRemoveEnrolmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrolmentRemoverRemoveEnrolmentCall) Return(arg0 error) *MockEnrolmentRemoverRemoveEnrolmentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrolmentRemoverRemoveEnrolmentCall) Do(f func(context.Context, identity.UserID) error) *MockEnrolmentRemoverRemoveEnrolmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrolmentRemoverRemoveEnrolmentCall) DoAndReturn(f func(context.Context, identity.UserID) error) *MockEnrolmentRemoverRemoveEnrolmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
