// Code generated by MockGen. DO NOT EDIT.
// Source: reset.go
//
// Generated by this command:
//
//	mockgen -source=reset.go -destination=reset_mock_test.go -package=recovery_test -typed
//

// Package recovery_test is a generated GoMock package.
package recovery_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	recovery "github.com/kartaladev/scrty/recovery"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticatorKind is a mock of AuthenticatorKind interface.
type MockAuthenticatorKind struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorKindMockRecorder
	isgomock struct{}
}

// MockAuthenticatorKindMockRecorder is the mock recorder for MockAuthenticatorKind.
type MockAuthenticatorKindMockRecorder struct {
	mock *MockAuthenticatorKind
}

// NewMockAuthenticatorKind creates a new mock instance.
func NewMockAuthenticatorKind(ctrl *gomock.Controller) *MockAuthenticatorKind {
	mock := &MockAuthenticatorKind{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorKindMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticatorKind) EXPECT() *MockAuthenticatorKindMockRecorder {
	return m.recorder
}

// Held mocks base method.
func (m *MockAuthenticatorKind) Held(ctx context.Context, user identity.UserID) ([]recovery.AuthenticatorRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Held", ctx, user)
	ret0, _ := ret[0].([]recovery.AuthenticatorRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Held indicates an expected call of Held.
func (mr *MockAuthenticatorKindMockRecorder) Held(ctx, user any) *MockAuthenticatorKindHeldCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Held", reflect.TypeOf((*MockAuthenticatorKind)(nil).Held), ctx, user)
	return &MockAuthenticatorKindHeldCall{Call: call}
}

// MockAuthenticatorKindHeldCall wrap *gomock.Call
type MockAuthenticatorKindHeldCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthenticatorKindHeldCall) Return(arg0 []recovery.AuthenticatorRef, arg1 error) *MockAuthenticatorKindHeldCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthenticatorKindHeldCall) Do(f func(context.Context, identity.UserID) ([]recovery.AuthenticatorRef, error)) *MockAuthenticatorKindHeldCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthenticatorKindHeldCall) DoAndReturn(f func(context.Context, identity.UserID) ([]recovery.AuthenticatorRef, error)) *MockAuthenticatorKindHeldCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Kind mocks base method.
func (m *MockAuthenticatorKind) Kind() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kind")
	ret0, _ := ret[0].(string)
	return ret0
}

// Kind indicates an expected call of Kind.
func (mr *MockAuthenticatorKindMockRecorder) Kind() *MockAuthenticatorKindKindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kind", reflect.TypeOf((*MockAuthenticatorKind)(nil).Kind))
	return &MockAuthenticatorKindKindCall{Call: call}
}

// MockAuthenticatorKindKindCall wrap *gomock.Call
type MockAuthenticatorKindKindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthenticatorKindKindCall) Return(arg0 string) *MockAuthenticatorKindKindCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthenticatorKindKindCall) Do(f func() string) *MockAuthenticatorKindKindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthenticatorKindKindCall) DoAndReturn(f func() string) *MockAuthenticatorKindKindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Remove mocks base method.
func (m *MockAuthenticatorKind) Remove(ctx context.Context, user identity.UserID, refs []recovery.AuthenticatorRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, user, refs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockAuthenticatorKindMockRecorder) Remove(ctx, user, refs any) *MockAuthenticatorKindRemoveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockAuthenticatorKind)(nil).Remove), ctx, user, refs)
	return &MockAuthenticatorKindRemoveCall{Call: call}
}

// MockAuthenticatorKindRemoveCall wrap *gomock.Call
type MockAuthenticatorKindRemoveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthenticatorKindRemoveCall) Return(arg0 error) *MockAuthenticatorKindRemoveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthenticatorKindRemoveCall) Do(f func(context.Context, identity.UserID, []recovery.AuthenticatorRef) error) *MockAuthenticatorKindRemoveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthenticatorKindRemoveCall) DoAndReturn(f func(context.Context, identity.UserID, []recovery.AuthenticatorRef) error) *MockAuthenticatorKindRemoveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
