// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/notify (interfaces: Sender,NonBlocking)
//
// Generated by this command:
//
//	mockgen -destination=sender_mock_test.go -package=recovery_test -typed github.com/kartaladev/scrty/notify Sender,NonBlocking
//

// Package recovery_test is a generated GoMock package.
package recovery_test

import (
	context "context"
	reflect "reflect"

	notify "github.com/kartaladev/scrty/notify"
	gomock "go.uber.org/mock/gomock"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockSender) Send(ctx context.Context, msg notify.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSenderMockRecorder) Send(ctx, msg any) *MockSenderSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSender)(nil).Send), ctx, msg)
	return &MockSenderSendCall{Call: call}
}

// MockSenderSendCall wrap *gomock.Call
type MockSenderSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSenderSendCall) Return(arg0 error) *MockSenderSendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSenderSendCall) Do(f func(context.Context, notify.Message) error) *MockSenderSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSenderSendCall) DoAndReturn(f func(context.Context, notify.Message) error) *MockSenderSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockNonBlocking is a mock of NonBlocking interface.
type MockNonBlocking struct {
	ctrl     *gomock.Controller
	recorder *MockNonBlockingMockRecorder
	isgomock struct{}
}

// MockNonBlockingMockRecorder is the mock recorder for MockNonBlocking.
type MockNonBlockingMockRecorder struct {
	mock *MockNonBlocking
}

// NewMockNonBlocking creates a new mock instance.
func NewMockNonBlocking(ctrl *gomock.Controller) *MockNonBlocking {
	mock := &MockNonBlocking{ctrl: ctrl}
	mock.recorder = &MockNonBlockingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNonBlocking) EXPECT() *MockNonBlockingMockRecorder {
	return m.recorder
}

// NonBlocking mocks base method.
func (m *MockNonBlocking) NonBlocking() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NonBlocking")
	ret0, _ := ret[0].(bool)
	return ret0
}

// NonBlocking indicates an expected call of NonBlocking.
func (mr *MockNonBlockingMockRecorder) NonBlocking() *MockNonBlockingNonBlockingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NonBlocking", reflect.TypeOf((*MockNonBlocking)(nil).NonBlocking))
	return &MockNonBlockingNonBlockingCall{Call: call}
}

// MockNonBlockingNonBlockingCall wrap *gomock.Call
type MockNonBlockingNonBlockingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNonBlockingNonBlockingCall) Return(arg0 bool) *MockNonBlockingNonBlockingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNonBlockingNonBlockingCall) Do(f func() bool) *MockNonBlockingNonBlockingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNonBlockingNonBlockingCall) DoAndReturn(f func() bool) *MockNonBlockingNonBlockingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
