// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=store_mock_test.go -package=recovery_test -typed
//

// Package recovery_test is a generated GoMock package.
package recovery_test

import (
	context "context"
	reflect "reflect"
	time "time"

	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockCodeStore is a mock of CodeStore interface.
type MockCodeStore struct {
	ctrl     *gomock.Controller
	recorder *MockCodeStoreMockRecorder
	isgomock struct{}
}

// MockCodeStoreMockRecorder is the mock recorder for MockCodeStore.
type MockCodeStoreMockRecorder struct {
	mock *MockCodeStore
}

// NewMockCodeStore creates a new mock instance.
func NewMockCodeStore(ctrl *gomock.Controller) *MockCodeStore {
	mock := &MockCodeStore{ctrl: ctrl}
	mock.recorder = &MockCodeStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeStore) EXPECT() *MockCodeStoreMockRecorder {
	return m.recorder
}

// DeleteUser mocks base method.
func (m *MockCodeStore) DeleteUser(ctx context.Context, user identity.UserID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockCodeStoreMockRecorder) DeleteUser(ctx, user any) *MockCodeStoreDeleteUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockCodeStore)(nil).DeleteUser), ctx, user)
	return &MockCodeStoreDeleteUserCall{Call: call}
}

// MockCodeStoreDeleteUserCall wrap *gomock.Call
type MockCodeStoreDeleteUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeStoreDeleteUserCall) Return(arg0 int, arg1 error) *MockCodeStoreDeleteUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeStoreDeleteUserCall) Do(f func(context.Context, identity.UserID) (int, error)) *MockCodeStoreDeleteUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeStoreDeleteUserCall) DoAndReturn(f func(context.Context, identity.UserID) (int, error)) *MockCodeStoreDeleteUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Match mocks base method.
func (m *MockCodeStore) Match(ctx context.Context, user identity.UserID, hash []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Match", ctx, user, hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Match indicates an expected call of Match.
func (mr *MockCodeStoreMockRecorder) Match(ctx, user, hash any) *MockCodeStoreMatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockCodeStore)(nil).Match), ctx, user, hash)
	return &MockCodeStoreMatchCall{Call: call}
}

// MockCodeStoreMatchCall wrap *gomock.Call
type MockCodeStoreMatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeStoreMatchCall) Return(arg0 bool, arg1 error) *MockCodeStoreMatchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeStoreMatchCall) Do(f func(context.Context, identity.UserID, []byte) (bool, error)) *MockCodeStoreMatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeStoreMatchCall) DoAndReturn(f func(context.Context, identity.UserID, []byte) (bool, error)) *MockCodeStoreMatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Remaining mocks base method.
func (m *MockCodeStore) Remaining(ctx context.Context, user identity.UserID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remaining", ctx, user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Remaining indicates an expected call of Remaining.
func (mr *MockCodeStoreMockRecorder) Remaining(ctx, user any) *MockCodeStoreRemainingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remaining", reflect.TypeOf((*MockCodeStore)(nil).Remaining), ctx, user)
	return &MockCodeStoreRemainingCall{Call: call}
}

// MockCodeStoreRemainingCall wrap *gomock.Call
type MockCodeStoreRemainingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeStoreRemainingCall) Return(arg0 int, arg1 error) *MockCodeStoreRemainingCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeStoreRemainingCall) Do(f func(context.Context, identity.UserID) (int, error)) *MockCodeStoreRemainingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeStoreRemainingCall) DoAndReturn(f func(context.Context, identity.UserID) (int, error)) *MockCodeStoreRemainingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReplaceSet mocks base method.
func (m *MockCodeStore) ReplaceSet(ctx context.Context, user identity.UserID, hashes [][]byte, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceSet", ctx, user, hashes, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceSet indicates an expected call of ReplaceSet.
func (mr *MockCodeStoreMockRecorder) ReplaceSet(ctx, user, hashes, at any) *MockCodeStoreReplaceSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceSet", reflect.TypeOf((*MockCodeStore)(nil).ReplaceSet), ctx, user, hashes, at)
	return &MockCodeStoreReplaceSetCall{Call: call}
}

// MockCodeStoreReplaceSetCall wrap *gomock.Call
type MockCodeStoreReplaceSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeStoreReplaceSetCall) Return(arg0 error) *MockCodeStoreReplaceSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeStoreReplaceSetCall) Do(f func(context.Context, identity.UserID, [][]byte, time.Time) error) *MockCodeStoreReplaceSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeStoreReplaceSetCall) DoAndReturn(f func(context.Context, identity.UserID, [][]byte, time.Time) error) *MockCodeStoreReplaceSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Spend mocks base method.
func (m *MockCodeStore) Spend(ctx context.Context, user identity.UserID, hash []byte, at time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Spend", ctx, user, hash, at)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Spend indicates an expected call of Spend.
func (mr *MockCodeStoreMockRecorder) Spend(ctx, user, hash, at any) *MockCodeStoreSpendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Spend", reflect.TypeOf((*MockCodeStore)(nil).Spend), ctx, user, hash, at)
	return &MockCodeStoreSpendCall{Call: call}
}

// MockCodeStoreSpendCall wrap *gomock.Call
type MockCodeStoreSpendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeStoreSpendCall) Return(arg0 bool, arg1 error) *MockCodeStoreSpendCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeStoreSpendCall) Do(f func(context.Context, identity.UserID, []byte, time.Time) (bool, error)) *MockCodeStoreSpendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeStoreSpendCall) DoAndReturn(f func(context.Context, identity.UserID, []byte, time.Time) (bool, error)) *MockCodeStoreSpendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
