// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/onetime (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=tokenstore_mock_test.go -package=recovery_test -typed -mock_names=Store=MockTokenStore github.com/kartaladev/scrty/onetime Store
//

// Package recovery_test is a generated GoMock package.
package recovery_test

import (
	context "context"
	reflect "reflect"
	time "time"

	onetime "github.com/kartaladev/scrty/onetime"
	id "github.com/kartaladev/scrty/pkg/id"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenStore is a mock of Store interface.
type MockTokenStore struct {
	ctrl     *gomock.Controller
	recorder *MockTokenStoreMockRecorder
	isgomock struct{}
}

// MockTokenStoreMockRecorder is the mock recorder for MockTokenStore.
type MockTokenStoreMockRecorder struct {
	mock *MockTokenStore
}

// NewMockTokenStore creates a new mock instance.
func NewMockTokenStore(ctrl *gomock.Controller) *MockTokenStore {
	mock := &MockTokenStore{ctrl: ctrl}
	mock.recorder = &MockTokenStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenStore) EXPECT() *MockTokenStoreMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockTokenStore) Consume(ctx context.Context, tokenID id.ID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, tokenID, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockTokenStoreMockRecorder) Consume(ctx, tokenID, at any) *MockTokenStoreConsumeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockTokenStore)(nil).Consume), ctx, tokenID, at)
	return &MockTokenStoreConsumeCall{Call: call}
}

// MockTokenStoreConsumeCall wrap *gomock.Call
type MockTokenStoreConsumeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenStoreConsumeCall) Return(arg0 error) *MockTokenStoreConsumeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenStoreConsumeCall) Do(f func(context.Context, id.ID, time.Time) error) *MockTokenStoreConsumeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenStoreConsumeCall) DoAndReturn(f func(context.Context, id.ID, time.Time) error) *MockTokenStoreConsumeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CountRecentBySubject mocks base method.
func (m *MockTokenStore) CountRecentBySubject(ctx context.Context, purpose, subject string, since time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecentBySubject", ctx, purpose, subject, since)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecentBySubject indicates an expected call of CountRecentBySubject.
func (mr *MockTokenStoreMockRecorder) CountRecentBySubject(ctx, purpose, subject, since any) *MockTokenStoreCountRecentBySubjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecentBySubject", reflect.TypeOf((*MockTokenStore)(nil).CountRecentBySubject), ctx, purpose, subject, since)
	return &MockTokenStoreCountRecentBySubjectCall{Call: call}
}

// MockTokenStoreCountRecentBySubjectCall wrap *gomock.Call
type MockTokenStoreCountRecentBySubjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenStoreCountRecentBySubjectCall) Return(arg0 int, arg1 error) *MockTokenStoreCountRecentBySubjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenStoreCountRecentBySubjectCall) Do(f func(context.Context, string, string, time.Time) (int, error)) *MockTokenStoreCountRecentBySubjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenStoreCountRecentBySubjectCall) DoAndReturn(f func(context.Context, string, string, time.Time) (int, error)) *MockTokenStoreCountRecentBySubjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByID mocks base method.
func (m *MockTokenStore) FindByID(ctx context.Context, tokenID id.ID) (*onetime.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, tokenID)
	ret0, _ := ret[0].(*onetime.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTokenStoreMockRecorder) FindByID(ctx, tokenID any) *MockTokenStoreFindByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTokenStore)(nil).FindByID), ctx, tokenID)
	return &MockTokenStoreFindByIDCall{Call: call}
}

// MockTokenStoreFindByIDCall wrap *gomock.Call
type MockTokenStoreFindByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenStoreFindByIDCall) Return(arg0 *onetime.Token, arg1 error) *MockTokenStoreFindByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenStoreFindByIDCall) Do(f func(context.Context, id.ID) (*onetime.Token, error)) *MockTokenStoreFindByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenStoreFindByIDCall) DoAndReturn(f func(context.Context, id.ID) (*onetime.Token, error)) *MockTokenStoreFindByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockTokenStore) Insert(ctx context.Context, tok onetime.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, tok)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockTokenStoreMockRecorder) Insert(ctx, tok any) *MockTokenStoreInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockTokenStore)(nil).Insert), ctx, tok)
	return &MockTokenStoreInsertCall{Call: call}
}

// MockTokenStoreInsertCall wrap *gomock.Call
type MockTokenStoreInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenStoreInsertCall) Return(arg0 error) *MockTokenStoreInsertCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenStoreInsertCall) Do(f func(context.Context, onetime.Token) error) *MockTokenStoreInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenStoreInsertCall) DoAndReturn(f func(context.Context, onetime.Token) error) *MockTokenStoreInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
