// Code generated by MockGen. DO NOT EDIT.
// Source: reset.go
//
// Generated by this command:
//
//	mockgen -source=reset.go -destination=reset_mock_test.go -package=mfa_test -typed
//

// Package mfa_test is a generated GoMock package.
package mfa_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRevoker is a mock of SessionRevoker interface.
type MockSessionRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRevokerMockRecorder
	isgomock struct{}
}

// MockSessionRevokerMockRecorder is the mock recorder for MockSessionRevoker.
type MockSessionRevokerMockRecorder struct {
	mock *MockSessionRevoker
}

// NewMockSessionRevoker creates a new mock instance.
func NewMockSessionRevoker(ctrl *gomock.Controller) *MockSessionRevoker {
	mock := &MockSessionRevoker{ctrl: ctrl}
	mock.recorder = &MockSessionRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRevoker) EXPECT() *MockSessionRevokerMockRecorder {
	return m.recorder
}

// DeleteByUser mocks base method.
func (m *MockSessionRevoker) DeleteByUser(ctx context.Context, user identity.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUser indicates an expected call of DeleteByUser.
func (mr *MockSessionRevokerMockRecorder) DeleteByUser(ctx, user any) *MockSessionRevokerDeleteByUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUser", reflect.TypeOf((*MockSessionRevoker)(nil).DeleteByUser), ctx, user)
	return &MockSessionRevokerDeleteByUserCall{Call: call}
}

// MockSessionRevokerDeleteByUserCall wrap *gomock.Call
type MockSessionRevokerDeleteByUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRevokerDeleteByUserCall) Return(arg0 error) *MockSessionRevokerDeleteByUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRevokerDeleteByUserCall) Do(f func(context.Context, identity.UserID) error) *MockSessionRevokerDeleteByUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRevokerDeleteByUserCall) DoAndReturn(f func(context.Context, identity.UserID) error) *MockSessionRevokerDeleteByUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEnrolmentRemover is a mock of EnrolmentRemover interface.
type MockEnrolmentRemover struct {
	ctrl     *gomock.Controller
	recorder *MockEnrolmentRemoverMockRecorder
	isgomock struct{}
}

// MockEnrolmentRemoverMockRecorder is the mock recorder for MockEnrolmentRemover.
type MockEnrolmentRemoverMockRecorder struct {
	mock *MockEnrolmentRemover
}

// NewMockEnrolmentRemover creates a new mock instance.
func NewMockEnrolmentRemover(ctrl *gomock.Controller) *MockEnrolmentRemover {
	mock := &MockEnrolmentRemover{ctrl: ctrl}
	mock.recorder = &MockEnrolmentRemoverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrolmentRemover) EXPECT() *MockEnrolmentRemoverMockRecorder {
	return m.recorder
}

// RemoveEnrolment mocks base method.
func (m *MockEnrolmentRemover) RemoveEnrolment(ctx context.Context, user identity.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveEnrolment", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEnrolment indicates an expected call of RemoveEnrolment.
func (mr *MockEnrolmentRemoverMockRecorder) RemoveEnrolment(ctx, user any) *MockEnrolmentRemoverRemoveEnrolmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEnrolment", reflect.TypeOf((*MockEnrolmentRemover)(nil).RemoveEnrolment), ctx, user)
	return &MockEnrolmentRemoverRemoveEnrolmentCall{Call: call}
}

// MockEnrolmentRemoverRemoveEnrolmentCall wrap *gomock.Call
type MockEnrolmentRemoverRemoveEnrolmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrolmentRemoverRemoveEnrolmentCall) Return(arg0 error) *MockEnrolmentRemoverRemoveEnrolmentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrolmentRemoverRemoveEnrolmentCall) Do(f func(context.Context, identity.UserID) error) *MockEnrolmentRemoverRemoveEnrolmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrolmentRemoverRemoveEnrolmentCall) DoAndReturn(f func(context.Context, identity.UserID) error) *MockEnrolmentRemoverRemoveEnrolmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
