// Code generated by MockGen. DO NOT EDIT.
// Source: attempts.go
//
// Generated by this command:
//
//	mockgen -source=attempts.go -package=policy_test -destination=attempts_mock_test.go -typed
//

// Package policy_test is a generated GoMock package.
package policy_test

import (
	context "context"
	reflect "reflect"
	time "time"

	policy "github.com/kartaladev/scrty/policy"
	gomock "go.uber.org/mock/gomock"
)

// MockAttemptStore is a mock of AttemptStore interface.
type MockAttemptStore struct {
	ctrl     *gomock.Controller
	recorder *MockAttemptStoreMockRecorder
	isgomock struct{}
}

// MockAttemptStoreMockRecorder is the mock recorder for MockAttemptStore.
type MockAttemptStoreMockRecorder struct {
	mock *MockAttemptStore
}

// NewMockAttemptStore creates a new mock instance.
func NewMockAttemptStore(ctrl *gomock.Controller) *MockAttemptStore {
	mock := &MockAttemptStore{ctrl: ctrl}
	mock.recorder = &MockAttemptStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttemptStore) EXPECT() *MockAttemptStoreMockRecorder {
	return m.recorder
}

// FailureCount mocks base method.
func (m *MockAttemptStore) FailureCount(ctx context.Context, username string, since time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailureCount", ctx, username, since)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FailureCount indicates an expected call of FailureCount.
func (mr *MockAttemptStoreMockRecorder) FailureCount(ctx, username, since any) *MockAttemptStoreFailureCountCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailureCount", reflect.TypeOf((*MockAttemptStore)(nil).FailureCount), ctx, username, since)
	return &MockAttemptStoreFailureCountCall{Call: call}
}

// MockAttemptStoreFailureCountCall wrap *gomock.Call
type MockAttemptStoreFailureCountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAttemptStoreFailureCountCall) Return(arg0 int, arg1 error) *MockAttemptStoreFailureCountCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAttemptStoreFailureCountCall) Do(f func(context.Context, string, time.Time) (int, error)) *MockAttemptStoreFailureCountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAttemptStoreFailureCountCall) DoAndReturn(f func(context.Context, string, time.Time) (int, error)) *MockAttemptStoreFailureCountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RecordFailure mocks base method.
func (m *MockAttemptStore) RecordFailure(ctx context.Context, username string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordFailure", ctx, username, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordFailure indicates an expected call of RecordFailure.
func (mr *MockAttemptStoreMockRecorder) RecordFailure(ctx, username, at any) *MockAttemptStoreRecordFailureCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFailure", reflect.TypeOf((*MockAttemptStore)(nil).RecordFailure), ctx, username, at)
	return &MockAttemptStoreRecordFailureCall{Call: call}
}

// MockAttemptStoreRecordFailureCall wrap *gomock.Call
type MockAttemptStoreRecordFailureCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAttemptStoreRecordFailureCall) Return(arg0 error) *MockAttemptStoreRecordFailureCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAttemptStoreRecordFailureCall) Do(f func(context.Context, string, time.Time) error) *MockAttemptStoreRecordFailureCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAttemptStoreRecordFailureCall) DoAndReturn(f func(context.Context, string, time.Time) error) *MockAttemptStoreRecordFailureCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Reset mocks base method.
func (m *MockAttemptStore) Reset(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockAttemptStoreMockRecorder) Reset(ctx, username any) *MockAttemptStoreResetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockAttemptStore)(nil).Reset), ctx, username)
	return &MockAttemptStoreResetCall{Call: call}
}

// MockAttemptStoreResetCall wrap *gomock.Call
type MockAttemptStoreResetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAttemptStoreResetCall) Return(arg0 error) *MockAttemptStoreResetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAttemptStoreResetCall) Do(f func(context.Context, string) error) *MockAttemptStoreResetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAttemptStoreResetCall) DoAndReturn(f func(context.Context, string) error) *MockAttemptStoreResetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAttemptReaper is a mock of AttemptReaper interface.
type MockAttemptReaper struct {
	ctrl     *gomock.Controller
	recorder *MockAttemptReaperMockRecorder
	isgomock struct{}
}

// MockAttemptReaperMockRecorder is the mock recorder for MockAttemptReaper.
type MockAttemptReaperMockRecorder struct {
	mock *MockAttemptReaper
}

// NewMockAttemptReaper creates a new mock instance.
func NewMockAttemptReaper(ctrl *gomock.Controller) *MockAttemptReaper {
	mock := &MockAttemptReaper{ctrl: ctrl}
	mock.recorder = &MockAttemptReaperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttemptReaper) EXPECT() *MockAttemptReaperMockRecorder {
	return m.recorder
}

// DeleteAttemptsBefore mocks base method.
func (m *MockAttemptReaper) DeleteAttemptsBefore(ctx context.Context, retainSince time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttemptsBefore", ctx, retainSince)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAttemptsBefore indicates an expected call of DeleteAttemptsBefore.
func (mr *MockAttemptReaperMockRecorder) DeleteAttemptsBefore(ctx, retainSince any) *MockAttemptReaperDeleteAttemptsBeforeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttemptsBefore", reflect.TypeOf((*MockAttemptReaper)(nil).DeleteAttemptsBefore), ctx, retainSince)
	return &MockAttemptReaperDeleteAttemptsBeforeCall{Call: call}
}

// MockAttemptReaperDeleteAttemptsBeforeCall wrap *gomock.Call
type MockAttemptReaperDeleteAttemptsBeforeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAttemptReaperDeleteAttemptsBeforeCall) Return(arg0 int, arg1 error) *MockAttemptReaperDeleteAttemptsBeforeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAttemptReaperDeleteAttemptsBeforeCall) Do(f func(context.Context, time.Time) (int, error)) *MockAttemptReaperDeleteAttemptsBeforeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAttemptReaperDeleteAttemptsBeforeCall) DoAndReturn(f func(context.Context, time.Time) (int, error)) *MockAttemptReaperDeleteAttemptsBeforeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockFailureStreakStore is a mock of FailureStreakStore interface.
type MockFailureStreakStore struct {
	ctrl     *gomock.Controller
	recorder *MockFailureStreakStoreMockRecorder
	isgomock struct{}
}

// MockFailureStreakStoreMockRecorder is the mock recorder for MockFailureStreakStore.
type MockFailureStreakStoreMockRecorder struct {
	mock *MockFailureStreakStore
}

// NewMockFailureStreakStore creates a new mock instance.
func NewMockFailureStreakStore(ctrl *gomock.Controller) *MockFailureStreakStore {
	mock := &MockFailureStreakStore{ctrl: ctrl}
	mock.recorder = &MockFailureStreakStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFailureStreakStore) EXPECT() *MockFailureStreakStoreMockRecorder {
	return m.recorder
}

// AddStreakFailure mocks base method.
func (m *MockFailureStreakStore) AddStreakFailure(ctx context.Context, username string, at, since time.Time, limit int) (policy.FailureStreak, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStreakFailure", ctx, username, at, since, limit)
	ret0, _ := ret[0].(policy.FailureStreak)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddStreakFailure indicates an expected call of AddStreakFailure.
func (mr *MockFailureStreakStoreMockRecorder) AddStreakFailure(ctx, username, at, since, limit any) *MockFailureStreakStoreAddStreakFailureCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStreakFailure", reflect.TypeOf((*MockFailureStreakStore)(nil).AddStreakFailure), ctx, username, at, since, limit)
	return &MockFailureStreakStoreAddStreakFailureCall{Call: call}
}

// MockFailureStreakStoreAddStreakFailureCall wrap *gomock.Call
type MockFailureStreakStoreAddStreakFailureCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFailureStreakStoreAddStreakFailureCall) Return(streak policy.FailureStreak, setHold bool, err error) *MockFailureStreakStoreAddStreakFailureCall {
	c.Call = c.Call.Return(streak, setHold, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFailureStreakStoreAddStreakFailureCall) Do(f func(context.Context, string, time.Time, time.Time, int) (policy.FailureStreak, bool, error)) *MockFailureStreakStoreAddStreakFailureCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFailureStreakStoreAddStreakFailureCall) DoAndReturn(f func(context.Context, string, time.Time, time.Time, int) (policy.FailureStreak, bool, error)) *MockFailureStreakStoreAddStreakFailureCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteStreaksBefore mocks base method.
func (m *MockFailureStreakStore) DeleteStreaksBefore(ctx context.Context, retainSince time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStreaksBefore", ctx, retainSince)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStreaksBefore indicates an expected call of DeleteStreaksBefore.
func (mr *MockFailureStreakStoreMockRecorder) DeleteStreaksBefore(ctx, retainSince any) *MockFailureStreakStoreDeleteStreaksBeforeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStreaksBefore", reflect.TypeOf((*MockFailureStreakStore)(nil).DeleteStreaksBefore), ctx, retainSince)
	return &MockFailureStreakStoreDeleteStreaksBeforeCall{Call: call}
}

// MockFailureStreakStoreDeleteStreaksBeforeCall wrap *gomock.Call
type MockFailureStreakStoreDeleteStreaksBeforeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFailureStreakStoreDeleteStreaksBeforeCall) Return(arg0 int, arg1 error) *MockFailureStreakStoreDeleteStreaksBeforeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFailureStreakStoreDeleteStreaksBeforeCall) Do(f func(context.Context, time.Time) (int, error)) *MockFailureStreakStoreDeleteStreaksBeforeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFailureStreakStoreDeleteStreaksBeforeCall) DoAndReturn(f func(context.Context, time.Time) (int, error)) *MockFailureStreakStoreDeleteStreaksBeforeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FailureStreak mocks base method.
func (m *MockFailureStreakStore) FailureStreak(ctx context.Context, username string, since time.Time) (policy.FailureStreak, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailureStreak", ctx, username, since)
	ret0, _ := ret[0].(policy.FailureStreak)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FailureStreak indicates an expected call of FailureStreak.
func (mr *MockFailureStreakStoreMockRecorder) FailureStreak(ctx, username, since any) *MockFailureStreakStoreFailureStreakCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailureStreak", reflect.TypeOf((*MockFailureStreakStore)(nil).FailureStreak), ctx, username, since)
	return &MockFailureStreakStoreFailureStreakCall{Call: call}
}

// MockFailureStreakStoreFailureStreakCall wrap *gomock.Call
type MockFailureStreakStoreFailureStreakCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFailureStreakStoreFailureStreakCall) Return(arg0 policy.FailureStreak, arg1 error) *MockFailureStreakStoreFailureStreakCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFailureStreakStoreFailureStreakCall) Do(f func(context.Context, string, time.Time) (policy.FailureStreak, error)) *MockFailureStreakStoreFailureStreakCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFailureStreakStoreFailureStreakCall) DoAndReturn(f func(context.Context, string, time.Time) (policy.FailureStreak, error)) *MockFailureStreakStoreFailureStreakCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
