// Code generated by MockGen. DO NOT EDIT.
// Source: concurrent.go
//
// Generated by this command:
//
//	mockgen -source=concurrent.go -package=policy_test -destination=concurrent_mock_test.go -typed
//

// Package policy_test is a generated GoMock package.
package policy_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionCounter is a mock of SessionCounter interface.
type MockSessionCounter struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCounterMockRecorder
	isgomock struct{}
}

// MockSessionCounterMockRecorder is the mock recorder for MockSessionCounter.
type MockSessionCounterMockRecorder struct {
	mock *MockSessionCounter
}

// NewMockSessionCounter creates a new mock instance.
func NewMockSessionCounter(ctrl *gomock.Controller) *MockSessionCounter {
	mock := &MockSessionCounter{ctrl: ctrl}
	mock.recorder = &MockSessionCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCounter) EXPECT() *MockSessionCounterMockRecorder {
	return m.recorder
}

// CountActiveByUser mocks base method.
func (m *MockSessionCounter) CountActiveByUser(ctx context.Context, user identity.UserID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByUser", ctx, user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveByUser indicates an expected call of CountActiveByUser.
func (mr *MockSessionCounterMockRecorder) CountActiveByUser(ctx, user any) *MockSessionCounterCountActiveByUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByUser", reflect.TypeOf((*MockSessionCounter)(nil).CountActiveByUser), ctx, user)
	return &MockSessionCounterCountActiveByUserCall{Call: call}
}

// MockSessionCounterCountActiveByUserCall wrap *gomock.Call
type MockSessionCounterCountActiveByUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionCounterCountActiveByUserCall) Return(arg0 int, arg1 error) *MockSessionCounterCountActiveByUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionCounterCountActiveByUserCall) Do(f func(context.Context, identity.UserID) (int, error)) *MockSessionCounterCountActiveByUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionCounterCountActiveByUserCall) DoAndReturn(f func(context.Context, identity.UserID) (int, error)) *MockSessionCounterCountActiveByUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
