// Code generated by MockGen. DO NOT EDIT.
// Source: mfa.go
//
// Generated by this command:
//
//	mockgen -source=mfa.go -package=policy_test -destination=mfa_mock_test.go -typed -exclude_interfaces=MFAOption,RefusalLogFlusher
//

// Package policy_test is a generated GoMock package.
package policy_test

import (
	context "context"
	reflect "reflect"

	factor "github.com/kartaladev/scrty/factor"
	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockMFAMethodLookup is a mock of MFAMethodLookup interface.
type MockMFAMethodLookup struct {
	ctrl     *gomock.Controller
	recorder *MockMFAMethodLookupMockRecorder
	isgomock struct{}
}

// MockMFAMethodLookupMockRecorder is the mock recorder for MockMFAMethodLookup.
type MockMFAMethodLookupMockRecorder struct {
	mock *MockMFAMethodLookup
}

// NewMockMFAMethodLookup creates a new mock instance.
func NewMockMFAMethodLookup(ctrl *gomock.Controller) *MockMFAMethodLookup {
	mock := &MockMFAMethodLookup{ctrl: ctrl}
	mock.recorder = &MockMFAMethodLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMFAMethodLookup) EXPECT() *MockMFAMethodLookupMockRecorder {
	return m.recorder
}

// Channel mocks base method.
func (m *MockMFAMethodLookup) Channel() factor.Channel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Channel")
	ret0, _ := ret[0].(factor.Channel)
	return ret0
}

// Channel indicates an expected call of Channel.
func (mr *MockMFAMethodLookupMockRecorder) Channel() *MockMFAMethodLookupChannelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Channel", reflect.TypeOf((*MockMFAMethodLookup)(nil).Channel))
	return &MockMFAMethodLookupChannelCall{Call: call}
}

// MockMFAMethodLookupChannelCall wrap *gomock.Call
type MockMFAMethodLookupChannelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMFAMethodLookupChannelCall) Return(arg0 factor.Channel) *MockMFAMethodLookupChannelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMFAMethodLookupChannelCall) Do(f func() factor.Channel) *MockMFAMethodLookupChannelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMFAMethodLookupChannelCall) DoAndReturn(f func() factor.Channel) *MockMFAMethodLookupChannelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Enrolled mocks base method.
func (m *MockMFAMethodLookup) Enrolled(ctx context.Context, user identity.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enrolled", ctx, user)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enrolled indicates an expected call of Enrolled.
func (mr *MockMFAMethodLookupMockRecorder) Enrolled(ctx, user any) *MockMFAMethodLookupEnrolledCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enrolled", reflect.TypeOf((*MockMFAMethodLookup)(nil).Enrolled), ctx, user)
	return &MockMFAMethodLookupEnrolledCall{Call: call}
}

// MockMFAMethodLookupEnrolledCall wrap *gomock.Call
type MockMFAMethodLookupEnrolledCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMFAMethodLookupEnrolledCall) Return(arg0 bool, arg1 error) *MockMFAMethodLookupEnrolledCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMFAMethodLookupEnrolledCall) Do(f func(context.Context, identity.UserID) (bool, error)) *MockMFAMethodLookupEnrolledCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMFAMethodLookupEnrolledCall) DoAndReturn(f func(context.Context, identity.UserID) (bool, error)) *MockMFAMethodLookupEnrolledCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockMFAMethodLookup) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockMFAMethodLookupMockRecorder) Name() *MockMFAMethodLookupNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockMFAMethodLookup)(nil).Name))
	return &MockMFAMethodLookupNameCall{Call: call}
}

// MockMFAMethodLookupNameCall wrap *gomock.Call
type MockMFAMethodLookupNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMFAMethodLookupNameCall) Return(arg0 string) *MockMFAMethodLookupNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMFAMethodLookupNameCall) Do(f func() string) *MockMFAMethodLookupNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMFAMethodLookupNameCall) DoAndReturn(f func() string) *MockMFAMethodLookupNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
