// Code generated by MockGen. DO NOT EDIT.
// Source: policy.go
//
// Generated by this command:
//
//	mockgen -source=policy.go -package=policy_test -destination=mocks_test.go -typed
//

// Package policy_test is a generated GoMock package.
package policy_test

import (
	context "context"
	reflect "reflect"

	policy "github.com/kartaladev/scrty/policy"
	gomock "go.uber.org/mock/gomock"
)

// MockChallenger is a mock of Challenger interface.
type MockChallenger struct {
	ctrl     *gomock.Controller
	recorder *MockChallengerMockRecorder
	isgomock struct{}
}

// MockChallengerMockRecorder is the mock recorder for MockChallenger.
type MockChallengerMockRecorder struct {
	mock *MockChallenger
}

// NewMockChallenger creates a new mock instance.
func NewMockChallenger(ctrl *gomock.Controller) *MockChallenger {
	mock := &MockChallenger{ctrl: ctrl}
	mock.recorder = &MockChallengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChallenger) EXPECT() *MockChallengerMockRecorder {
	return m.recorder
}

// Challenges mocks base method.
func (m *MockChallenger) Challenges() []policy.ChallengeKind {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Challenges")
	ret0, _ := ret[0].([]policy.ChallengeKind)
	return ret0
}

// Challenges indicates an expected call of Challenges.
func (mr *MockChallengerMockRecorder) Challenges() *MockChallengerChallengesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Challenges", reflect.TypeOf((*MockChallenger)(nil).Challenges))
	return &MockChallengerChallengesCall{Call: call}
}

// MockChallengerChallengesCall wrap *gomock.Call
type MockChallengerChallengesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChallengerChallengesCall) Return(arg0 []policy.ChallengeKind) *MockChallengerChallengesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChallengerChallengesCall) Do(f func() []policy.ChallengeKind) *MockChallengerChallengesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChallengerChallengesCall) DoAndReturn(f func() []policy.ChallengeKind) *MockChallengerChallengesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockPolicy is a mock of Policy interface.
type MockPolicy struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyMockRecorder
	isgomock struct{}
}

// MockPolicyMockRecorder is the mock recorder for MockPolicy.
type MockPolicyMockRecorder struct {
	mock *MockPolicy
}

// NewMockPolicy creates a new mock instance.
func NewMockPolicy(ctrl *gomock.Controller) *MockPolicy {
	mock := &MockPolicy{ctrl: ctrl}
	mock.recorder = &MockPolicyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicy) EXPECT() *MockPolicyMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockPolicy) Evaluate(ctx context.Context, in *policy.Input) policy.Decision {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, in)
	ret0, _ := ret[0].(policy.Decision)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockPolicyMockRecorder) Evaluate(ctx, in any) *MockPolicyEvaluateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockPolicy)(nil).Evaluate), ctx, in)
	return &MockPolicyEvaluateCall{Call: call}
}

// MockPolicyEvaluateCall wrap *gomock.Call
type MockPolicyEvaluateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyEvaluateCall) Return(arg0 policy.Decision) *MockPolicyEvaluateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyEvaluateCall) Do(f func(context.Context, *policy.Input) policy.Decision) *MockPolicyEvaluateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyEvaluateCall) DoAndReturn(f func(context.Context, *policy.Input) policy.Decision) *MockPolicyEvaluateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockPolicy) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPolicyMockRecorder) Name() *MockPolicyNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPolicy)(nil).Name))
	return &MockPolicyNameCall{Call: call}
}

// MockPolicyNameCall wrap *gomock.Call
type MockPolicyNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyNameCall) Return(arg0 string) *MockPolicyNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyNameCall) Do(f func() string) *MockPolicyNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyNameCall) DoAndReturn(f func() string) *MockPolicyNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Phases mocks base method.
func (m *MockPolicy) Phases() []policy.Phase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Phases")
	ret0, _ := ret[0].([]policy.Phase)
	return ret0
}

// Phases indicates an expected call of Phases.
func (mr *MockPolicyMockRecorder) Phases() *MockPolicyPhasesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Phases", reflect.TypeOf((*MockPolicy)(nil).Phases))
	return &MockPolicyPhasesCall{Call: call}
}

// MockPolicyPhasesCall wrap *gomock.Call
type MockPolicyPhasesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyPhasesCall) Return(arg0 []policy.Phase) *MockPolicyPhasesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyPhasesCall) Do(f func() []policy.Phase) *MockPolicyPhasesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyPhasesCall) DoAndReturn(f func() []policy.Phase) *MockPolicyPhasesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
