// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/identity (interfaces: MFARequirementLookup)
//
// Generated by this command:
//
//	mockgen -destination=requirementlookup_mock_test.go -package=policy_test -typed github.com/kartaladev/scrty/identity MFARequirementLookup
//

// Package policy_test is a generated GoMock package.
package policy_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockMFARequirementLookup is a mock of MFARequirementLookup interface.
type MockMFARequirementLookup struct {
	ctrl     *gomock.Controller
	recorder *MockMFARequirementLookupMockRecorder
	isgomock struct{}
}

// MockMFARequirementLookupMockRecorder is the mock recorder for MockMFARequirementLookup.
type MockMFARequirementLookupMockRecorder struct {
	mock *MockMFARequirementLookup
}

// NewMockMFARequirementLookup creates a new mock instance.
func NewMockMFARequirementLookup(ctrl *gomock.Controller) *MockMFARequirementLookup {
	mock := &MockMFARequirementLookup{ctrl: ctrl}
	mock.recorder = &MockMFARequirementLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMFARequirementLookup) EXPECT() *MockMFARequirementLookupMockRecorder {
	return m.recorder
}

// Required mocks base method.
func (m *MockMFARequirementLookup) Required(ctx context.Context, userID identity.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Required", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Required indicates an expected call of Required.
func (mr *MockMFARequirementLookupMockRecorder) Required(ctx, userID any) *MockMFARequirementLookupRequiredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Required", reflect.TypeOf((*MockMFARequirementLookup)(nil).Required), ctx, userID)
	return &MockMFARequirementLookupRequiredCall{Call: call}
}

// MockMFARequirementLookupRequiredCall wrap *gomock.Call
type MockMFARequirementLookupRequiredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMFARequirementLookupRequiredCall) Return(arg0 bool, arg1 error) *MockMFARequirementLookupRequiredCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMFARequirementLookupRequiredCall) Do(f func(context.Context, identity.UserID) (bool, error)) *MockMFARequirementLookupRequiredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMFARequirementLookupRequiredCall) DoAndReturn(f func(context.Context, identity.UserID) (bool, error)) *MockMFARequirementLookupRequiredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
