// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -package=apikey_test -destination=mocks_test.go -typed
//

// Package apikey_test is a generated GoMock package.
package apikey_test

import (
	context "context"
	reflect "reflect"
	time "time"

	apikey "github.com/kartaladev/scrty/apikey"
	identity "github.com/kartaladev/scrty/identity"
	id "github.com/kartaladev/scrty/pkg/id"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStore) Get(ctx context.Context, keyID id.ID) (apikey.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, keyID)
	ret0, _ := ret[0].(apikey.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStoreMockRecorder) Get(ctx, keyID any) *MockStoreGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStore)(nil).Get), ctx, keyID)
	return &MockStoreGetCall{Call: call}
}

// MockStoreGetCall wrap *gomock.Call
type MockStoreGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreGetCall) Return(arg0 apikey.Key, arg1 error) *MockStoreGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreGetCall) Do(f func(context.Context, id.ID) (apikey.Key, error)) *MockStoreGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreGetCall) DoAndReturn(f func(context.Context, id.ID) (apikey.Key, error)) *MockStoreGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockStore) List(ctx context.Context, principal identity.UserID) ([]apikey.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, principal)
	ret0, _ := ret[0].([]apikey.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStoreMockRecorder) List(ctx, principal any) *MockStoreListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStore)(nil).List), ctx, principal)
	return &MockStoreListCall{Call: call}
}

// MockStoreListCall wrap *gomock.Call
type MockStoreListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreListCall) Return(arg0 []apikey.Key, arg1 error) *MockStoreListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreListCall) Do(f func(context.Context, identity.UserID) ([]apikey.Key, error)) *MockStoreListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreListCall) DoAndReturn(f func(context.Context, identity.UserID) ([]apikey.Key, error)) *MockStoreListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Put mocks base method.
func (m *MockStore) Put(ctx context.Context, rec apikey.Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockStoreMockRecorder) Put(ctx, rec any) *MockStorePutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockStore)(nil).Put), ctx, rec)
	return &MockStorePutCall{Call: call}
}

// MockStorePutCall wrap *gomock.Call
type MockStorePutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStorePutCall) Return(arg0 error) *MockStorePutCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStorePutCall) Do(f func(context.Context, apikey.Key) error) *MockStorePutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStorePutCall) DoAndReturn(f func(context.Context, apikey.Key) error) *MockStorePutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Revoke mocks base method.
func (m *MockStore) Revoke(ctx context.Context, keyID id.ID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, keyID, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockStoreMockRecorder) Revoke(ctx, keyID, at any) *MockStoreRevokeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockStore)(nil).Revoke), ctx, keyID, at)
	return &MockStoreRevokeCall{Call: call}
}

// MockStoreRevokeCall wrap *gomock.Call
type MockStoreRevokeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreRevokeCall) Return(arg0 error) *MockStoreRevokeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreRevokeCall) Do(f func(context.Context, id.ID, time.Time) error) *MockStoreRevokeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreRevokeCall) DoAndReturn(f func(context.Context, id.ID, time.Time) error) *MockStoreRevokeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TouchLastUsed mocks base method.
func (m *MockStore) TouchLastUsed(ctx context.Context, keyID id.ID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLastUsed", ctx, keyID, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchLastUsed indicates an expected call of TouchLastUsed.
func (mr *MockStoreMockRecorder) TouchLastUsed(ctx, keyID, at any) *MockStoreTouchLastUsedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLastUsed", reflect.TypeOf((*MockStore)(nil).TouchLastUsed), ctx, keyID, at)
	return &MockStoreTouchLastUsedCall{Call: call}
}

// MockStoreTouchLastUsedCall wrap *gomock.Call
type MockStoreTouchLastUsedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreTouchLastUsedCall) Return(arg0 error) *MockStoreTouchLastUsedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreTouchLastUsedCall) Do(f func(context.Context, id.ID, time.Time) error) *MockStoreTouchLastUsedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreTouchLastUsedCall) DoAndReturn(f func(context.Context, id.ID, time.Time) error) *MockStoreTouchLastUsedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
