// Code generated by MockGen. DO NOT EDIT.
// Source: ../../ratelimit/limiter.go
//
// Generated by this command:
//
//	mockgen -source=../../ratelimit/limiter.go -package=unavailable_test -destination=limiter_mock_test.go -typed
//

// Package unavailable_test is a generated GoMock package.
package unavailable_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLimiter is a mock of Limiter interface.
type MockLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockLimiterMockRecorder
	isgomock struct{}
}

// MockLimiterMockRecorder is the mock recorder for MockLimiter.
type MockLimiterMockRecorder struct {
	mock *MockLimiter
}

// NewMockLimiter creates a new mock instance.
func NewMockLimiter(ctrl *gomock.Controller) *MockLimiter {
	mock := &MockLimiter{ctrl: ctrl}
	mock.recorder = &MockLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimiter) EXPECT() *MockLimiterMockRecorder {
	return m.recorder
}

// Exceeded mocks base method.
func (m *MockLimiter) Exceeded(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exceeded", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exceeded indicates an expected call of Exceeded.
func (mr *MockLimiterMockRecorder) Exceeded(ctx, key any) *MockLimiterExceededCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exceeded", reflect.TypeOf((*MockLimiter)(nil).Exceeded), ctx, key)
	return &MockLimiterExceededCall{Call: call}
}

// MockLimiterExceededCall wrap *gomock.Call
type MockLimiterExceededCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLimiterExceededCall) Return(arg0 bool, arg1 error) *MockLimiterExceededCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLimiterExceededCall) Do(f func(context.Context, string) (bool, error)) *MockLimiterExceededCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLimiterExceededCall) DoAndReturn(f func(context.Context, string) (bool, error)) *MockLimiterExceededCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RecordFailure mocks base method.
func (m *MockLimiter) RecordFailure(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordFailure", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordFailure indicates an expected call of RecordFailure.
func (mr *MockLimiterMockRecorder) RecordFailure(ctx, key any) *MockLimiterRecordFailureCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFailure", reflect.TypeOf((*MockLimiter)(nil).RecordFailure), ctx, key)
	return &MockLimiterRecordFailureCall{Call: call}
}

// MockLimiterRecordFailureCall wrap *gomock.Call
type MockLimiterRecordFailureCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLimiterRecordFailureCall) Return(arg0 error) *MockLimiterRecordFailureCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLimiterRecordFailureCall) Do(f func(context.Context, string) error) *MockLimiterRecordFailureCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLimiterRecordFailureCall) DoAndReturn(f func(context.Context, string) error) *MockLimiterRecordFailureCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
