// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/identity (interfaces: RoleLoader)
//
// Generated by this command:
//
//	mockgen -destination=roleloader_mock_test.go -package=authorize_test -typed github.com/kartaladev/scrty/identity RoleLoader
//

// Package authorize_test is a generated GoMock package.
package authorize_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleLoader is a mock of RoleLoader interface.
type MockRoleLoader struct {
	ctrl     *gomock.Controller
	recorder *MockRoleLoaderMockRecorder
	isgomock struct{}
}

// MockRoleLoaderMockRecorder is the mock recorder for MockRoleLoader.
type MockRoleLoaderMockRecorder struct {
	mock *MockRoleLoader
}

// NewMockRoleLoader creates a new mock instance.
func NewMockRoleLoader(ctrl *gomock.Controller) *MockRoleLoader {
	mock := &MockRoleLoader{ctrl: ctrl}
	mock.recorder = &MockRoleLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleLoader) EXPECT() *MockRoleLoaderMockRecorder {
	return m.recorder
}

// LoadPrivileges mocks base method.
func (m *MockRoleLoader) LoadPrivileges(ctx context.Context, role string) ([]*identity.ResourcePrivileges, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPrivileges", ctx, role)
	ret0, _ := ret[0].([]*identity.ResourcePrivileges)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadPrivileges indicates an expected call of LoadPrivileges.
func (mr *MockRoleLoaderMockRecorder) LoadPrivileges(ctx, role any) *MockRoleLoaderLoadPrivilegesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPrivileges", reflect.TypeOf((*MockRoleLoader)(nil).LoadPrivileges), ctx, role)
	return &MockRoleLoaderLoadPrivilegesCall{Call: call}
}

// MockRoleLoaderLoadPrivilegesCall wrap *gomock.Call
type MockRoleLoaderLoadPrivilegesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRoleLoaderLoadPrivilegesCall) Return(arg0 []*identity.ResourcePrivileges, arg1 error) *MockRoleLoaderLoadPrivilegesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRoleLoaderLoadPrivilegesCall) Do(f func(context.Context, string) ([]*identity.ResourcePrivileges, error)) *MockRoleLoaderLoadPrivilegesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRoleLoaderLoadPrivilegesCall) DoAndReturn(f func(context.Context, string) ([]*identity.ResourcePrivileges, error)) *MockRoleLoaderLoadPrivilegesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
