// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/signingkey (interfaces: KeySource)
//
// Generated by this command:
//
//	mockgen -destination=keysource_mock_test.go -package=token_test -typed github.com/kartaladev/scrty/signingkey KeySource
//

// Package token_test is a generated GoMock package.
package token_test

import (
	crypto "crypto"
	reflect "reflect"

	signingkey "github.com/kartaladev/scrty/signingkey"
	gomock "go.uber.org/mock/gomock"
)

// MockKeySource is a mock of KeySource interface.
type MockKeySource struct {
	ctrl     *gomock.Controller
	recorder *MockKeySourceMockRecorder
	isgomock struct{}
}

// MockKeySourceMockRecorder is the mock recorder for MockKeySource.
type MockKeySourceMockRecorder struct {
	mock *MockKeySource
}

// NewMockKeySource creates a new mock instance.
func NewMockKeySource(ctrl *gomock.Controller) *MockKeySource {
	mock := &MockKeySource{ctrl: ctrl}
	mock.recorder = &MockKeySourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeySource) EXPECT() *MockKeySourceMockRecorder {
	return m.recorder
}

// GetSigner mocks base method.
func (m *MockKeySource) GetSigner(alg signingkey.Alg) (string, crypto.Signer, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSigner", alg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(crypto.Signer)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetSigner indicates an expected call of GetSigner.
func (mr *MockKeySourceMockRecorder) GetSigner(alg any) *MockKeySourceGetSignerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSigner", reflect.TypeOf((*MockKeySource)(nil).GetSigner), alg)
	return &MockKeySourceGetSignerCall{Call: call}
}

// MockKeySourceGetSignerCall wrap *gomock.Call
type MockKeySourceGetSignerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeySourceGetSignerCall) Return(kid string, signer crypto.Signer, ok bool) *MockKeySourceGetSignerCall {
	c.Call = c.Call.Return(kid, signer, ok)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeySourceGetSignerCall) Do(f func(signingkey.Alg) (string, crypto.Signer, bool)) *MockKeySourceGetSignerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeySourceGetSignerCall) DoAndReturn(f func(signingkey.Alg) (string, crypto.Signer, bool)) *MockKeySourceGetSignerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VerificationKeys mocks base method.
func (m *MockKeySource) VerificationKeys() ([]signingkey.PublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerificationKeys")
	ret0, _ := ret[0].([]signingkey.PublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerificationKeys indicates an expected call of VerificationKeys.
func (mr *MockKeySourceMockRecorder) VerificationKeys() *MockKeySourceVerificationKeysCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerificationKeys", reflect.TypeOf((*MockKeySource)(nil).VerificationKeys))
	return &MockKeySourceVerificationKeysCall{Call: call}
}

// MockKeySourceVerificationKeysCall wrap *gomock.Call
type MockKeySourceVerificationKeysCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeySourceVerificationKeysCall) Return(arg0 []signingkey.PublicKey, arg1 error) *MockKeySourceVerificationKeysCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeySourceVerificationKeysCall) Do(f func() ([]signingkey.PublicKey, error)) *MockKeySourceVerificationKeysCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeySourceVerificationKeysCall) DoAndReturn(f func() ([]signingkey.PublicKey, error)) *MockKeySourceVerificationKeysCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
