// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/authorize (interfaces: Authorizer)
//
// Generated by this command:
//
//	mockgen -destination=authorizer_mock_test.go -package=fibersec_test -typed github.com/kartaladev/scrty/authorize Authorizer
//

// Package fibersec_test is a generated GoMock package.
package fibersec_test

import (
	context "context"
	reflect "reflect"

	authorize "github.com/kartaladev/scrty/authorize"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthorizer is a mock of Authorizer interface.
type MockAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerMockRecorder
	isgomock struct{}
}

// MockAuthorizerMockRecorder is the mock recorder for MockAuthorizer.
type MockAuthorizerMockRecorder struct {
	mock *MockAuthorizer
}

// NewMockAuthorizer creates a new mock instance.
func NewMockAuthorizer(ctrl *gomock.Controller) *MockAuthorizer {
	mock := &MockAuthorizer{ctrl: ctrl}
	mock.recorder = &MockAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizer) EXPECT() *MockAuthorizerMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockAuthorizer) Authorize(ctx context.Context, attrs authorize.Attributes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, attrs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Authorize indicates an expected call of Authorize.
func (mr *MockAuthorizerMockRecorder) Authorize(ctx, attrs any) *MockAuthorizerAuthorizeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockAuthorizer)(nil).Authorize), ctx, attrs)
	return &MockAuthorizerAuthorizeCall{Call: call}
}

// MockAuthorizerAuthorizeCall wrap *gomock.Call
type MockAuthorizerAuthorizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthorizerAuthorizeCall) Return(arg0 error) *MockAuthorizerAuthorizeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthorizerAuthorizeCall) Do(f func(context.Context, authorize.Attributes) error) *MockAuthorizerAuthorizeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthorizerAuthorizeCall) DoAndReturn(f func(context.Context, authorize.Attributes) error) *MockAuthorizerAuthorizeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
