// Code generated by MockGen. DO NOT EDIT.
// Source: sessions.go
//
// Generated by this command:
//
//	mockgen -source=sessions.go -destination=sessions_mock_test.go -package=passkey_test -typed
//

// Package passkey_test is a generated GoMock package.
package passkey_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRevoker is a mock of SessionRevoker interface.
type MockSessionRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRevokerMockRecorder
	isgomock struct{}
}

// MockSessionRevokerMockRecorder is the mock recorder for MockSessionRevoker.
type MockSessionRevokerMockRecorder struct {
	mock *MockSessionRevoker
}

// NewMockSessionRevoker creates a new mock instance.
func NewMockSessionRevoker(ctrl *gomock.Controller) *MockSessionRevoker {
	mock := &MockSessionRevoker{ctrl: ctrl}
	mock.recorder = &MockSessionRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRevoker) EXPECT() *MockSessionRevokerMockRecorder {
	return m.recorder
}

// DeleteByUser mocks base method.
func (m *MockSessionRevoker) DeleteByUser(ctx context.Context, user identity.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUser indicates an expected call of DeleteByUser.
func (mr *MockSessionRevokerMockRecorder) DeleteByUser(ctx, user any) *MockSessionRevokerDeleteByUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUser", reflect.TypeOf((*MockSessionRevoker)(nil).DeleteByUser), ctx, user)
	return &MockSessionRevokerDeleteByUserCall{Call: call}
}

// MockSessionRevokerDeleteByUserCall wrap *gomock.Call
type MockSessionRevokerDeleteByUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRevokerDeleteByUserCall) Return(arg0 error) *MockSessionRevokerDeleteByUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRevokerDeleteByUserCall) Do(f func(context.Context, identity.UserID) error) *MockSessionRevokerDeleteByUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRevokerDeleteByUserCall) DoAndReturn(f func(context.Context, identity.UserID) error) *MockSessionRevokerDeleteByUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteByUserExcept mocks base method.
func (m *MockSessionRevoker) DeleteByUserExcept(ctx context.Context, user identity.UserID, keep string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserExcept", ctx, user, keep)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByUserExcept indicates an expected call of DeleteByUserExcept.
func (mr *MockSessionRevokerMockRecorder) DeleteByUserExcept(ctx, user, keep any) *MockSessionRevokerDeleteByUserExceptCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserExcept", reflect.TypeOf((*MockSessionRevoker)(nil).DeleteByUserExcept), ctx, user, keep)
	return &MockSessionRevokerDeleteByUserExceptCall{Call: call}
}

// MockSessionRevokerDeleteByUserExceptCall wrap *gomock.Call
type MockSessionRevokerDeleteByUserExceptCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRevokerDeleteByUserExceptCall) Return(arg0 int, arg1 error) *MockSessionRevokerDeleteByUserExceptCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRevokerDeleteByUserExceptCall) Do(f func(context.Context, identity.UserID, string) (int, error)) *MockSessionRevokerDeleteByUserExceptCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRevokerDeleteByUserExceptCall) DoAndReturn(f func(context.Context, identity.UserID, string) (int, error)) *MockSessionRevokerDeleteByUserExceptCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
