// Code generated by MockGen. DO NOT EDIT.
// Source: verifier.go
//
// Generated by this command:
//
//	mockgen -source=verifier.go -destination=verifier_mock_test.go -package=passkey_test -typed
//

// Package passkey_test is a generated GoMock package.
package passkey_test

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	passkey "github.com/kartaladev/scrty/passkey"
	gomock "go.uber.org/mock/gomock"
)

// MockVerifier is a mock of Verifier interface.
type MockVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockVerifierMockRecorder
	isgomock struct{}
}

// MockVerifierMockRecorder is the mock recorder for MockVerifier.
type MockVerifierMockRecorder struct {
	mock *MockVerifier
}

// NewMockVerifier creates a new mock instance.
func NewMockVerifier(ctrl *gomock.Controller) *MockVerifier {
	mock := &MockVerifier{ctrl: ctrl}
	mock.recorder = &MockVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifier) EXPECT() *MockVerifierMockRecorder {
	return m.recorder
}

// CreationOptions mocks base method.
func (m *MockVerifier) CreationOptions(ctx context.Context, in passkey.CreationInput) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreationOptions", ctx, in)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreationOptions indicates an expected call of CreationOptions.
func (mr *MockVerifierMockRecorder) CreationOptions(ctx, in any) *MockVerifierCreationOptionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreationOptions", reflect.TypeOf((*MockVerifier)(nil).CreationOptions), ctx, in)
	return &MockVerifierCreationOptionsCall{Call: call}
}

// MockVerifierCreationOptionsCall wrap *gomock.Call
type MockVerifierCreationOptionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVerifierCreationOptionsCall) Return(arg0 json.RawMessage, arg1 error) *MockVerifierCreationOptionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVerifierCreationOptionsCall) Do(f func(context.Context, passkey.CreationInput) (json.RawMessage, error)) *MockVerifierCreationOptionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVerifierCreationOptionsCall) DoAndReturn(f func(context.Context, passkey.CreationInput) (json.RawMessage, error)) *MockVerifierCreationOptionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ParseAssertion mocks base method.
func (m *MockVerifier) ParseAssertion(body []byte) (passkey.ParsedAssertion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAssertion", body)
	ret0, _ := ret[0].(passkey.ParsedAssertion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAssertion indicates an expected call of ParseAssertion.
func (mr *MockVerifierMockRecorder) ParseAssertion(body any) *MockVerifierParseAssertionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAssertion", reflect.TypeOf((*MockVerifier)(nil).ParseAssertion), body)
	return &MockVerifierParseAssertionCall{Call: call}
}

// MockVerifierParseAssertionCall wrap *gomock.Call
type MockVerifierParseAssertionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVerifierParseAssertionCall) Return(arg0 passkey.ParsedAssertion, arg1 error) *MockVerifierParseAssertionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVerifierParseAssertionCall) Do(f func([]byte) (passkey.ParsedAssertion, error)) *MockVerifierParseAssertionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVerifierParseAssertionCall) DoAndReturn(f func([]byte) (passkey.ParsedAssertion, error)) *MockVerifierParseAssertionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ParseRegistration mocks base method.
func (m *MockVerifier) ParseRegistration(body []byte) (passkey.ParsedRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRegistration", body)
	ret0, _ := ret[0].(passkey.ParsedRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseRegistration indicates an expected call of ParseRegistration.
func (mr *MockVerifierMockRecorder) ParseRegistration(body any) *MockVerifierParseRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRegistration", reflect.TypeOf((*MockVerifier)(nil).ParseRegistration), body)
	return &MockVerifierParseRegistrationCall{Call: call}
}

// MockVerifierParseRegistrationCall wrap *gomock.Call
type MockVerifierParseRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVerifierParseRegistrationCall) Return(arg0 passkey.ParsedRegistration, arg1 error) *MockVerifierParseRegistrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVerifierParseRegistrationCall) Do(f func([]byte) (passkey.ParsedRegistration, error)) *MockVerifierParseRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVerifierParseRegistrationCall) DoAndReturn(f func([]byte) (passkey.ParsedRegistration, error)) *MockVerifierParseRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RelyingParty mocks base method.
func (m *MockVerifier) RelyingParty() passkey.RelyingParty {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelyingParty")
	ret0, _ := ret[0].(passkey.RelyingParty)
	return ret0
}

// RelyingParty indicates an expected call of RelyingParty.
func (mr *MockVerifierMockRecorder) RelyingParty() *MockVerifierRelyingPartyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelyingParty", reflect.TypeOf((*MockVerifier)(nil).RelyingParty))
	return &MockVerifierRelyingPartyCall{Call: call}
}

// MockVerifierRelyingPartyCall wrap *gomock.Call
type MockVerifierRelyingPartyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVerifierRelyingPartyCall) Return(arg0 passkey.RelyingParty) *MockVerifierRelyingPartyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVerifierRelyingPartyCall) Do(f func() passkey.RelyingParty) *MockVerifierRelyingPartyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVerifierRelyingPartyCall) DoAndReturn(f func() passkey.RelyingParty) *MockVerifierRelyingPartyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RequestOptions mocks base method.
func (m *MockVerifier) RequestOptions(ctx context.Context, in passkey.RequestInput) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestOptions", ctx, in)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestOptions indicates an expected call of RequestOptions.
func (mr *MockVerifierMockRecorder) RequestOptions(ctx, in any) *MockVerifierRequestOptionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestOptions", reflect.TypeOf((*MockVerifier)(nil).RequestOptions), ctx, in)
	return &MockVerifierRequestOptionsCall{Call: call}
}

// MockVerifierRequestOptionsCall wrap *gomock.Call
type MockVerifierRequestOptionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVerifierRequestOptionsCall) Return(arg0 json.RawMessage, arg1 error) *MockVerifierRequestOptionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVerifierRequestOptionsCall) Do(f func(context.Context, passkey.RequestInput) (json.RawMessage, error)) *MockVerifierRequestOptionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVerifierRequestOptionsCall) DoAndReturn(f func(context.Context, passkey.RequestInput) (json.RawMessage, error)) *MockVerifierRequestOptionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VerifyAssertion mocks base method.
func (m *MockVerifier) VerifyAssertion(ctx context.Context, p passkey.ParsedAssertion, c *passkey.Credential, exp passkey.AssertionExpectation) (*passkey.AssertionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAssertion", ctx, p, c, exp)
	ret0, _ := ret[0].(*passkey.AssertionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAssertion indicates an expected call of VerifyAssertion.
func (mr *MockVerifierMockRecorder) VerifyAssertion(ctx, p, c, exp any) *MockVerifierVerifyAssertionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAssertion", reflect.TypeOf((*MockVerifier)(nil).VerifyAssertion), ctx, p, c, exp)
	return &MockVerifierVerifyAssertionCall{Call: call}
}

// MockVerifierVerifyAssertionCall wrap *gomock.Call
type MockVerifierVerifyAssertionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *MockVerifierVerifyAssertionCall) Return(arg0 *passkey.AssertionResult, arg1 error) *MockVerifierVerifyAssertionCall {
	c_2.Call = c_2.Call.Return(arg0, arg1)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *MockVerifierVerifyAssertionCall) Do(f func(context.Context, passkey.ParsedAssertion, *passkey.Credential, passkey.AssertionExpectation) (*passkey.AssertionResult, error)) *MockVerifierVerifyAssertionCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *MockVerifierVerifyAssertionCall) DoAndReturn(f func(context.Context, passkey.ParsedAssertion, *passkey.Credential, passkey.AssertionExpectation) (*passkey.AssertionResult, error)) *MockVerifierVerifyAssertionCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// VerifyRegistration mocks base method.
func (m *MockVerifier) VerifyRegistration(ctx context.Context, p passkey.ParsedRegistration, exp passkey.RegistrationExpectation) (*passkey.NewCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRegistration", ctx, p, exp)
	ret0, _ := ret[0].(*passkey.NewCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRegistration indicates an expected call of VerifyRegistration.
func (mr *MockVerifierMockRecorder) VerifyRegistration(ctx, p, exp any) *MockVerifierVerifyRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRegistration", reflect.TypeOf((*MockVerifier)(nil).VerifyRegistration), ctx, p, exp)
	return &MockVerifierVerifyRegistrationCall{Call: call}
}

// MockVerifierVerifyRegistrationCall wrap *gomock.Call
type MockVerifierVerifyRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVerifierVerifyRegistrationCall) Return(arg0 *passkey.NewCredential, arg1 error) *MockVerifierVerifyRegistrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVerifierVerifyRegistrationCall) Do(f func(context.Context, passkey.ParsedRegistration, passkey.RegistrationExpectation) (*passkey.NewCredential, error)) *MockVerifierVerifyRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVerifierVerifyRegistrationCall) DoAndReturn(f func(context.Context, passkey.ParsedRegistration, passkey.RegistrationExpectation) (*passkey.NewCredential, error)) *MockVerifierVerifyRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockParsedRegistration is a mock of ParsedRegistration interface.
type MockParsedRegistration struct {
	ctrl     *gomock.Controller
	recorder *MockParsedRegistrationMockRecorder
	isgomock struct{}
}

// MockParsedRegistrationMockRecorder is the mock recorder for MockParsedRegistration.
type MockParsedRegistrationMockRecorder struct {
	mock *MockParsedRegistration
}

// NewMockParsedRegistration creates a new mock instance.
func NewMockParsedRegistration(ctrl *gomock.Controller) *MockParsedRegistration {
	mock := &MockParsedRegistration{ctrl: ctrl}
	mock.recorder = &MockParsedRegistrationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParsedRegistration) EXPECT() *MockParsedRegistrationMockRecorder {
	return m.recorder
}

// Challenge mocks base method.
func (m *MockParsedRegistration) Challenge() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Challenge")
	ret0, _ := ret[0].(string)
	return ret0
}

// Challenge indicates an expected call of Challenge.
func (mr *MockParsedRegistrationMockRecorder) Challenge() *MockParsedRegistrationChallengeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Challenge", reflect.TypeOf((*MockParsedRegistration)(nil).Challenge))
	return &MockParsedRegistrationChallengeCall{Call: call}
}

// MockParsedRegistrationChallengeCall wrap *gomock.Call
type MockParsedRegistrationChallengeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParsedRegistrationChallengeCall) Return(arg0 string) *MockParsedRegistrationChallengeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParsedRegistrationChallengeCall) Do(f func() string) *MockParsedRegistrationChallengeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParsedRegistrationChallengeCall) DoAndReturn(f func() string) *MockParsedRegistrationChallengeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CredentialID mocks base method.
func (m *MockParsedRegistration) CredentialID() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CredentialID")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// CredentialID indicates an expected call of CredentialID.
func (mr *MockParsedRegistrationMockRecorder) CredentialID() *MockParsedRegistrationCredentialIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CredentialID", reflect.TypeOf((*MockParsedRegistration)(nil).CredentialID))
	return &MockParsedRegistrationCredentialIDCall{Call: call}
}

// MockParsedRegistrationCredentialIDCall wrap *gomock.Call
type MockParsedRegistrationCredentialIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParsedRegistrationCredentialIDCall) Return(arg0 []byte) *MockParsedRegistrationCredentialIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParsedRegistrationCredentialIDCall) Do(f func() []byte) *MockParsedRegistrationCredentialIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParsedRegistrationCredentialIDCall) DoAndReturn(f func() []byte) *MockParsedRegistrationCredentialIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockParsedRegistration) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockParsedRegistrationMockRecorder) Name() *MockParsedRegistrationNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockParsedRegistration)(nil).Name))
	return &MockParsedRegistrationNameCall{Call: call}
}

// MockParsedRegistrationNameCall wrap *gomock.Call
type MockParsedRegistrationNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParsedRegistrationNameCall) Return(arg0 string) *MockParsedRegistrationNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParsedRegistrationNameCall) Do(f func() string) *MockParsedRegistrationNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParsedRegistrationNameCall) DoAndReturn(f func() string) *MockParsedRegistrationNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockParsedAssertion is a mock of ParsedAssertion interface.
type MockParsedAssertion struct {
	ctrl     *gomock.Controller
	recorder *MockParsedAssertionMockRecorder
	isgomock struct{}
}

// MockParsedAssertionMockRecorder is the mock recorder for MockParsedAssertion.
type MockParsedAssertionMockRecorder struct {
	mock *MockParsedAssertion
}

// NewMockParsedAssertion creates a new mock instance.
func NewMockParsedAssertion(ctrl *gomock.Controller) *MockParsedAssertion {
	mock := &MockParsedAssertion{ctrl: ctrl}
	mock.recorder = &MockParsedAssertionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParsedAssertion) EXPECT() *MockParsedAssertionMockRecorder {
	return m.recorder
}

// Challenge mocks base method.
func (m *MockParsedAssertion) Challenge() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Challenge")
	ret0, _ := ret[0].(string)
	return ret0
}

// Challenge indicates an expected call of Challenge.
func (mr *MockParsedAssertionMockRecorder) Challenge() *MockParsedAssertionChallengeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Challenge", reflect.TypeOf((*MockParsedAssertion)(nil).Challenge))
	return &MockParsedAssertionChallengeCall{Call: call}
}

// MockParsedAssertionChallengeCall wrap *gomock.Call
type MockParsedAssertionChallengeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParsedAssertionChallengeCall) Return(arg0 string) *MockParsedAssertionChallengeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParsedAssertionChallengeCall) Do(f func() string) *MockParsedAssertionChallengeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParsedAssertionChallengeCall) DoAndReturn(f func() string) *MockParsedAssertionChallengeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CredentialID mocks base method.
func (m *MockParsedAssertion) CredentialID() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CredentialID")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// CredentialID indicates an expected call of CredentialID.
func (mr *MockParsedAssertionMockRecorder) CredentialID() *MockParsedAssertionCredentialIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CredentialID", reflect.TypeOf((*MockParsedAssertion)(nil).CredentialID))
	return &MockParsedAssertionCredentialIDCall{Call: call}
}

// MockParsedAssertionCredentialIDCall wrap *gomock.Call
type MockParsedAssertionCredentialIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParsedAssertionCredentialIDCall) Return(arg0 []byte) *MockParsedAssertionCredentialIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParsedAssertionCredentialIDCall) Do(f func() []byte) *MockParsedAssertionCredentialIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParsedAssertionCredentialIDCall) DoAndReturn(f func() []byte) *MockParsedAssertionCredentialIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UserHandle mocks base method.
func (m *MockParsedAssertion) UserHandle() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserHandle")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// UserHandle indicates an expected call of UserHandle.
func (mr *MockParsedAssertionMockRecorder) UserHandle() *MockParsedAssertionUserHandleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserHandle", reflect.TypeOf((*MockParsedAssertion)(nil).UserHandle))
	return &MockParsedAssertionUserHandleCall{Call: call}
}

// MockParsedAssertionUserHandleCall wrap *gomock.Call
type MockParsedAssertionUserHandleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParsedAssertionUserHandleCall) Return(arg0 []byte) *MockParsedAssertionUserHandleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParsedAssertionUserHandleCall) Do(f func() []byte) *MockParsedAssertionUserHandleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParsedAssertionUserHandleCall) DoAndReturn(f func() []byte) *MockParsedAssertionUserHandleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
