// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/policy (interfaces: AttemptStore)
//
// Generated by this command:
//
//	mockgen -destination=attemptstore_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/policy AttemptStore
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAttemptStore is a mock of AttemptStore interface.
type MockAttemptStore struct {
	ctrl     *gomock.Controller
	recorder *MockAttemptStoreMockRecorder
	isgomock struct{}
}

// MockAttemptStoreMockRecorder is the mock recorder for MockAttemptStore.
type MockAttemptStoreMockRecorder struct {
	mock *MockAttemptStore
}

// NewMockAttemptStore creates a new mock instance.
func NewMockAttemptStore(ctrl *gomock.Controller) *MockAttemptStore {
	mock := &MockAttemptStore{ctrl: ctrl}
	mock.recorder = &MockAttemptStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttemptStore) EXPECT() *MockAttemptStoreMockRecorder {
	return m.recorder
}

// FailureCount mocks base method.
func (m *MockAttemptStore) FailureCount(ctx context.Context, username string, since time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailureCount", ctx, username, since)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FailureCount indicates an expected call of FailureCount.
func (mr *MockAttemptStoreMockRecorder) FailureCount(ctx, username, since any) *MockAttemptStoreFailureCountCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailureCount", reflect.TypeOf((*MockAttemptStore)(nil).FailureCount), ctx, username, since)
	return &MockAttemptStoreFailureCountCall{Call: call}
}

// MockAttemptStoreFailureCountCall wrap *gomock.Call
type MockAttemptStoreFailureCountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAttemptStoreFailureCountCall) Return(arg0 int, arg1 error) *MockAttemptStoreFailureCountCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAttemptStoreFailureCountCall) Do(f func(context.Context, string, time.Time) (int, error)) *MockAttemptStoreFailureCountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAttemptStoreFailureCountCall) DoAndReturn(f func(context.Context, string, time.Time) (int, error)) *MockAttemptStoreFailureCountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RecordFailure mocks base method.
func (m *MockAttemptStore) RecordFailure(ctx context.Context, username string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordFailure", ctx, username, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordFailure indicates an expected call of RecordFailure.
func (mr *MockAttemptStoreMockRecorder) RecordFailure(ctx, username, at any) *MockAttemptStoreRecordFailureCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFailure", reflect.TypeOf((*MockAttemptStore)(nil).RecordFailure), ctx, username, at)
	return &MockAttemptStoreRecordFailureCall{Call: call}
}

// MockAttemptStoreRecordFailureCall wrap *gomock.Call
type MockAttemptStoreRecordFailureCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAttemptStoreRecordFailureCall) Return(arg0 error) *MockAttemptStoreRecordFailureCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAttemptStoreRecordFailureCall) Do(f func(context.Context, string, time.Time) error) *MockAttemptStoreRecordFailureCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAttemptStoreRecordFailureCall) DoAndReturn(f func(context.Context, string, time.Time) error) *MockAttemptStoreRecordFailureCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Reset mocks base method.
func (m *MockAttemptStore) Reset(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockAttemptStoreMockRecorder) Reset(ctx, username any) *MockAttemptStoreResetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockAttemptStore)(nil).Reset), ctx, username)
	return &MockAttemptStoreResetCall{Call: call}
}

// MockAttemptStoreResetCall wrap *gomock.Call
type MockAttemptStoreResetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAttemptStoreResetCall) Return(arg0 error) *MockAttemptStoreResetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAttemptStoreResetCall) Do(f func(context.Context, string) error) *MockAttemptStoreResetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAttemptStoreResetCall) DoAndReturn(f func(context.Context, string) error) *MockAttemptStoreResetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
