// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/authenticate (interfaces: Authenticator)
//
// Generated by this command:
//
//	mockgen -destination=authenticator_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/authenticate Authenticator
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"

	authenticate "github.com/kartaladev/scrty/authenticate"
	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticator is a mock of Authenticator interface.
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
	isgomock struct{}
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator.
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance.
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockAuthenticator) Authenticate(ctx context.Context, c identity.Credentials) (*authenticate.Authentication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, c)
	ret0, _ := ret[0].(*authenticate.Authentication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockAuthenticatorMockRecorder) Authenticate(ctx, c any) *MockAuthenticatorAuthenticateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuthenticator)(nil).Authenticate), ctx, c)
	return &MockAuthenticatorAuthenticateCall{Call: call}
}

// MockAuthenticatorAuthenticateCall wrap *gomock.Call
type MockAuthenticatorAuthenticateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *MockAuthenticatorAuthenticateCall) Return(arg0 *authenticate.Authentication, arg1 error) *MockAuthenticatorAuthenticateCall {
	c_2.Call = c_2.Call.Return(arg0, arg1)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *MockAuthenticatorAuthenticateCall) Do(f func(context.Context, identity.Credentials) (*authenticate.Authentication, error)) *MockAuthenticatorAuthenticateCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *MockAuthenticatorAuthenticateCall) DoAndReturn(f func(context.Context, identity.Credentials) (*authenticate.Authentication, error)) *MockAuthenticatorAuthenticateCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}
