// Code generated by MockGen. DO NOT EDIT.
// Source: lockout_unknown_test.go
//
// Generated by this command:
//
//	mockgen -source=lockout_unknown_test.go -package=httpsec_test -destination=decoyauthenticator_mock_test.go -typed -mock_names=DecoyAuthenticator=MockDecoyAuthenticator
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"

	authenticate "github.com/kartaladev/scrty/authenticate"
	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockDecoyAuthenticator is a mock of DecoyAuthenticator interface.
type MockDecoyAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockDecoyAuthenticatorMockRecorder
	isgomock struct{}
}

// MockDecoyAuthenticatorMockRecorder is the mock recorder for MockDecoyAuthenticator.
type MockDecoyAuthenticatorMockRecorder struct {
	mock *MockDecoyAuthenticator
}

// NewMockDecoyAuthenticator creates a new mock instance.
func NewMockDecoyAuthenticator(ctrl *gomock.Controller) *MockDecoyAuthenticator {
	mock := &MockDecoyAuthenticator{ctrl: ctrl}
	mock.recorder = &MockDecoyAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecoyAuthenticator) EXPECT() *MockDecoyAuthenticatorMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockDecoyAuthenticator) Authenticate(ctx context.Context, c identity.Credentials) (*authenticate.Authentication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, c)
	ret0, _ := ret[0].(*authenticate.Authentication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockDecoyAuthenticatorMockRecorder) Authenticate(ctx, c any) *MockDecoyAuthenticatorAuthenticateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockDecoyAuthenticator)(nil).Authenticate), ctx, c)
	return &MockDecoyAuthenticatorAuthenticateCall{Call: call}
}

// MockDecoyAuthenticatorAuthenticateCall wrap *gomock.Call
type MockDecoyAuthenticatorAuthenticateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *MockDecoyAuthenticatorAuthenticateCall) Return(arg0 *authenticate.Authentication, arg1 error) *MockDecoyAuthenticatorAuthenticateCall {
	c_2.Call = c_2.Call.Return(arg0, arg1)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *MockDecoyAuthenticatorAuthenticateCall) Do(f func(context.Context, identity.Credentials) (*authenticate.Authentication, error)) *MockDecoyAuthenticatorAuthenticateCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *MockDecoyAuthenticatorAuthenticateCall) DoAndReturn(f func(context.Context, identity.Credentials) (*authenticate.Authentication, error)) *MockDecoyAuthenticatorAuthenticateCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// VerifyDecoy mocks base method.
func (m *MockDecoyAuthenticator) VerifyDecoy(ctx context.Context, creds identity.Credentials) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyDecoy", ctx, creds)
	ret0, _ := ret[0].(bool)
	return ret0
}

// VerifyDecoy indicates an expected call of VerifyDecoy.
func (mr *MockDecoyAuthenticatorMockRecorder) VerifyDecoy(ctx, creds any) *MockDecoyAuthenticatorVerifyDecoyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyDecoy", reflect.TypeOf((*MockDecoyAuthenticator)(nil).VerifyDecoy), ctx, creds)
	return &MockDecoyAuthenticatorVerifyDecoyCall{Call: call}
}

// MockDecoyAuthenticatorVerifyDecoyCall wrap *gomock.Call
type MockDecoyAuthenticatorVerifyDecoyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDecoyAuthenticatorVerifyDecoyCall) Return(handled bool) *MockDecoyAuthenticatorVerifyDecoyCall {
	c.Call = c.Call.Return(handled)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDecoyAuthenticatorVerifyDecoyCall) Do(f func(context.Context, identity.Credentials) bool) *MockDecoyAuthenticatorVerifyDecoyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDecoyAuthenticatorVerifyDecoyCall) DoAndReturn(f func(context.Context, identity.Credentials) bool) *MockDecoyAuthenticatorVerifyDecoyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
