// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/password (interfaces: Encoder)
//
// Generated by this command:
//
//	mockgen -destination=encoder_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/password Encoder
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEncoder is a mock of Encoder interface.
type MockEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockEncoderMockRecorder
	isgomock struct{}
}

// MockEncoderMockRecorder is the mock recorder for MockEncoder.
type MockEncoderMockRecorder struct {
	mock *MockEncoder
}

// NewMockEncoder creates a new mock instance.
func NewMockEncoder(ctrl *gomock.Controller) *MockEncoder {
	mock := &MockEncoder{ctrl: ctrl}
	mock.recorder = &MockEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncoder) EXPECT() *MockEncoderMockRecorder {
	return m.recorder
}

// Encode mocks base method.
func (m *MockEncoder) Encode(input string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockEncoderMockRecorder) Encode(input any) *MockEncoderEncodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockEncoder)(nil).Encode), input)
	return &MockEncoderEncodeCall{Call: call}
}

// MockEncoderEncodeCall wrap *gomock.Call
type MockEncoderEncodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEncoderEncodeCall) Return(arg0 []byte, arg1 error) *MockEncoderEncodeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEncoderEncodeCall) Do(f func(string) ([]byte, error)) *MockEncoderEncodeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEncoderEncodeCall) DoAndReturn(f func(string) ([]byte, error)) *MockEncoderEncodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Match mocks base method.
func (m *MockEncoder) Match(input string, encoded []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Match", input, encoded)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Match indicates an expected call of Match.
func (mr *MockEncoderMockRecorder) Match(input, encoded any) *MockEncoderMatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockEncoder)(nil).Match), input, encoded)
	return &MockEncoderMatchCall{Call: call}
}

// MockEncoderMatchCall wrap *gomock.Call
type MockEncoderMatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEncoderMatchCall) Return(arg0 bool) *MockEncoderMatchCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEncoderMatchCall) Do(f func(string, []byte) bool) *MockEncoderMatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEncoderMatchCall) DoAndReturn(f func(string, []byte) bool) *MockEncoderMatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
