// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/httpsec (interfaces: EndSessionBuilder)
//
// Generated by this command:
//
//	mockgen -destination=endsessionbuilder_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/httpsec EndSessionBuilder
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"

	session "github.com/kartaladev/scrty/session"
	gomock "go.uber.org/mock/gomock"
)

// MockEndSessionBuilder is a mock of EndSessionBuilder interface.
type MockEndSessionBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockEndSessionBuilderMockRecorder
	isgomock struct{}
}

// MockEndSessionBuilderMockRecorder is the mock recorder for MockEndSessionBuilder.
type MockEndSessionBuilderMockRecorder struct {
	mock *MockEndSessionBuilder
}

// NewMockEndSessionBuilder creates a new mock instance.
func NewMockEndSessionBuilder(ctrl *gomock.Controller) *MockEndSessionBuilder {
	mock := &MockEndSessionBuilder{ctrl: ctrl}
	mock.recorder = &MockEndSessionBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndSessionBuilder) EXPECT() *MockEndSessionBuilderMockRecorder {
	return m.recorder
}

// EndSessionURL mocks base method.
func (m *MockEndSessionBuilder) EndSessionURL(ctx context.Context, s *session.Session, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndSessionURL", ctx, s, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndSessionURL indicates an expected call of EndSessionURL.
func (mr *MockEndSessionBuilderMockRecorder) EndSessionURL(ctx, s, state any) *MockEndSessionBuilderEndSessionURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndSessionURL", reflect.TypeOf((*MockEndSessionBuilder)(nil).EndSessionURL), ctx, s, state)
	return &MockEndSessionBuilderEndSessionURLCall{Call: call}
}

// MockEndSessionBuilderEndSessionURLCall wrap *gomock.Call
type MockEndSessionBuilderEndSessionURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEndSessionBuilderEndSessionURLCall) Return(arg0 string, arg1 error) *MockEndSessionBuilderEndSessionURLCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEndSessionBuilderEndSessionURLCall) Do(f func(context.Context, *session.Session, string) (string, error)) *MockEndSessionBuilderEndSessionURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEndSessionBuilderEndSessionURLCall) DoAndReturn(f func(context.Context, *session.Session, string) (string, error)) *MockEndSessionBuilderEndSessionURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
