// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/mfa (interfaces: Enroller)
//
// Generated by this command:
//
//	mockgen -destination=enroller_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/mfa Enroller
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"
	time "time"

	factor "github.com/kartaladev/scrty/factor"
	identity "github.com/kartaladev/scrty/identity"
	mfa "github.com/kartaladev/scrty/mfa"
	id "github.com/kartaladev/scrty/pkg/id"
	gomock "go.uber.org/mock/gomock"
)

// MockEnroller is a mock of Enroller interface.
type MockEnroller struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollerMockRecorder
	isgomock struct{}
}

// MockEnrollerMockRecorder is the mock recorder for MockEnroller.
type MockEnrollerMockRecorder struct {
	mock *MockEnroller
}

// NewMockEnroller creates a new mock instance.
func NewMockEnroller(ctrl *gomock.Controller) *MockEnroller {
	mock := &MockEnroller{ctrl: ctrl}
	mock.recorder = &MockEnrollerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnroller) EXPECT() *MockEnrollerMockRecorder {
	return m.recorder
}

// BeginEnrolmentGeneration mocks base method.
func (m *MockEnroller) BeginEnrolmentGeneration(ctx context.Context, user identity.UserID, accountLabel string) (mfa.Provisioning, id.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginEnrolmentGeneration", ctx, user, accountLabel)
	ret0, _ := ret[0].(mfa.Provisioning)
	ret1, _ := ret[1].(id.ID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BeginEnrolmentGeneration indicates an expected call of BeginEnrolmentGeneration.
func (mr *MockEnrollerMockRecorder) BeginEnrolmentGeneration(ctx, user, accountLabel any) *MockEnrollerBeginEnrolmentGenerationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginEnrolmentGeneration", reflect.TypeOf((*MockEnroller)(nil).BeginEnrolmentGeneration), ctx, user, accountLabel)
	return &MockEnrollerBeginEnrolmentGenerationCall{Call: call}
}

// MockEnrollerBeginEnrolmentGenerationCall wrap *gomock.Call
type MockEnrollerBeginEnrolmentGenerationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrollerBeginEnrolmentGenerationCall) Return(arg0 mfa.Provisioning, arg1 id.ID, arg2 error) *MockEnrollerBeginEnrolmentGenerationCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrollerBeginEnrolmentGenerationCall) Do(f func(context.Context, identity.UserID, string) (mfa.Provisioning, id.ID, error)) *MockEnrollerBeginEnrolmentGenerationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrollerBeginEnrolmentGenerationCall) DoAndReturn(f func(context.Context, identity.UserID, string) (mfa.Provisioning, id.ID, error)) *MockEnrollerBeginEnrolmentGenerationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Channel mocks base method.
func (m *MockEnroller) Channel() factor.Channel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Channel")
	ret0, _ := ret[0].(factor.Channel)
	return ret0
}

// Channel indicates an expected call of Channel.
func (mr *MockEnrollerMockRecorder) Channel() *MockEnrollerChannelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Channel", reflect.TypeOf((*MockEnroller)(nil).Channel))
	return &MockEnrollerChannelCall{Call: call}
}

// MockEnrollerChannelCall wrap *gomock.Call
type MockEnrollerChannelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrollerChannelCall) Return(arg0 factor.Channel) *MockEnrollerChannelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrollerChannelCall) Do(f func() factor.Channel) *MockEnrollerChannelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrollerChannelCall) DoAndReturn(f func() factor.Channel) *MockEnrollerChannelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CompleteEnrolment mocks base method.
func (m *MockEnroller) CompleteEnrolment(ctx context.Context, user identity.UserID, gen id.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteEnrolment", ctx, user, gen)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteEnrolment indicates an expected call of CompleteEnrolment.
func (mr *MockEnrollerMockRecorder) CompleteEnrolment(ctx, user, gen any) *MockEnrollerCompleteEnrolmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteEnrolment", reflect.TypeOf((*MockEnroller)(nil).CompleteEnrolment), ctx, user, gen)
	return &MockEnrollerCompleteEnrolmentCall{Call: call}
}

// MockEnrollerCompleteEnrolmentCall wrap *gomock.Call
type MockEnrollerCompleteEnrolmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrollerCompleteEnrolmentCall) Return(arg0 error) *MockEnrollerCompleteEnrolmentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrollerCompleteEnrolmentCall) Do(f func(context.Context, identity.UserID, id.ID) error) *MockEnrollerCompleteEnrolmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrollerCompleteEnrolmentCall) DoAndReturn(f func(context.Context, identity.UserID, id.ID) error) *MockEnrollerCompleteEnrolmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Enrolled mocks base method.
func (m *MockEnroller) Enrolled(ctx context.Context, user identity.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enrolled", ctx, user)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enrolled indicates an expected call of Enrolled.
func (mr *MockEnrollerMockRecorder) Enrolled(ctx, user any) *MockEnrollerEnrolledCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enrolled", reflect.TypeOf((*MockEnroller)(nil).Enrolled), ctx, user)
	return &MockEnrollerEnrolledCall{Call: call}
}

// MockEnrollerEnrolledCall wrap *gomock.Call
type MockEnrollerEnrolledCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrollerEnrolledCall) Return(arg0 bool, arg1 error) *MockEnrollerEnrolledCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrollerEnrolledCall) Do(f func(context.Context, identity.UserID) (bool, error)) *MockEnrollerEnrolledCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrollerEnrolledCall) DoAndReturn(f func(context.Context, identity.UserID) (bool, error)) *MockEnrollerEnrolledCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockEnroller) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockEnrollerMockRecorder) Name() *MockEnrollerNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockEnroller)(nil).Name))
	return &MockEnrollerNameCall{Call: call}
}

// MockEnrollerNameCall wrap *gomock.Call
type MockEnrollerNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrollerNameCall) Return(arg0 string) *MockEnrollerNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrollerNameCall) Do(f func() string) *MockEnrollerNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrollerNameCall) DoAndReturn(f func() string) *MockEnrollerNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ProveDevice mocks base method.
func (m *MockEnroller) ProveDevice(ctx context.Context, user identity.UserID, gen id.ID, code string, emailCode bool, emailCodeTTL time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProveDevice", ctx, user, gen, code, emailCode, emailCodeTTL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProveDevice indicates an expected call of ProveDevice.
func (mr *MockEnrollerMockRecorder) ProveDevice(ctx, user, gen, code, emailCode, emailCodeTTL any) *MockEnrollerProveDeviceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProveDevice", reflect.TypeOf((*MockEnroller)(nil).ProveDevice), ctx, user, gen, code, emailCode, emailCodeTTL)
	return &MockEnrollerProveDeviceCall{Call: call}
}

// MockEnrollerProveDeviceCall wrap *gomock.Call
type MockEnrollerProveDeviceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrollerProveDeviceCall) Return(arg0 string, arg1 error) *MockEnrollerProveDeviceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrollerProveDeviceCall) Do(f func(context.Context, identity.UserID, id.ID, string, bool, time.Duration) (string, error)) *MockEnrollerProveDeviceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrollerProveDeviceCall) DoAndReturn(f func(context.Context, identity.UserID, id.ID, string, bool, time.Duration) (string, error)) *MockEnrollerProveDeviceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RedeemEmailCode mocks base method.
func (m *MockEnroller) RedeemEmailCode(ctx context.Context, user identity.UserID, gen id.ID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedeemEmailCode", ctx, user, gen, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// RedeemEmailCode indicates an expected call of RedeemEmailCode.
func (mr *MockEnrollerMockRecorder) RedeemEmailCode(ctx, user, gen, code any) *MockEnrollerRedeemEmailCodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedeemEmailCode", reflect.TypeOf((*MockEnroller)(nil).RedeemEmailCode), ctx, user, gen, code)
	return &MockEnrollerRedeemEmailCodeCall{Call: call}
}

// MockEnrollerRedeemEmailCodeCall wrap *gomock.Call
type MockEnrollerRedeemEmailCodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrollerRedeemEmailCodeCall) Return(arg0 error) *MockEnrollerRedeemEmailCodeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrollerRedeemEmailCodeCall) Do(f func(context.Context, identity.UserID, id.ID, string) error) *MockEnrollerRedeemEmailCodeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrollerRedeemEmailCodeCall) DoAndReturn(f func(context.Context, identity.UserID, id.ID, string) error) *MockEnrollerRedeemEmailCodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SupportsEnrolmentPath mocks base method.
func (m *MockEnroller) SupportsEnrolmentPath() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsEnrolmentPath")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsEnrolmentPath indicates an expected call of SupportsEnrolmentPath.
func (mr *MockEnrollerMockRecorder) SupportsEnrolmentPath() *MockEnrollerSupportsEnrolmentPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsEnrolmentPath", reflect.TypeOf((*MockEnroller)(nil).SupportsEnrolmentPath))
	return &MockEnrollerSupportsEnrolmentPathCall{Call: call}
}

// MockEnrollerSupportsEnrolmentPathCall wrap *gomock.Call
type MockEnrollerSupportsEnrolmentPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrollerSupportsEnrolmentPathCall) Return(arg0 bool) *MockEnrollerSupportsEnrolmentPathCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrollerSupportsEnrolmentPathCall) Do(f func() bool) *MockEnrollerSupportsEnrolmentPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrollerSupportsEnrolmentPathCall) DoAndReturn(f func() bool) *MockEnrollerSupportsEnrolmentPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Verify mocks base method.
func (m *MockEnroller) Verify(ctx context.Context, user identity.UserID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, user, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockEnrollerMockRecorder) Verify(ctx, user, code any) *MockEnrollerVerifyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockEnroller)(nil).Verify), ctx, user, code)
	return &MockEnrollerVerifyCall{Call: call}
}

// MockEnrollerVerifyCall wrap *gomock.Call
type MockEnrollerVerifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrollerVerifyCall) Return(arg0 error) *MockEnrollerVerifyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrollerVerifyCall) Do(f func(context.Context, identity.UserID, string) error) *MockEnrollerVerifyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrollerVerifyCall) DoAndReturn(f func(context.Context, identity.UserID, string) error) *MockEnrollerVerifyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
