// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/policy (interfaces: FederatedAssuranceSource)
//
// Generated by this command:
//
//	mockgen -destination=federatedassurancesource_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/policy FederatedAssuranceSource
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	policy "github.com/kartaladev/scrty/policy"
	gomock "go.uber.org/mock/gomock"
)

// MockFederatedAssuranceSource is a mock of FederatedAssuranceSource interface.
type MockFederatedAssuranceSource struct {
	ctrl     *gomock.Controller
	recorder *MockFederatedAssuranceSourceMockRecorder
	isgomock struct{}
}

// MockFederatedAssuranceSourceMockRecorder is the mock recorder for MockFederatedAssuranceSource.
type MockFederatedAssuranceSourceMockRecorder struct {
	mock *MockFederatedAssuranceSource
}

// NewMockFederatedAssuranceSource creates a new mock instance.
func NewMockFederatedAssuranceSource(ctrl *gomock.Controller) *MockFederatedAssuranceSource {
	mock := &MockFederatedAssuranceSource{ctrl: ctrl}
	mock.recorder = &MockFederatedAssuranceSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFederatedAssuranceSource) EXPECT() *MockFederatedAssuranceSourceMockRecorder {
	return m.recorder
}

// MeetsAssurance mocks base method.
func (m *MockFederatedAssuranceSource) MeetsAssurance(ctx context.Context, user identity.UserID, ev policy.FederatedAssurance) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeetsAssurance", ctx, user, ev)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MeetsAssurance indicates an expected call of MeetsAssurance.
func (mr *MockFederatedAssuranceSourceMockRecorder) MeetsAssurance(ctx, user, ev any) *MockFederatedAssuranceSourceMeetsAssuranceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeetsAssurance", reflect.TypeOf((*MockFederatedAssuranceSource)(nil).MeetsAssurance), ctx, user, ev)
	return &MockFederatedAssuranceSourceMeetsAssuranceCall{Call: call}
}

// MockFederatedAssuranceSourceMeetsAssuranceCall wrap *gomock.Call
type MockFederatedAssuranceSourceMeetsAssuranceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFederatedAssuranceSourceMeetsAssuranceCall) Return(arg0 bool, arg1 error) *MockFederatedAssuranceSourceMeetsAssuranceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFederatedAssuranceSourceMeetsAssuranceCall) Do(f func(context.Context, identity.UserID, policy.FederatedAssurance) (bool, error)) *MockFederatedAssuranceSourceMeetsAssuranceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFederatedAssuranceSourceMeetsAssuranceCall) DoAndReturn(f func(context.Context, identity.UserID, policy.FederatedAssurance) (bool, error)) *MockFederatedAssuranceSourceMeetsAssuranceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
