// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/oidc (interfaces: FlowStore)
//
// Generated by this command:
//
//	mockgen -destination=flowstore_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/oidc FlowStore
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"
	time "time"

	oidc "github.com/kartaladev/scrty/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockFlowStore is a mock of FlowStore interface.
type MockFlowStore struct {
	ctrl     *gomock.Controller
	recorder *MockFlowStoreMockRecorder
	isgomock struct{}
}

// MockFlowStoreMockRecorder is the mock recorder for MockFlowStore.
type MockFlowStoreMockRecorder struct {
	mock *MockFlowStore
}

// NewMockFlowStore creates a new mock instance.
func NewMockFlowStore(ctrl *gomock.Controller) *MockFlowStore {
	mock := &MockFlowStore{ctrl: ctrl}
	mock.recorder = &MockFlowStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowStore) EXPECT() *MockFlowStoreMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockFlowStore) Begin(ctx context.Context, f oidc.Flow) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx, f)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockFlowStoreMockRecorder) Begin(ctx, f any) *MockFlowStoreBeginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockFlowStore)(nil).Begin), ctx, f)
	return &MockFlowStoreBeginCall{Call: call}
}

// MockFlowStoreBeginCall wrap *gomock.Call
type MockFlowStoreBeginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowStoreBeginCall) Return(handle string, err error) *MockFlowStoreBeginCall {
	c.Call = c.Call.Return(handle, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowStoreBeginCall) Do(f func(context.Context, oidc.Flow) (string, error)) *MockFlowStoreBeginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowStoreBeginCall) DoAndReturn(f func(context.Context, oidc.Flow) (string, error)) *MockFlowStoreBeginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Complete mocks base method.
func (m *MockFlowStore) Complete(ctx context.Context, handle, provider, state string) (oidc.Flow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, handle, provider, state)
	ret0, _ := ret[0].(oidc.Flow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockFlowStoreMockRecorder) Complete(ctx, handle, provider, state any) *MockFlowStoreCompleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockFlowStore)(nil).Complete), ctx, handle, provider, state)
	return &MockFlowStoreCompleteCall{Call: call}
}

// MockFlowStoreCompleteCall wrap *gomock.Call
type MockFlowStoreCompleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowStoreCompleteCall) Return(arg0 oidc.Flow, arg1 error) *MockFlowStoreCompleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowStoreCompleteCall) Do(f func(context.Context, string, string, string) (oidc.Flow, error)) *MockFlowStoreCompleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowStoreCompleteCall) DoAndReturn(f func(context.Context, string, string, string) (oidc.Flow, error)) *MockFlowStoreCompleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteExpired mocks base method.
func (m *MockFlowStore) DeleteExpired(ctx context.Context, before time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx, before)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockFlowStoreMockRecorder) DeleteExpired(ctx, before any) *MockFlowStoreDeleteExpiredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockFlowStore)(nil).DeleteExpired), ctx, before)
	return &MockFlowStoreDeleteExpiredCall{Call: call}
}

// MockFlowStoreDeleteExpiredCall wrap *gomock.Call
type MockFlowStoreDeleteExpiredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowStoreDeleteExpiredCall) Return(arg0 int, arg1 error) *MockFlowStoreDeleteExpiredCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowStoreDeleteExpiredCall) Do(f func(context.Context, time.Time) (int, error)) *MockFlowStoreDeleteExpiredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowStoreDeleteExpiredCall) DoAndReturn(f func(context.Context, time.Time) (int, error)) *MockFlowStoreDeleteExpiredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
