// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/httpsec (interfaces: HandoffRedeemer)
//
// Generated by this command:
//
//	mockgen -destination=handoffredeemer_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/httpsec HandoffRedeemer
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"

	oidc "github.com/kartaladev/scrty/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockHandoffRedeemer is a mock of HandoffRedeemer interface.
type MockHandoffRedeemer struct {
	ctrl     *gomock.Controller
	recorder *MockHandoffRedeemerMockRecorder
	isgomock struct{}
}

// MockHandoffRedeemerMockRecorder is the mock recorder for MockHandoffRedeemer.
type MockHandoffRedeemerMockRecorder struct {
	mock *MockHandoffRedeemer
}

// NewMockHandoffRedeemer creates a new mock instance.
func NewMockHandoffRedeemer(ctrl *gomock.Controller) *MockHandoffRedeemer {
	mock := &MockHandoffRedeemer{ctrl: ctrl}
	mock.recorder = &MockHandoffRedeemerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandoffRedeemer) EXPECT() *MockHandoffRedeemerMockRecorder {
	return m.recorder
}

// Redeem mocks base method.
func (m *MockHandoffRedeemer) Redeem(ctx context.Context, code string, checks ...oidc.RedeemCheck) (oidc.HandoffResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, code}
	for _, a := range checks {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Redeem", varargs...)
	ret0, _ := ret[0].(oidc.HandoffResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Redeem indicates an expected call of Redeem.
func (mr *MockHandoffRedeemerMockRecorder) Redeem(ctx, code any, checks ...any) *MockHandoffRedeemerRedeemCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, code}, checks...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redeem", reflect.TypeOf((*MockHandoffRedeemer)(nil).Redeem), varargs...)
	return &MockHandoffRedeemerRedeemCall{Call: call}
}

// MockHandoffRedeemerRedeemCall wrap *gomock.Call
type MockHandoffRedeemerRedeemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandoffRedeemerRedeemCall) Return(arg0 oidc.HandoffResult, arg1 error) *MockHandoffRedeemerRedeemCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandoffRedeemerRedeemCall) Do(f func(context.Context, string, ...oidc.RedeemCheck) (oidc.HandoffResult, error)) *MockHandoffRedeemerRedeemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandoffRedeemerRedeemCall) DoAndReturn(f func(context.Context, string, ...oidc.RedeemCheck) (oidc.HandoffResult, error)) *MockHandoffRedeemerRedeemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
