// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/oidc (interfaces: IdentityBroker)
//
// Generated by this command:
//
//	mockgen -destination=identitybroker_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/oidc IdentityBroker
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	oidc "github.com/kartaladev/scrty/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockIdentityBroker is a mock of IdentityBroker interface.
type MockIdentityBroker struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityBrokerMockRecorder
	isgomock struct{}
}

// MockIdentityBrokerMockRecorder is the mock recorder for MockIdentityBroker.
type MockIdentityBrokerMockRecorder struct {
	mock *MockIdentityBroker
}

// NewMockIdentityBroker creates a new mock instance.
func NewMockIdentityBroker(ctrl *gomock.Controller) *MockIdentityBroker {
	mock := &MockIdentityBroker{ctrl: ctrl}
	mock.recorder = &MockIdentityBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityBroker) EXPECT() *MockIdentityBrokerMockRecorder {
	return m.recorder
}

// Broker mocks base method.
func (m *MockIdentityBroker) Broker(ctx context.Context, ext oidc.ExternalIdentity) (*identity.Principal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Broker", ctx, ext)
	ret0, _ := ret[0].(*identity.Principal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Broker indicates an expected call of Broker.
func (mr *MockIdentityBrokerMockRecorder) Broker(ctx, ext any) *MockIdentityBrokerBrokerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broker", reflect.TypeOf((*MockIdentityBroker)(nil).Broker), ctx, ext)
	return &MockIdentityBrokerBrokerCall{Call: call}
}

// MockIdentityBrokerBrokerCall wrap *gomock.Call
type MockIdentityBrokerBrokerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIdentityBrokerBrokerCall) Return(arg0 *identity.Principal, arg1 error) *MockIdentityBrokerBrokerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIdentityBrokerBrokerCall) Do(f func(context.Context, oidc.ExternalIdentity) (*identity.Principal, error)) *MockIdentityBrokerBrokerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIdentityBrokerBrokerCall) DoAndReturn(f func(context.Context, oidc.ExternalIdentity) (*identity.Principal, error)) *MockIdentityBrokerBrokerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
