// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/httpsec (interfaces: KeySetProvider)
//
// Generated by this command:
//
//	mockgen -destination=keysetprovider_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/httpsec KeySetProvider
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKeySetProvider is a mock of KeySetProvider interface.
type MockKeySetProvider struct {
	ctrl     *gomock.Controller
	recorder *MockKeySetProviderMockRecorder
	isgomock struct{}
}

// MockKeySetProviderMockRecorder is the mock recorder for MockKeySetProvider.
type MockKeySetProviderMockRecorder struct {
	mock *MockKeySetProvider
}

// NewMockKeySetProvider creates a new mock instance.
func NewMockKeySetProvider(ctrl *gomock.Controller) *MockKeySetProvider {
	mock := &MockKeySetProvider{ctrl: ctrl}
	mock.recorder = &MockKeySetProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeySetProvider) EXPECT() *MockKeySetProviderMockRecorder {
	return m.recorder
}

// JWKS mocks base method.
func (m *MockKeySetProvider) JWKS() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JWKS")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JWKS indicates an expected call of JWKS.
func (mr *MockKeySetProviderMockRecorder) JWKS() *MockKeySetProviderJWKSCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JWKS", reflect.TypeOf((*MockKeySetProvider)(nil).JWKS))
	return &MockKeySetProviderJWKSCall{Call: call}
}

// MockKeySetProviderJWKSCall wrap *gomock.Call
type MockKeySetProviderJWKSCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeySetProviderJWKSCall) Return(arg0 []byte, arg1 error) *MockKeySetProviderJWKSCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeySetProviderJWKSCall) Do(f func() ([]byte, error)) *MockKeySetProviderJWKSCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeySetProviderJWKSCall) DoAndReturn(f func() ([]byte, error)) *MockKeySetProviderJWKSCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
