// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/oidc (interfaces: LinkStore)
//
// Generated by this command:
//
//	mockgen -destination=linkstore_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/oidc LinkStore
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	oidc "github.com/kartaladev/scrty/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockLinkStore is a mock of LinkStore interface.
type MockLinkStore struct {
	ctrl     *gomock.Controller
	recorder *MockLinkStoreMockRecorder
	isgomock struct{}
}

// MockLinkStoreMockRecorder is the mock recorder for MockLinkStore.
type MockLinkStoreMockRecorder struct {
	mock *MockLinkStore
}

// NewMockLinkStore creates a new mock instance.
func NewMockLinkStore(ctrl *gomock.Controller) *MockLinkStore {
	mock := &MockLinkStore{ctrl: ctrl}
	mock.recorder = &MockLinkStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkStore) EXPECT() *MockLinkStoreMockRecorder {
	return m.recorder
}

// DeleteByUser mocks base method.
func (m *MockLinkStore) DeleteByUser(ctx context.Context, user identity.UserID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUser", ctx, user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByUser indicates an expected call of DeleteByUser.
func (mr *MockLinkStoreMockRecorder) DeleteByUser(ctx, user any) *MockLinkStoreDeleteByUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUser", reflect.TypeOf((*MockLinkStore)(nil).DeleteByUser), ctx, user)
	return &MockLinkStoreDeleteByUserCall{Call: call}
}

// MockLinkStoreDeleteByUserCall wrap *gomock.Call
type MockLinkStoreDeleteByUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinkStoreDeleteByUserCall) Return(arg0 int, arg1 error) *MockLinkStoreDeleteByUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinkStoreDeleteByUserCall) Do(f func(context.Context, identity.UserID) (int, error)) *MockLinkStoreDeleteByUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinkStoreDeleteByUserCall) DoAndReturn(f func(context.Context, identity.UserID) (int, error)) *MockLinkStoreDeleteByUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByExternal mocks base method.
func (m *MockLinkStore) FindByExternal(ctx context.Context, provider, issuer, subject string) (*oidc.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByExternal", ctx, provider, issuer, subject)
	ret0, _ := ret[0].(*oidc.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByExternal indicates an expected call of FindByExternal.
func (mr *MockLinkStoreMockRecorder) FindByExternal(ctx, provider, issuer, subject any) *MockLinkStoreFindByExternalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByExternal", reflect.TypeOf((*MockLinkStore)(nil).FindByExternal), ctx, provider, issuer, subject)
	return &MockLinkStoreFindByExternalCall{Call: call}
}

// MockLinkStoreFindByExternalCall wrap *gomock.Call
type MockLinkStoreFindByExternalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinkStoreFindByExternalCall) Return(arg0 *oidc.Link, arg1 error) *MockLinkStoreFindByExternalCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinkStoreFindByExternalCall) Do(f func(context.Context, string, string, string) (*oidc.Link, error)) *MockLinkStoreFindByExternalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinkStoreFindByExternalCall) DoAndReturn(f func(context.Context, string, string, string) (*oidc.Link, error)) *MockLinkStoreFindByExternalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockLinkStore) Insert(ctx context.Context, l oidc.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, l)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockLinkStoreMockRecorder) Insert(ctx, l any) *MockLinkStoreInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockLinkStore)(nil).Insert), ctx, l)
	return &MockLinkStoreInsertCall{Call: call}
}

// MockLinkStoreInsertCall wrap *gomock.Call
type MockLinkStoreInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinkStoreInsertCall) Return(arg0 error) *MockLinkStoreInsertCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinkStoreInsertCall) Do(f func(context.Context, oidc.Link) error) *MockLinkStoreInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinkStoreInsertCall) DoAndReturn(f func(context.Context, oidc.Link) error) *MockLinkStoreInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
