// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/mfa (interfaces: Method)
//
// Generated by this command:
//
//	mockgen -destination=mfamethod_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/mfa Method
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"

	factor "github.com/kartaladev/scrty/factor"
	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockMethod is a mock of Method interface.
type MockMethod struct {
	ctrl     *gomock.Controller
	recorder *MockMethodMockRecorder
	isgomock struct{}
}

// MockMethodMockRecorder is the mock recorder for MockMethod.
type MockMethodMockRecorder struct {
	mock *MockMethod
}

// NewMockMethod creates a new mock instance.
func NewMockMethod(ctrl *gomock.Controller) *MockMethod {
	mock := &MockMethod{ctrl: ctrl}
	mock.recorder = &MockMethodMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMethod) EXPECT() *MockMethodMockRecorder {
	return m.recorder
}

// Channel mocks base method.
func (m *MockMethod) Channel() factor.Channel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Channel")
	ret0, _ := ret[0].(factor.Channel)
	return ret0
}

// Channel indicates an expected call of Channel.
func (mr *MockMethodMockRecorder) Channel() *MockMethodChannelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Channel", reflect.TypeOf((*MockMethod)(nil).Channel))
	return &MockMethodChannelCall{Call: call}
}

// MockMethodChannelCall wrap *gomock.Call
type MockMethodChannelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMethodChannelCall) Return(arg0 factor.Channel) *MockMethodChannelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMethodChannelCall) Do(f func() factor.Channel) *MockMethodChannelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMethodChannelCall) DoAndReturn(f func() factor.Channel) *MockMethodChannelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Enrolled mocks base method.
func (m *MockMethod) Enrolled(ctx context.Context, user identity.UserID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enrolled", ctx, user)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enrolled indicates an expected call of Enrolled.
func (mr *MockMethodMockRecorder) Enrolled(ctx, user any) *MockMethodEnrolledCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enrolled", reflect.TypeOf((*MockMethod)(nil).Enrolled), ctx, user)
	return &MockMethodEnrolledCall{Call: call}
}

// MockMethodEnrolledCall wrap *gomock.Call
type MockMethodEnrolledCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMethodEnrolledCall) Return(arg0 bool, arg1 error) *MockMethodEnrolledCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMethodEnrolledCall) Do(f func(context.Context, identity.UserID) (bool, error)) *MockMethodEnrolledCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMethodEnrolledCall) DoAndReturn(f func(context.Context, identity.UserID) (bool, error)) *MockMethodEnrolledCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockMethod) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockMethodMockRecorder) Name() *MockMethodNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockMethod)(nil).Name))
	return &MockMethodNameCall{Call: call}
}

// MockMethodNameCall wrap *gomock.Call
type MockMethodNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMethodNameCall) Return(arg0 string) *MockMethodNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMethodNameCall) Do(f func() string) *MockMethodNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMethodNameCall) DoAndReturn(f func() string) *MockMethodNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Verify mocks base method.
func (m *MockMethod) Verify(ctx context.Context, user identity.UserID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, user, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockMethodMockRecorder) Verify(ctx, user, code any) *MockMethodVerifyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockMethod)(nil).Verify), ctx, user, code)
	return &MockMethodVerifyCall{Call: call}
}

// MockMethodVerifyCall wrap *gomock.Call
type MockMethodVerifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMethodVerifyCall) Return(arg0 error) *MockMethodVerifyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMethodVerifyCall) Do(f func(context.Context, identity.UserID, string) error) *MockMethodVerifyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMethodVerifyCall) DoAndReturn(f func(context.Context, identity.UserID, string) error) *MockMethodVerifyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
