// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/onetime (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=onetimestore_mock_test.go -package=httpsec_test -typed -mock_names=Store=MockOnetimeStore github.com/kartaladev/scrty/onetime Store
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"
	time "time"

	onetime "github.com/kartaladev/scrty/onetime"
	id "github.com/kartaladev/scrty/pkg/id"
	gomock "go.uber.org/mock/gomock"
)

// MockOnetimeStore is a mock of Store interface.
type MockOnetimeStore struct {
	ctrl     *gomock.Controller
	recorder *MockOnetimeStoreMockRecorder
	isgomock struct{}
}

// MockOnetimeStoreMockRecorder is the mock recorder for MockOnetimeStore.
type MockOnetimeStoreMockRecorder struct {
	mock *MockOnetimeStore
}

// NewMockOnetimeStore creates a new mock instance.
func NewMockOnetimeStore(ctrl *gomock.Controller) *MockOnetimeStore {
	mock := &MockOnetimeStore{ctrl: ctrl}
	mock.recorder = &MockOnetimeStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOnetimeStore) EXPECT() *MockOnetimeStoreMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockOnetimeStore) Consume(ctx context.Context, tokenID id.ID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, tokenID, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockOnetimeStoreMockRecorder) Consume(ctx, tokenID, at any) *MockOnetimeStoreConsumeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockOnetimeStore)(nil).Consume), ctx, tokenID, at)
	return &MockOnetimeStoreConsumeCall{Call: call}
}

// MockOnetimeStoreConsumeCall wrap *gomock.Call
type MockOnetimeStoreConsumeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOnetimeStoreConsumeCall) Return(arg0 error) *MockOnetimeStoreConsumeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOnetimeStoreConsumeCall) Do(f func(context.Context, id.ID, time.Time) error) *MockOnetimeStoreConsumeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOnetimeStoreConsumeCall) DoAndReturn(f func(context.Context, id.ID, time.Time) error) *MockOnetimeStoreConsumeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CountRecentBySubject mocks base method.
func (m *MockOnetimeStore) CountRecentBySubject(ctx context.Context, purpose, subject string, since time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecentBySubject", ctx, purpose, subject, since)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecentBySubject indicates an expected call of CountRecentBySubject.
func (mr *MockOnetimeStoreMockRecorder) CountRecentBySubject(ctx, purpose, subject, since any) *MockOnetimeStoreCountRecentBySubjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecentBySubject", reflect.TypeOf((*MockOnetimeStore)(nil).CountRecentBySubject), ctx, purpose, subject, since)
	return &MockOnetimeStoreCountRecentBySubjectCall{Call: call}
}

// MockOnetimeStoreCountRecentBySubjectCall wrap *gomock.Call
type MockOnetimeStoreCountRecentBySubjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOnetimeStoreCountRecentBySubjectCall) Return(arg0 int, arg1 error) *MockOnetimeStoreCountRecentBySubjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOnetimeStoreCountRecentBySubjectCall) Do(f func(context.Context, string, string, time.Time) (int, error)) *MockOnetimeStoreCountRecentBySubjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOnetimeStoreCountRecentBySubjectCall) DoAndReturn(f func(context.Context, string, string, time.Time) (int, error)) *MockOnetimeStoreCountRecentBySubjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByID mocks base method.
func (m *MockOnetimeStore) FindByID(ctx context.Context, tokenID id.ID) (*onetime.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, tokenID)
	ret0, _ := ret[0].(*onetime.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockOnetimeStoreMockRecorder) FindByID(ctx, tokenID any) *MockOnetimeStoreFindByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockOnetimeStore)(nil).FindByID), ctx, tokenID)
	return &MockOnetimeStoreFindByIDCall{Call: call}
}

// MockOnetimeStoreFindByIDCall wrap *gomock.Call
type MockOnetimeStoreFindByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOnetimeStoreFindByIDCall) Return(arg0 *onetime.Token, arg1 error) *MockOnetimeStoreFindByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOnetimeStoreFindByIDCall) Do(f func(context.Context, id.ID) (*onetime.Token, error)) *MockOnetimeStoreFindByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOnetimeStoreFindByIDCall) DoAndReturn(f func(context.Context, id.ID) (*onetime.Token, error)) *MockOnetimeStoreFindByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockOnetimeStore) Insert(ctx context.Context, tok onetime.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, tok)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockOnetimeStoreMockRecorder) Insert(ctx, tok any) *MockOnetimeStoreInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockOnetimeStore)(nil).Insert), ctx, tok)
	return &MockOnetimeStoreInsertCall{Call: call}
}

// MockOnetimeStoreInsertCall wrap *gomock.Call
type MockOnetimeStoreInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOnetimeStoreInsertCall) Return(arg0 error) *MockOnetimeStoreInsertCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOnetimeStoreInsertCall) Do(f func(context.Context, onetime.Token) error) *MockOnetimeStoreInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOnetimeStoreInsertCall) DoAndReturn(f func(context.Context, onetime.Token) error) *MockOnetimeStoreInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
