// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/passkey (interfaces: Verifier,ParsedRegistration,ParsedAssertion)
//
// Generated by this command:
//
//	mockgen -destination=passkeyverifier_mock_test.go -package=httpsec_test -typed -mock_names=Verifier=MockPasskeyVerifier,ParsedRegistration=MockParsedRegistration,ParsedAssertion=MockParsedAssertion github.com/kartaladev/scrty/passkey Verifier,ParsedRegistration,ParsedAssertion
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	passkey "github.com/kartaladev/scrty/passkey"
	gomock "go.uber.org/mock/gomock"
)

// MockPasskeyVerifier is a mock of Verifier interface.
type MockPasskeyVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockPasskeyVerifierMockRecorder
	isgomock struct{}
}

// MockPasskeyVerifierMockRecorder is the mock recorder for MockPasskeyVerifier.
type MockPasskeyVerifierMockRecorder struct {
	mock *MockPasskeyVerifier
}

// NewMockPasskeyVerifier creates a new mock instance.
func NewMockPasskeyVerifier(ctrl *gomock.Controller) *MockPasskeyVerifier {
	mock := &MockPasskeyVerifier{ctrl: ctrl}
	mock.recorder = &MockPasskeyVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasskeyVerifier) EXPECT() *MockPasskeyVerifierMockRecorder {
	return m.recorder
}

// CreationOptions mocks base method.
func (m *MockPasskeyVerifier) CreationOptions(ctx context.Context, in passkey.CreationInput) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreationOptions", ctx, in)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreationOptions indicates an expected call of CreationOptions.
func (mr *MockPasskeyVerifierMockRecorder) CreationOptions(ctx, in any) *MockPasskeyVerifierCreationOptionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreationOptions", reflect.TypeOf((*MockPasskeyVerifier)(nil).CreationOptions), ctx, in)
	return &MockPasskeyVerifierCreationOptionsCall{Call: call}
}

// MockPasskeyVerifierCreationOptionsCall wrap *gomock.Call
type MockPasskeyVerifierCreationOptionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPasskeyVerifierCreationOptionsCall) Return(arg0 json.RawMessage, arg1 error) *MockPasskeyVerifierCreationOptionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPasskeyVerifierCreationOptionsCall) Do(f func(context.Context, passkey.CreationInput) (json.RawMessage, error)) *MockPasskeyVerifierCreationOptionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPasskeyVerifierCreationOptionsCall) DoAndReturn(f func(context.Context, passkey.CreationInput) (json.RawMessage, error)) *MockPasskeyVerifierCreationOptionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ParseAssertion mocks base method.
func (m *MockPasskeyVerifier) ParseAssertion(body []byte) (passkey.ParsedAssertion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAssertion", body)
	ret0, _ := ret[0].(passkey.ParsedAssertion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAssertion indicates an expected call of ParseAssertion.
func (mr *MockPasskeyVerifierMockRecorder) ParseAssertion(body any) *MockPasskeyVerifierParseAssertionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAssertion", reflect.TypeOf((*MockPasskeyVerifier)(nil).ParseAssertion), body)
	return &MockPasskeyVerifierParseAssertionCall{Call: call}
}

// MockPasskeyVerifierParseAssertionCall wrap *gomock.Call
type MockPasskeyVerifierParseAssertionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPasskeyVerifierParseAssertionCall) Return(arg0 passkey.ParsedAssertion, arg1 error) *MockPasskeyVerifierParseAssertionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPasskeyVerifierParseAssertionCall) Do(f func([]byte) (passkey.ParsedAssertion, error)) *MockPasskeyVerifierParseAssertionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPasskeyVerifierParseAssertionCall) DoAndReturn(f func([]byte) (passkey.ParsedAssertion, error)) *MockPasskeyVerifierParseAssertionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ParseRegistration mocks base method.
func (m *MockPasskeyVerifier) ParseRegistration(body []byte) (passkey.ParsedRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRegistration", body)
	ret0, _ := ret[0].(passkey.ParsedRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseRegistration indicates an expected call of ParseRegistration.
func (mr *MockPasskeyVerifierMockRecorder) ParseRegistration(body any) *MockPasskeyVerifierParseRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRegistration", reflect.TypeOf((*MockPasskeyVerifier)(nil).ParseRegistration), body)
	return &MockPasskeyVerifierParseRegistrationCall{Call: call}
}

// MockPasskeyVerifierParseRegistrationCall wrap *gomock.Call
type MockPasskeyVerifierParseRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPasskeyVerifierParseRegistrationCall) Return(arg0 passkey.ParsedRegistration, arg1 error) *MockPasskeyVerifierParseRegistrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPasskeyVerifierParseRegistrationCall) Do(f func([]byte) (passkey.ParsedRegistration, error)) *MockPasskeyVerifierParseRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPasskeyVerifierParseRegistrationCall) DoAndReturn(f func([]byte) (passkey.ParsedRegistration, error)) *MockPasskeyVerifierParseRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RelyingParty mocks base method.
func (m *MockPasskeyVerifier) RelyingParty() passkey.RelyingParty {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelyingParty")
	ret0, _ := ret[0].(passkey.RelyingParty)
	return ret0
}

// RelyingParty indicates an expected call of RelyingParty.
func (mr *MockPasskeyVerifierMockRecorder) RelyingParty() *MockPasskeyVerifierRelyingPartyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelyingParty", reflect.TypeOf((*MockPasskeyVerifier)(nil).RelyingParty))
	return &MockPasskeyVerifierRelyingPartyCall{Call: call}
}

// MockPasskeyVerifierRelyingPartyCall wrap *gomock.Call
type MockPasskeyVerifierRelyingPartyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPasskeyVerifierRelyingPartyCall) Return(arg0 passkey.RelyingParty) *MockPasskeyVerifierRelyingPartyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPasskeyVerifierRelyingPartyCall) Do(f func() passkey.RelyingParty) *MockPasskeyVerifierRelyingPartyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPasskeyVerifierRelyingPartyCall) DoAndReturn(f func() passkey.RelyingParty) *MockPasskeyVerifierRelyingPartyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RequestOptions mocks base method.
func (m *MockPasskeyVerifier) RequestOptions(ctx context.Context, in passkey.RequestInput) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestOptions", ctx, in)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestOptions indicates an expected call of RequestOptions.
func (mr *MockPasskeyVerifierMockRecorder) RequestOptions(ctx, in any) *MockPasskeyVerifierRequestOptionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestOptions", reflect.TypeOf((*MockPasskeyVerifier)(nil).RequestOptions), ctx, in)
	return &MockPasskeyVerifierRequestOptionsCall{Call: call}
}

// MockPasskeyVerifierRequestOptionsCall wrap *gomock.Call
type MockPasskeyVerifierRequestOptionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPasskeyVerifierRequestOptionsCall) Return(arg0 json.RawMessage, arg1 error) *MockPasskeyVerifierRequestOptionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPasskeyVerifierRequestOptionsCall) Do(f func(context.Context, passkey.RequestInput) (json.RawMessage, error)) *MockPasskeyVerifierRequestOptionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPasskeyVerifierRequestOptionsCall) DoAndReturn(f func(context.Context, passkey.RequestInput) (json.RawMessage, error)) *MockPasskeyVerifierRequestOptionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VerifyAssertion mocks base method.
func (m *MockPasskeyVerifier) VerifyAssertion(ctx context.Context, p passkey.ParsedAssertion, c *passkey.Credential, exp passkey.AssertionExpectation) (*passkey.AssertionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAssertion", ctx, p, c, exp)
	ret0, _ := ret[0].(*passkey.AssertionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAssertion indicates an expected call of VerifyAssertion.
func (mr *MockPasskeyVerifierMockRecorder) VerifyAssertion(ctx, p, c, exp any) *MockPasskeyVerifierVerifyAssertionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAssertion", reflect.TypeOf((*MockPasskeyVerifier)(nil).VerifyAssertion), ctx, p, c, exp)
	return &MockPasskeyVerifierVerifyAssertionCall{Call: call}
}

// MockPasskeyVerifierVerifyAssertionCall wrap *gomock.Call
type MockPasskeyVerifierVerifyAssertionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c_2 *MockPasskeyVerifierVerifyAssertionCall) Return(arg0 *passkey.AssertionResult, arg1 error) *MockPasskeyVerifierVerifyAssertionCall {
	c_2.Call = c_2.Call.Return(arg0, arg1)
	return c_2
}

// Do rewrite *gomock.Call.Do
func (c_2 *MockPasskeyVerifierVerifyAssertionCall) Do(f func(context.Context, passkey.ParsedAssertion, *passkey.Credential, passkey.AssertionExpectation) (*passkey.AssertionResult, error)) *MockPasskeyVerifierVerifyAssertionCall {
	c_2.Call = c_2.Call.Do(f)
	return c_2
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c_2 *MockPasskeyVerifierVerifyAssertionCall) DoAndReturn(f func(context.Context, passkey.ParsedAssertion, *passkey.Credential, passkey.AssertionExpectation) (*passkey.AssertionResult, error)) *MockPasskeyVerifierVerifyAssertionCall {
	c_2.Call = c_2.Call.DoAndReturn(f)
	return c_2
}

// VerifyRegistration mocks base method.
func (m *MockPasskeyVerifier) VerifyRegistration(ctx context.Context, p passkey.ParsedRegistration, exp passkey.RegistrationExpectation) (*passkey.NewCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRegistration", ctx, p, exp)
	ret0, _ := ret[0].(*passkey.NewCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRegistration indicates an expected call of VerifyRegistration.
func (mr *MockPasskeyVerifierMockRecorder) VerifyRegistration(ctx, p, exp any) *MockPasskeyVerifierVerifyRegistrationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRegistration", reflect.TypeOf((*MockPasskeyVerifier)(nil).VerifyRegistration), ctx, p, exp)
	return &MockPasskeyVerifierVerifyRegistrationCall{Call: call}
}

// MockPasskeyVerifierVerifyRegistrationCall wrap *gomock.Call
type MockPasskeyVerifierVerifyRegistrationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPasskeyVerifierVerifyRegistrationCall) Return(arg0 *passkey.NewCredential, arg1 error) *MockPasskeyVerifierVerifyRegistrationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPasskeyVerifierVerifyRegistrationCall) Do(f func(context.Context, passkey.ParsedRegistration, passkey.RegistrationExpectation) (*passkey.NewCredential, error)) *MockPasskeyVerifierVerifyRegistrationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPasskeyVerifierVerifyRegistrationCall) DoAndReturn(f func(context.Context, passkey.ParsedRegistration, passkey.RegistrationExpectation) (*passkey.NewCredential, error)) *MockPasskeyVerifierVerifyRegistrationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockParsedRegistration is a mock of ParsedRegistration interface.
type MockParsedRegistration struct {
	ctrl     *gomock.Controller
	recorder *MockParsedRegistrationMockRecorder
	isgomock struct{}
}

// MockParsedRegistrationMockRecorder is the mock recorder for MockParsedRegistration.
type MockParsedRegistrationMockRecorder struct {
	mock *MockParsedRegistration
}

// NewMockParsedRegistration creates a new mock instance.
func NewMockParsedRegistration(ctrl *gomock.Controller) *MockParsedRegistration {
	mock := &MockParsedRegistration{ctrl: ctrl}
	mock.recorder = &MockParsedRegistrationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParsedRegistration) EXPECT() *MockParsedRegistrationMockRecorder {
	return m.recorder
}

// Challenge mocks base method.
func (m *MockParsedRegistration) Challenge() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Challenge")
	ret0, _ := ret[0].(string)
	return ret0
}

// Challenge indicates an expected call of Challenge.
func (mr *MockParsedRegistrationMockRecorder) Challenge() *MockParsedRegistrationChallengeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Challenge", reflect.TypeOf((*MockParsedRegistration)(nil).Challenge))
	return &MockParsedRegistrationChallengeCall{Call: call}
}

// MockParsedRegistrationChallengeCall wrap *gomock.Call
type MockParsedRegistrationChallengeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParsedRegistrationChallengeCall) Return(arg0 string) *MockParsedRegistrationChallengeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParsedRegistrationChallengeCall) Do(f func() string) *MockParsedRegistrationChallengeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParsedRegistrationChallengeCall) DoAndReturn(f func() string) *MockParsedRegistrationChallengeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CredentialID mocks base method.
func (m *MockParsedRegistration) CredentialID() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CredentialID")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// CredentialID indicates an expected call of CredentialID.
func (mr *MockParsedRegistrationMockRecorder) CredentialID() *MockParsedRegistrationCredentialIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CredentialID", reflect.TypeOf((*MockParsedRegistration)(nil).CredentialID))
	return &MockParsedRegistrationCredentialIDCall{Call: call}
}

// MockParsedRegistrationCredentialIDCall wrap *gomock.Call
type MockParsedRegistrationCredentialIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParsedRegistrationCredentialIDCall) Return(arg0 []byte) *MockParsedRegistrationCredentialIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParsedRegistrationCredentialIDCall) Do(f func() []byte) *MockParsedRegistrationCredentialIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParsedRegistrationCredentialIDCall) DoAndReturn(f func() []byte) *MockParsedRegistrationCredentialIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockParsedRegistration) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockParsedRegistrationMockRecorder) Name() *MockParsedRegistrationNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockParsedRegistration)(nil).Name))
	return &MockParsedRegistrationNameCall{Call: call}
}

// MockParsedRegistrationNameCall wrap *gomock.Call
type MockParsedRegistrationNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParsedRegistrationNameCall) Return(arg0 string) *MockParsedRegistrationNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParsedRegistrationNameCall) Do(f func() string) *MockParsedRegistrationNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParsedRegistrationNameCall) DoAndReturn(f func() string) *MockParsedRegistrationNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockParsedAssertion is a mock of ParsedAssertion interface.
type MockParsedAssertion struct {
	ctrl     *gomock.Controller
	recorder *MockParsedAssertionMockRecorder
	isgomock struct{}
}

// MockParsedAssertionMockRecorder is the mock recorder for MockParsedAssertion.
type MockParsedAssertionMockRecorder struct {
	mock *MockParsedAssertion
}

// NewMockParsedAssertion creates a new mock instance.
func NewMockParsedAssertion(ctrl *gomock.Controller) *MockParsedAssertion {
	mock := &MockParsedAssertion{ctrl: ctrl}
	mock.recorder = &MockParsedAssertionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParsedAssertion) EXPECT() *MockParsedAssertionMockRecorder {
	return m.recorder
}

// Challenge mocks base method.
func (m *MockParsedAssertion) Challenge() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Challenge")
	ret0, _ := ret[0].(string)
	return ret0
}

// Challenge indicates an expected call of Challenge.
func (mr *MockParsedAssertionMockRecorder) Challenge() *MockParsedAssertionChallengeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Challenge", reflect.TypeOf((*MockParsedAssertion)(nil).Challenge))
	return &MockParsedAssertionChallengeCall{Call: call}
}

// MockParsedAssertionChallengeCall wrap *gomock.Call
type MockParsedAssertionChallengeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParsedAssertionChallengeCall) Return(arg0 string) *MockParsedAssertionChallengeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParsedAssertionChallengeCall) Do(f func() string) *MockParsedAssertionChallengeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParsedAssertionChallengeCall) DoAndReturn(f func() string) *MockParsedAssertionChallengeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CredentialID mocks base method.
func (m *MockParsedAssertion) CredentialID() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CredentialID")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// CredentialID indicates an expected call of CredentialID.
func (mr *MockParsedAssertionMockRecorder) CredentialID() *MockParsedAssertionCredentialIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CredentialID", reflect.TypeOf((*MockParsedAssertion)(nil).CredentialID))
	return &MockParsedAssertionCredentialIDCall{Call: call}
}

// MockParsedAssertionCredentialIDCall wrap *gomock.Call
type MockParsedAssertionCredentialIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParsedAssertionCredentialIDCall) Return(arg0 []byte) *MockParsedAssertionCredentialIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParsedAssertionCredentialIDCall) Do(f func() []byte) *MockParsedAssertionCredentialIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParsedAssertionCredentialIDCall) DoAndReturn(f func() []byte) *MockParsedAssertionCredentialIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UserHandle mocks base method.
func (m *MockParsedAssertion) UserHandle() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserHandle")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// UserHandle indicates an expected call of UserHandle.
func (mr *MockParsedAssertionMockRecorder) UserHandle() *MockParsedAssertionUserHandleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserHandle", reflect.TypeOf((*MockParsedAssertion)(nil).UserHandle))
	return &MockParsedAssertionUserHandleCall{Call: call}
}

// MockParsedAssertionUserHandleCall wrap *gomock.Call
type MockParsedAssertionUserHandleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockParsedAssertionUserHandleCall) Return(arg0 []byte) *MockParsedAssertionUserHandleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockParsedAssertionUserHandleCall) Do(f func() []byte) *MockParsedAssertionUserHandleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockParsedAssertionUserHandleCall) DoAndReturn(f func() []byte) *MockParsedAssertionUserHandleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
