// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/recovery (interfaces: RecordStore)
//
// Generated by this command:
//
//	mockgen -destination=recordstore_mock_test.go -package=httpsec_test -typed -mock_names=RecordStore=MockRecordStore github.com/kartaladev/scrty/recovery RecordStore
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"
	time "time"

	identity "github.com/kartaladev/scrty/identity"
	id "github.com/kartaladev/scrty/pkg/id"
	recovery "github.com/kartaladev/scrty/recovery"
	gomock "go.uber.org/mock/gomock"
)

// MockRecordStore is a mock of RecordStore interface.
type MockRecordStore struct {
	ctrl     *gomock.Controller
	recorder *MockRecordStoreMockRecorder
	isgomock struct{}
}

// MockRecordStoreMockRecorder is the mock recorder for MockRecordStore.
type MockRecordStoreMockRecorder struct {
	mock *MockRecordStore
}

// NewMockRecordStore creates a new mock instance.
func NewMockRecordStore(ctrl *gomock.Controller) *MockRecordStore {
	mock := &MockRecordStore{ctrl: ctrl}
	mock.recorder = &MockRecordStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordStore) EXPECT() *MockRecordStoreMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockRecordStore) Cancel(ctx context.Context, arg1 id.ID, at time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, arg1, at)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockRecordStoreMockRecorder) Cancel(ctx, arg1, at any) *MockRecordStoreCancelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockRecordStore)(nil).Cancel), ctx, arg1, at)
	return &MockRecordStoreCancelCall{Call: call}
}

// MockRecordStoreCancelCall wrap *gomock.Call
type MockRecordStoreCancelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordStoreCancelCall) Return(arg0 int, arg1 error) *MockRecordStoreCancelCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordStoreCancelCall) Do(f func(context.Context, id.ID, time.Time) (int, error)) *MockRecordStoreCancelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordStoreCancelCall) DoAndReturn(f func(context.Context, id.ID, time.Time) (int, error)) *MockRecordStoreCancelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CancelPending mocks base method.
func (m *MockRecordStore) CancelPending(ctx context.Context, user identity.UserID, at time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelPending", ctx, user, at)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelPending indicates an expected call of CancelPending.
func (mr *MockRecordStoreMockRecorder) CancelPending(ctx, user, at any) *MockRecordStoreCancelPendingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPending", reflect.TypeOf((*MockRecordStore)(nil).CancelPending), ctx, user, at)
	return &MockRecordStoreCancelPendingCall{Call: call}
}

// MockRecordStoreCancelPendingCall wrap *gomock.Call
type MockRecordStoreCancelPendingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordStoreCancelPendingCall) Return(arg0 int, arg1 error) *MockRecordStoreCancelPendingCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordStoreCancelPendingCall) Do(f func(context.Context, identity.UserID, time.Time) (int, error)) *MockRecordStoreCancelPendingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordStoreCancelPendingCall) DoAndReturn(f func(context.Context, identity.UserID, time.Time) (int, error)) *MockRecordStoreCancelPendingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Complete mocks base method.
func (m *MockRecordStore) Complete(ctx context.Context, arg1 id.ID, at time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, arg1, at)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockRecordStoreMockRecorder) Complete(ctx, arg1, at any) *MockRecordStoreCompleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockRecordStore)(nil).Complete), ctx, arg1, at)
	return &MockRecordStoreCompleteCall{Call: call}
}

// MockRecordStoreCompleteCall wrap *gomock.Call
type MockRecordStoreCompleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordStoreCompleteCall) Return(arg0 bool, arg1 error) *MockRecordStoreCompleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordStoreCompleteCall) Do(f func(context.Context, id.ID, time.Time) (bool, error)) *MockRecordStoreCompleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordStoreCompleteCall) DoAndReturn(f func(context.Context, id.ID, time.Time) (bool, error)) *MockRecordStoreCompleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Find mocks base method.
func (m *MockRecordStore) Find(ctx context.Context, arg1 id.ID) (*recovery.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, arg1)
	ret0, _ := ret[0].(*recovery.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRecordStoreMockRecorder) Find(ctx, arg1 any) *MockRecordStoreFindCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRecordStore)(nil).Find), ctx, arg1)
	return &MockRecordStoreFindCall{Call: call}
}

// MockRecordStoreFindCall wrap *gomock.Call
type MockRecordStoreFindCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordStoreFindCall) Return(arg0 *recovery.Record, arg1 error) *MockRecordStoreFindCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordStoreFindCall) Do(f func(context.Context, id.ID) (*recovery.Record, error)) *MockRecordStoreFindCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordStoreFindCall) DoAndReturn(f func(context.Context, id.ID) (*recovery.Record, error)) *MockRecordStoreFindCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockRecordStore) Insert(ctx context.Context, r recovery.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockRecordStoreMockRecorder) Insert(ctx, r any) *MockRecordStoreInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockRecordStore)(nil).Insert), ctx, r)
	return &MockRecordStoreInsertCall{Call: call}
}

// MockRecordStoreInsertCall wrap *gomock.Call
type MockRecordStoreInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordStoreInsertCall) Return(arg0 error) *MockRecordStoreInsertCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordStoreInsertCall) Do(f func(context.Context, recovery.Record) error) *MockRecordStoreInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordStoreInsertCall) DoAndReturn(f func(context.Context, recovery.Record) error) *MockRecordStoreInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LatestCompletion mocks base method.
func (m *MockRecordStore) LatestCompletion(ctx context.Context, user identity.UserID) (time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestCompletion", ctx, user)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LatestCompletion indicates an expected call of LatestCompletion.
func (mr *MockRecordStoreMockRecorder) LatestCompletion(ctx, user any) *MockRecordStoreLatestCompletionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestCompletion", reflect.TypeOf((*MockRecordStore)(nil).LatestCompletion), ctx, user)
	return &MockRecordStoreLatestCompletionCall{Call: call}
}

// MockRecordStoreLatestCompletionCall wrap *gomock.Call
type MockRecordStoreLatestCompletionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordStoreLatestCompletionCall) Return(arg0 time.Time, arg1 bool, arg2 error) *MockRecordStoreLatestCompletionCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordStoreLatestCompletionCall) Do(f func(context.Context, identity.UserID) (time.Time, bool, error)) *MockRecordStoreLatestCompletionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordStoreLatestCompletionCall) DoAndReturn(f func(context.Context, identity.UserID) (time.Time, bool, error)) *MockRecordStoreLatestCompletionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
