// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/session (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=sessionstore_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/session Store
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	session "github.com/kartaladev/scrty/session"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CountActiveByUser mocks base method.
func (m *MockStore) CountActiveByUser(ctx context.Context, user identity.UserID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByUser", ctx, user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveByUser indicates an expected call of CountActiveByUser.
func (mr *MockStoreMockRecorder) CountActiveByUser(ctx, user any) *MockStoreCountActiveByUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByUser", reflect.TypeOf((*MockStore)(nil).CountActiveByUser), ctx, user)
	return &MockStoreCountActiveByUserCall{Call: call}
}

// MockStoreCountActiveByUserCall wrap *gomock.Call
type MockStoreCountActiveByUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreCountActiveByUserCall) Return(arg0 int, arg1 error) *MockStoreCountActiveByUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreCountActiveByUserCall) Do(f func(context.Context, identity.UserID) (int, error)) *MockStoreCountActiveByUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreCountActiveByUserCall) DoAndReturn(f func(context.Context, identity.UserID) (int, error)) *MockStoreCountActiveByUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockStore) Create(ctx context.Context, s *session.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStoreMockRecorder) Create(ctx, s any) *MockStoreCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStore)(nil).Create), ctx, s)
	return &MockStoreCreateCall{Call: call}
}

// MockStoreCreateCall wrap *gomock.Call
type MockStoreCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreCreateCall) Return(arg0 error) *MockStoreCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreCreateCall) Do(f func(context.Context, *session.Session) error) *MockStoreCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreCreateCall) DoAndReturn(f func(context.Context, *session.Session) error) *MockStoreCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockStore) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStoreMockRecorder) Delete(ctx, id any) *MockStoreDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStore)(nil).Delete), ctx, id)
	return &MockStoreDeleteCall{Call: call}
}

// MockStoreDeleteCall wrap *gomock.Call
type MockStoreDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreDeleteCall) Return(arg0 error) *MockStoreDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreDeleteCall) Do(f func(context.Context, string) error) *MockStoreDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockStoreDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteByExternalSession mocks base method.
func (m *MockStore) DeleteByExternalSession(ctx context.Context, issuer, sessionID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByExternalSession", ctx, issuer, sessionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByExternalSession indicates an expected call of DeleteByExternalSession.
func (mr *MockStoreMockRecorder) DeleteByExternalSession(ctx, issuer, sessionID any) *MockStoreDeleteByExternalSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByExternalSession", reflect.TypeOf((*MockStore)(nil).DeleteByExternalSession), ctx, issuer, sessionID)
	return &MockStoreDeleteByExternalSessionCall{Call: call}
}

// MockStoreDeleteByExternalSessionCall wrap *gomock.Call
type MockStoreDeleteByExternalSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreDeleteByExternalSessionCall) Return(arg0 int, arg1 error) *MockStoreDeleteByExternalSessionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreDeleteByExternalSessionCall) Do(f func(context.Context, string, string) (int, error)) *MockStoreDeleteByExternalSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreDeleteByExternalSessionCall) DoAndReturn(f func(context.Context, string, string) (int, error)) *MockStoreDeleteByExternalSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteByUser mocks base method.
func (m *MockStore) DeleteByUser(ctx context.Context, user identity.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUser indicates an expected call of DeleteByUser.
func (mr *MockStoreMockRecorder) DeleteByUser(ctx, user any) *MockStoreDeleteByUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUser", reflect.TypeOf((*MockStore)(nil).DeleteByUser), ctx, user)
	return &MockStoreDeleteByUserCall{Call: call}
}

// MockStoreDeleteByUserCall wrap *gomock.Call
type MockStoreDeleteByUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreDeleteByUserCall) Return(arg0 error) *MockStoreDeleteByUserCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreDeleteByUserCall) Do(f func(context.Context, identity.UserID) error) *MockStoreDeleteByUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreDeleteByUserCall) DoAndReturn(f func(context.Context, identity.UserID) error) *MockStoreDeleteByUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteByUserAndExternalIssuer mocks base method.
func (m *MockStore) DeleteByUserAndExternalIssuer(ctx context.Context, user identity.UserID, issuer string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserAndExternalIssuer", ctx, user, issuer)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByUserAndExternalIssuer indicates an expected call of DeleteByUserAndExternalIssuer.
func (mr *MockStoreMockRecorder) DeleteByUserAndExternalIssuer(ctx, user, issuer any) *MockStoreDeleteByUserAndExternalIssuerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserAndExternalIssuer", reflect.TypeOf((*MockStore)(nil).DeleteByUserAndExternalIssuer), ctx, user, issuer)
	return &MockStoreDeleteByUserAndExternalIssuerCall{Call: call}
}

// MockStoreDeleteByUserAndExternalIssuerCall wrap *gomock.Call
type MockStoreDeleteByUserAndExternalIssuerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreDeleteByUserAndExternalIssuerCall) Return(arg0 int, arg1 error) *MockStoreDeleteByUserAndExternalIssuerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreDeleteByUserAndExternalIssuerCall) Do(f func(context.Context, identity.UserID, string) (int, error)) *MockStoreDeleteByUserAndExternalIssuerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreDeleteByUserAndExternalIssuerCall) DoAndReturn(f func(context.Context, identity.UserID, string) (int, error)) *MockStoreDeleteByUserAndExternalIssuerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteExpired mocks base method.
func (m *MockStore) DeleteExpired(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockStoreMockRecorder) DeleteExpired(ctx any) *MockStoreDeleteExpiredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockStore)(nil).DeleteExpired), ctx)
	return &MockStoreDeleteExpiredCall{Call: call}
}

// MockStoreDeleteExpiredCall wrap *gomock.Call
type MockStoreDeleteExpiredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreDeleteExpiredCall) Return(arg0 int, arg1 error) *MockStoreDeleteExpiredCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreDeleteExpiredCall) Do(f func(context.Context) (int, error)) *MockStoreDeleteExpiredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreDeleteExpiredCall) DoAndReturn(f func(context.Context) (int, error)) *MockStoreDeleteExpiredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Load mocks base method.
func (m *MockStore) Load(ctx context.Context, id string) (*session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, id)
	ret0, _ := ret[0].(*session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockStoreMockRecorder) Load(ctx, id any) *MockStoreLoadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockStore)(nil).Load), ctx, id)
	return &MockStoreLoadCall{Call: call}
}

// MockStoreLoadCall wrap *gomock.Call
type MockStoreLoadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreLoadCall) Return(arg0 *session.Session, arg1 error) *MockStoreLoadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreLoadCall) Do(f func(context.Context, string) (*session.Session, error)) *MockStoreLoadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreLoadCall) DoAndReturn(f func(context.Context, string) (*session.Session, error)) *MockStoreLoadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockStore) Save(ctx context.Context, s *session.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStoreMockRecorder) Save(ctx, s any) *MockStoreSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStore)(nil).Save), ctx, s)
	return &MockStoreSaveCall{Call: call}
}

// MockStoreSaveCall wrap *gomock.Call
type MockStoreSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreSaveCall) Return(arg0 error) *MockStoreSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreSaveCall) Do(f func(context.Context, *session.Session) error) *MockStoreSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreSaveCall) DoAndReturn(f func(context.Context, *session.Session) error) *MockStoreSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
