// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/token (interfaces: Generator)
//
// Generated by this command:
//
//	mockgen -destination=tokengenerator_mock_test.go -package=httpsec_test -typed github.com/kartaladev/scrty/token Generator
//

// Package httpsec_test is a generated GoMock package.
package httpsec_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	token "github.com/kartaladev/scrty/token"
	gomock "go.uber.org/mock/gomock"
)

// MockGenerator is a mock of Generator interface.
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
	isgomock struct{}
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator.
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance.
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockGenerator) Generate(ctx context.Context, id string, p *identity.Principal) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, id, p)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockGeneratorMockRecorder) Generate(ctx, id, p any) *MockGeneratorGenerateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockGenerator)(nil).Generate), ctx, id, p)
	return &MockGeneratorGenerateCall{Call: call}
}

// MockGeneratorGenerateCall wrap *gomock.Call
type MockGeneratorGenerateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGeneratorGenerateCall) Return(arg0 string, arg1 error) *MockGeneratorGenerateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGeneratorGenerateCall) Do(f func(context.Context, string, *identity.Principal) (string, error)) *MockGeneratorGenerateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGeneratorGenerateCall) DoAndReturn(f func(context.Context, string, *identity.Principal) (string, error)) *MockGeneratorGenerateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Verify mocks base method.
func (m *MockGenerator) Verify(ctx context.Context, arg1 string) (*token.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, arg1)
	ret0, _ := ret[0].(*token.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockGeneratorMockRecorder) Verify(ctx, arg1 any) *MockGeneratorVerifyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockGenerator)(nil).Verify), ctx, arg1)
	return &MockGeneratorVerifyCall{Call: call}
}

// MockGeneratorVerifyCall wrap *gomock.Call
type MockGeneratorVerifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGeneratorVerifyCall) Return(arg0 *token.Claims, arg1 error) *MockGeneratorVerifyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGeneratorVerifyCall) Do(f func(context.Context, string) (*token.Claims, error)) *MockGeneratorVerifyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGeneratorVerifyCall) DoAndReturn(f func(context.Context, string) (*token.Claims, error)) *MockGeneratorVerifyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
