// Code generated by MockGen. DO NOT EDIT.
// Source: assurance_source.go
//
// Generated by this command:
//
//	mockgen -source=assurance_source.go -package=oidc_test -destination=assurance_source_mock_test.go -typed
//

// Package oidc_test is a generated GoMock package.
package oidc_test

import (
	context "context"
	reflect "reflect"

	oidc "github.com/kartaladev/scrty/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockAssuranceEvaluator is a mock of AssuranceEvaluator interface.
type MockAssuranceEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockAssuranceEvaluatorMockRecorder
	isgomock struct{}
}

// MockAssuranceEvaluatorMockRecorder is the mock recorder for MockAssuranceEvaluator.
type MockAssuranceEvaluatorMockRecorder struct {
	mock *MockAssuranceEvaluator
}

// NewMockAssuranceEvaluator creates a new mock instance.
func NewMockAssuranceEvaluator(ctrl *gomock.Controller) *MockAssuranceEvaluator {
	mock := &MockAssuranceEvaluator{ctrl: ctrl}
	mock.recorder = &MockAssuranceEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssuranceEvaluator) EXPECT() *MockAssuranceEvaluatorMockRecorder {
	return m.recorder
}

// MeetsAssurance mocks base method.
func (m *MockAssuranceEvaluator) MeetsAssurance(ctx context.Context, in oidc.AssuranceInput) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeetsAssurance", ctx, in)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MeetsAssurance indicates an expected call of MeetsAssurance.
func (mr *MockAssuranceEvaluatorMockRecorder) MeetsAssurance(ctx, in any) *MockAssuranceEvaluatorMeetsAssuranceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeetsAssurance", reflect.TypeOf((*MockAssuranceEvaluator)(nil).MeetsAssurance), ctx, in)
	return &MockAssuranceEvaluatorMeetsAssuranceCall{Call: call}
}

// MockAssuranceEvaluatorMeetsAssuranceCall wrap *gomock.Call
type MockAssuranceEvaluatorMeetsAssuranceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAssuranceEvaluatorMeetsAssuranceCall) Return(arg0 bool, arg1 error) *MockAssuranceEvaluatorMeetsAssuranceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAssuranceEvaluatorMeetsAssuranceCall) Do(f func(context.Context, oidc.AssuranceInput) (bool, error)) *MockAssuranceEvaluatorMeetsAssuranceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAssuranceEvaluatorMeetsAssuranceCall) DoAndReturn(f func(context.Context, oidc.AssuranceInput) (bool, error)) *MockAssuranceEvaluatorMeetsAssuranceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
