// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/identity (interfaces: UserLoader,UserProvisioner)
//
// Generated by this command:
//
//	mockgen -destination=broker_mocks_test.go -package=oidc_test -typed github.com/kartaladev/scrty/identity UserLoader,UserProvisioner
//

// Package oidc_test is a generated GoMock package.
package oidc_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserLoader is a mock of UserLoader interface.
type MockUserLoader struct {
	ctrl     *gomock.Controller
	recorder *MockUserLoaderMockRecorder
	isgomock struct{}
}

// MockUserLoaderMockRecorder is the mock recorder for MockUserLoader.
type MockUserLoaderMockRecorder struct {
	mock *MockUserLoader
}

// NewMockUserLoader creates a new mock instance.
func NewMockUserLoader(ctrl *gomock.Controller) *MockUserLoader {
	mock := &MockUserLoader{ctrl: ctrl}
	mock.recorder = &MockUserLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserLoader) EXPECT() *MockUserLoaderMockRecorder {
	return m.recorder
}

// LoadByUserID mocks base method.
func (m *MockUserLoader) LoadByUserID(ctx context.Context, id identity.UserID) (*identity.Details, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadByUserID", ctx, id)
	ret0, _ := ret[0].(*identity.Details)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadByUserID indicates an expected call of LoadByUserID.
func (mr *MockUserLoaderMockRecorder) LoadByUserID(ctx, id any) *MockUserLoaderLoadByUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadByUserID", reflect.TypeOf((*MockUserLoader)(nil).LoadByUserID), ctx, id)
	return &MockUserLoaderLoadByUserIDCall{Call: call}
}

// MockUserLoaderLoadByUserIDCall wrap *gomock.Call
type MockUserLoaderLoadByUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserLoaderLoadByUserIDCall) Return(arg0 *identity.Details, arg1 error) *MockUserLoaderLoadByUserIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserLoaderLoadByUserIDCall) Do(f func(context.Context, identity.UserID) (*identity.Details, error)) *MockUserLoaderLoadByUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserLoaderLoadByUserIDCall) DoAndReturn(f func(context.Context, identity.UserID) (*identity.Details, error)) *MockUserLoaderLoadByUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LoadByUsername mocks base method.
func (m *MockUserLoader) LoadByUsername(ctx context.Context, username string) (*identity.Details, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadByUsername", ctx, username)
	ret0, _ := ret[0].(*identity.Details)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadByUsername indicates an expected call of LoadByUsername.
func (mr *MockUserLoaderMockRecorder) LoadByUsername(ctx, username any) *MockUserLoaderLoadByUsernameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadByUsername", reflect.TypeOf((*MockUserLoader)(nil).LoadByUsername), ctx, username)
	return &MockUserLoaderLoadByUsernameCall{Call: call}
}

// MockUserLoaderLoadByUsernameCall wrap *gomock.Call
type MockUserLoaderLoadByUsernameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserLoaderLoadByUsernameCall) Return(arg0 *identity.Details, arg1 error) *MockUserLoaderLoadByUsernameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserLoaderLoadByUsernameCall) Do(f func(context.Context, string) (*identity.Details, error)) *MockUserLoaderLoadByUsernameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserLoaderLoadByUsernameCall) DoAndReturn(f func(context.Context, string) (*identity.Details, error)) *MockUserLoaderLoadByUsernameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockUserProvisioner is a mock of UserProvisioner interface.
type MockUserProvisioner struct {
	ctrl     *gomock.Controller
	recorder *MockUserProvisionerMockRecorder
	isgomock struct{}
}

// MockUserProvisionerMockRecorder is the mock recorder for MockUserProvisioner.
type MockUserProvisionerMockRecorder struct {
	mock *MockUserProvisioner
}

// NewMockUserProvisioner creates a new mock instance.
func NewMockUserProvisioner(ctrl *gomock.Controller) *MockUserProvisioner {
	mock := &MockUserProvisioner{ctrl: ctrl}
	mock.recorder = &MockUserProvisionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProvisioner) EXPECT() *MockUserProvisionerMockRecorder {
	return m.recorder
}

// Provision mocks base method.
func (m *MockUserProvisioner) Provision(ctx context.Context, username string, opts ...identity.UserOption) (*identity.Details, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, username}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Provision", varargs...)
	ret0, _ := ret[0].(*identity.Details)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Provision indicates an expected call of Provision.
func (mr *MockUserProvisionerMockRecorder) Provision(ctx, username any, opts ...any) *MockUserProvisionerProvisionCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, username}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provision", reflect.TypeOf((*MockUserProvisioner)(nil).Provision), varargs...)
	return &MockUserProvisionerProvisionCall{Call: call}
}

// MockUserProvisionerProvisionCall wrap *gomock.Call
type MockUserProvisionerProvisionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserProvisionerProvisionCall) Return(arg0 *identity.Details, arg1 error) *MockUserProvisionerProvisionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserProvisionerProvisionCall) Do(f func(context.Context, string, ...identity.UserOption) (*identity.Details, error)) *MockUserProvisionerProvisionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserProvisionerProvisionCall) DoAndReturn(f func(context.Context, string, ...identity.UserOption) (*identity.Details, error)) *MockUserProvisionerProvisionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockUserProvisioner) Update(ctx context.Context, username string, opts ...identity.UserOption) (*identity.Details, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, username}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*identity.Details)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserProvisionerMockRecorder) Update(ctx, username any, opts ...any) *MockUserProvisionerUpdateCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, username}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserProvisioner)(nil).Update), varargs...)
	return &MockUserProvisionerUpdateCall{Call: call}
}

// MockUserProvisionerUpdateCall wrap *gomock.Call
type MockUserProvisionerUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserProvisionerUpdateCall) Return(arg0 *identity.Details, arg1 error) *MockUserProvisionerUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserProvisionerUpdateCall) Do(f func(context.Context, string, ...identity.UserOption) (*identity.Details, error)) *MockUserProvisionerUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserProvisionerUpdateCall) DoAndReturn(f func(context.Context, string, ...identity.UserOption) (*identity.Details, error)) *MockUserProvisionerUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
