// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/pkg/id (interfaces: Generator)
//
// Generated by this command:
//
//	mockgen -destination=handoff_idgenerator_mock_test.go -package=oidc_test -typed -mock_names=Generator=MockHandoffIDGenerator github.com/kartaladev/scrty/pkg/id Generator
//

// Package oidc_test is a generated GoMock package.
package oidc_test

import (
	reflect "reflect"

	id "github.com/kartaladev/scrty/pkg/id"
	gomock "go.uber.org/mock/gomock"
)

// MockHandoffIDGenerator is a mock of Generator interface.
type MockHandoffIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockHandoffIDGeneratorMockRecorder
	isgomock struct{}
}

// MockHandoffIDGeneratorMockRecorder is the mock recorder for MockHandoffIDGenerator.
type MockHandoffIDGeneratorMockRecorder struct {
	mock *MockHandoffIDGenerator
}

// NewMockHandoffIDGenerator creates a new mock instance.
func NewMockHandoffIDGenerator(ctrl *gomock.Controller) *MockHandoffIDGenerator {
	mock := &MockHandoffIDGenerator{ctrl: ctrl}
	mock.recorder = &MockHandoffIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandoffIDGenerator) EXPECT() *MockHandoffIDGeneratorMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockHandoffIDGenerator) NewID() (id.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(id.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewID indicates an expected call of NewID.
func (mr *MockHandoffIDGeneratorMockRecorder) NewID() *MockHandoffIDGeneratorNewIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockHandoffIDGenerator)(nil).NewID))
	return &MockHandoffIDGeneratorNewIDCall{Call: call}
}

// MockHandoffIDGeneratorNewIDCall wrap *gomock.Call
type MockHandoffIDGeneratorNewIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandoffIDGeneratorNewIDCall) Return(arg0 id.ID, arg1 error) *MockHandoffIDGeneratorNewIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandoffIDGeneratorNewIDCall) Do(f func() (id.ID, error)) *MockHandoffIDGeneratorNewIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandoffIDGeneratorNewIDCall) DoAndReturn(f func() (id.ID, error)) *MockHandoffIDGeneratorNewIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
