// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -package=oidc_test -destination=ports_mock_test.go -typed
//

// Package oidc_test is a generated GoMock package.
package oidc_test

import (
	context "context"
	reflect "reflect"
	time "time"

	identity "github.com/kartaladev/scrty/identity"
	oidc "github.com/kartaladev/scrty/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockFlowStore is a mock of FlowStore interface.
type MockFlowStore struct {
	ctrl     *gomock.Controller
	recorder *MockFlowStoreMockRecorder
	isgomock struct{}
}

// MockFlowStoreMockRecorder is the mock recorder for MockFlowStore.
type MockFlowStoreMockRecorder struct {
	mock *MockFlowStore
}

// NewMockFlowStore creates a new mock instance.
func NewMockFlowStore(ctrl *gomock.Controller) *MockFlowStore {
	mock := &MockFlowStore{ctrl: ctrl}
	mock.recorder = &MockFlowStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlowStore) EXPECT() *MockFlowStoreMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockFlowStore) Begin(ctx context.Context, f oidc.Flow) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx, f)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockFlowStoreMockRecorder) Begin(ctx, f any) *MockFlowStoreBeginCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockFlowStore)(nil).Begin), ctx, f)
	return &MockFlowStoreBeginCall{Call: call}
}

// MockFlowStoreBeginCall wrap *gomock.Call
type MockFlowStoreBeginCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowStoreBeginCall) Return(handle string, err error) *MockFlowStoreBeginCall {
	c.Call = c.Call.Return(handle, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowStoreBeginCall) Do(f func(context.Context, oidc.Flow) (string, error)) *MockFlowStoreBeginCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowStoreBeginCall) DoAndReturn(f func(context.Context, oidc.Flow) (string, error)) *MockFlowStoreBeginCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Complete mocks base method.
func (m *MockFlowStore) Complete(ctx context.Context, handle, provider, state string) (oidc.Flow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, handle, provider, state)
	ret0, _ := ret[0].(oidc.Flow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockFlowStoreMockRecorder) Complete(ctx, handle, provider, state any) *MockFlowStoreCompleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockFlowStore)(nil).Complete), ctx, handle, provider, state)
	return &MockFlowStoreCompleteCall{Call: call}
}

// MockFlowStoreCompleteCall wrap *gomock.Call
type MockFlowStoreCompleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowStoreCompleteCall) Return(arg0 oidc.Flow, arg1 error) *MockFlowStoreCompleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowStoreCompleteCall) Do(f func(context.Context, string, string, string) (oidc.Flow, error)) *MockFlowStoreCompleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowStoreCompleteCall) DoAndReturn(f func(context.Context, string, string, string) (oidc.Flow, error)) *MockFlowStoreCompleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteExpired mocks base method.
func (m *MockFlowStore) DeleteExpired(ctx context.Context, before time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx, before)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockFlowStoreMockRecorder) DeleteExpired(ctx, before any) *MockFlowStoreDeleteExpiredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockFlowStore)(nil).DeleteExpired), ctx, before)
	return &MockFlowStoreDeleteExpiredCall{Call: call}
}

// MockFlowStoreDeleteExpiredCall wrap *gomock.Call
type MockFlowStoreDeleteExpiredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFlowStoreDeleteExpiredCall) Return(arg0 int, arg1 error) *MockFlowStoreDeleteExpiredCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFlowStoreDeleteExpiredCall) Do(f func(context.Context, time.Time) (int, error)) *MockFlowStoreDeleteExpiredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFlowStoreDeleteExpiredCall) DoAndReturn(f func(context.Context, time.Time) (int, error)) *MockFlowStoreDeleteExpiredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockIdentityBroker is a mock of IdentityBroker interface.
type MockIdentityBroker struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityBrokerMockRecorder
	isgomock struct{}
}

// MockIdentityBrokerMockRecorder is the mock recorder for MockIdentityBroker.
type MockIdentityBrokerMockRecorder struct {
	mock *MockIdentityBroker
}

// NewMockIdentityBroker creates a new mock instance.
func NewMockIdentityBroker(ctrl *gomock.Controller) *MockIdentityBroker {
	mock := &MockIdentityBroker{ctrl: ctrl}
	mock.recorder = &MockIdentityBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityBroker) EXPECT() *MockIdentityBrokerMockRecorder {
	return m.recorder
}

// Broker mocks base method.
func (m *MockIdentityBroker) Broker(ctx context.Context, ext oidc.ExternalIdentity) (*identity.Principal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Broker", ctx, ext)
	ret0, _ := ret[0].(*identity.Principal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Broker indicates an expected call of Broker.
func (mr *MockIdentityBrokerMockRecorder) Broker(ctx, ext any) *MockIdentityBrokerBrokerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broker", reflect.TypeOf((*MockIdentityBroker)(nil).Broker), ctx, ext)
	return &MockIdentityBrokerBrokerCall{Call: call}
}

// MockIdentityBrokerBrokerCall wrap *gomock.Call
type MockIdentityBrokerBrokerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIdentityBrokerBrokerCall) Return(arg0 *identity.Principal, arg1 error) *MockIdentityBrokerBrokerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIdentityBrokerBrokerCall) Do(f func(context.Context, oidc.ExternalIdentity) (*identity.Principal, error)) *MockIdentityBrokerBrokerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIdentityBrokerBrokerCall) DoAndReturn(f func(context.Context, oidc.ExternalIdentity) (*identity.Principal, error)) *MockIdentityBrokerBrokerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockLinkStore is a mock of LinkStore interface.
type MockLinkStore struct {
	ctrl     *gomock.Controller
	recorder *MockLinkStoreMockRecorder
	isgomock struct{}
}

// MockLinkStoreMockRecorder is the mock recorder for MockLinkStore.
type MockLinkStoreMockRecorder struct {
	mock *MockLinkStore
}

// NewMockLinkStore creates a new mock instance.
func NewMockLinkStore(ctrl *gomock.Controller) *MockLinkStore {
	mock := &MockLinkStore{ctrl: ctrl}
	mock.recorder = &MockLinkStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkStore) EXPECT() *MockLinkStoreMockRecorder {
	return m.recorder
}

// DeleteByUser mocks base method.
func (m *MockLinkStore) DeleteByUser(ctx context.Context, user identity.UserID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUser", ctx, user)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByUser indicates an expected call of DeleteByUser.
func (mr *MockLinkStoreMockRecorder) DeleteByUser(ctx, user any) *MockLinkStoreDeleteByUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUser", reflect.TypeOf((*MockLinkStore)(nil).DeleteByUser), ctx, user)
	return &MockLinkStoreDeleteByUserCall{Call: call}
}

// MockLinkStoreDeleteByUserCall wrap *gomock.Call
type MockLinkStoreDeleteByUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinkStoreDeleteByUserCall) Return(arg0 int, arg1 error) *MockLinkStoreDeleteByUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinkStoreDeleteByUserCall) Do(f func(context.Context, identity.UserID) (int, error)) *MockLinkStoreDeleteByUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinkStoreDeleteByUserCall) DoAndReturn(f func(context.Context, identity.UserID) (int, error)) *MockLinkStoreDeleteByUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByExternal mocks base method.
func (m *MockLinkStore) FindByExternal(ctx context.Context, provider, issuer, subject string) (*oidc.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByExternal", ctx, provider, issuer, subject)
	ret0, _ := ret[0].(*oidc.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByExternal indicates an expected call of FindByExternal.
func (mr *MockLinkStoreMockRecorder) FindByExternal(ctx, provider, issuer, subject any) *MockLinkStoreFindByExternalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByExternal", reflect.TypeOf((*MockLinkStore)(nil).FindByExternal), ctx, provider, issuer, subject)
	return &MockLinkStoreFindByExternalCall{Call: call}
}

// MockLinkStoreFindByExternalCall wrap *gomock.Call
type MockLinkStoreFindByExternalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinkStoreFindByExternalCall) Return(arg0 *oidc.Link, arg1 error) *MockLinkStoreFindByExternalCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinkStoreFindByExternalCall) Do(f func(context.Context, string, string, string) (*oidc.Link, error)) *MockLinkStoreFindByExternalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinkStoreFindByExternalCall) DoAndReturn(f func(context.Context, string, string, string) (*oidc.Link, error)) *MockLinkStoreFindByExternalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockLinkStore) Insert(ctx context.Context, l oidc.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, l)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockLinkStoreMockRecorder) Insert(ctx, l any) *MockLinkStoreInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockLinkStore)(nil).Insert), ctx, l)
	return &MockLinkStoreInsertCall{Call: call}
}

// MockLinkStoreInsertCall wrap *gomock.Call
type MockLinkStoreInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLinkStoreInsertCall) Return(arg0 error) *MockLinkStoreInsertCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLinkStoreInsertCall) Do(f func(context.Context, oidc.Link) error) *MockLinkStoreInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLinkStoreInsertCall) DoAndReturn(f func(context.Context, oidc.Link) error) *MockLinkStoreInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockHandoffStore is a mock of HandoffStore interface.
type MockHandoffStore struct {
	ctrl     *gomock.Controller
	recorder *MockHandoffStoreMockRecorder
	isgomock struct{}
}

// MockHandoffStoreMockRecorder is the mock recorder for MockHandoffStore.
type MockHandoffStoreMockRecorder struct {
	mock *MockHandoffStore
}

// NewMockHandoffStore creates a new mock instance.
func NewMockHandoffStore(ctrl *gomock.Controller) *MockHandoffStore {
	mock := &MockHandoffStore{ctrl: ctrl}
	mock.recorder = &MockHandoffStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandoffStore) EXPECT() *MockHandoffStoreMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockHandoffStore) Consume(ctx context.Context, tokenID string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, tokenID, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockHandoffStoreMockRecorder) Consume(ctx, tokenID, at any) *MockHandoffStoreConsumeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockHandoffStore)(nil).Consume), ctx, tokenID, at)
	return &MockHandoffStoreConsumeCall{Call: call}
}

// MockHandoffStoreConsumeCall wrap *gomock.Call
type MockHandoffStoreConsumeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandoffStoreConsumeCall) Return(arg0 error) *MockHandoffStoreConsumeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandoffStoreConsumeCall) Do(f func(context.Context, string, time.Time) error) *MockHandoffStoreConsumeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandoffStoreConsumeCall) DoAndReturn(f func(context.Context, string, time.Time) error) *MockHandoffStoreConsumeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteExpired mocks base method.
func (m *MockHandoffStore) DeleteExpired(ctx context.Context, before time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx, before)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockHandoffStoreMockRecorder) DeleteExpired(ctx, before any) *MockHandoffStoreDeleteExpiredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockHandoffStore)(nil).DeleteExpired), ctx, before)
	return &MockHandoffStoreDeleteExpiredCall{Call: call}
}

// MockHandoffStoreDeleteExpiredCall wrap *gomock.Call
type MockHandoffStoreDeleteExpiredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandoffStoreDeleteExpiredCall) Return(arg0 int, arg1 error) *MockHandoffStoreDeleteExpiredCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandoffStoreDeleteExpiredCall) Do(f func(context.Context, time.Time) (int, error)) *MockHandoffStoreDeleteExpiredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandoffStoreDeleteExpiredCall) DoAndReturn(f func(context.Context, time.Time) (int, error)) *MockHandoffStoreDeleteExpiredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByTokenID mocks base method.
func (m *MockHandoffStore) FindByTokenID(ctx context.Context, tokenID string) (*oidc.HandoffRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTokenID", ctx, tokenID)
	ret0, _ := ret[0].(*oidc.HandoffRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTokenID indicates an expected call of FindByTokenID.
func (mr *MockHandoffStoreMockRecorder) FindByTokenID(ctx, tokenID any) *MockHandoffStoreFindByTokenIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTokenID", reflect.TypeOf((*MockHandoffStore)(nil).FindByTokenID), ctx, tokenID)
	return &MockHandoffStoreFindByTokenIDCall{Call: call}
}

// MockHandoffStoreFindByTokenIDCall wrap *gomock.Call
type MockHandoffStoreFindByTokenIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandoffStoreFindByTokenIDCall) Return(arg0 *oidc.HandoffRecord, arg1 error) *MockHandoffStoreFindByTokenIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandoffStoreFindByTokenIDCall) Do(f func(context.Context, string) (*oidc.HandoffRecord, error)) *MockHandoffStoreFindByTokenIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandoffStoreFindByTokenIDCall) DoAndReturn(f func(context.Context, string) (*oidc.HandoffRecord, error)) *MockHandoffStoreFindByTokenIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockHandoffStore) Insert(ctx context.Context, rec oidc.HandoffRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockHandoffStoreMockRecorder) Insert(ctx, rec any) *MockHandoffStoreInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockHandoffStore)(nil).Insert), ctx, rec)
	return &MockHandoffStoreInsertCall{Call: call}
}

// MockHandoffStoreInsertCall wrap *gomock.Call
type MockHandoffStoreInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHandoffStoreInsertCall) Return(arg0 error) *MockHandoffStoreInsertCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHandoffStoreInsertCall) Do(f func(context.Context, oidc.HandoffRecord) error) *MockHandoffStoreInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHandoffStoreInsertCall) DoAndReturn(f func(context.Context, oidc.HandoffRecord) error) *MockHandoffStoreInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
