package seal

import (
	"crypto/aes"
	"crypto/cipher"
	"errors"
	"fmt"

	"github.com/kartaladev/scrty/internal/diag"
	"github.com/kartaladev/scrty/internal/nilcheck"
)

// Cipher seals and opens the long-lived secrets a durable store keeps, binding
// each value to the record it belongs to through additional authenticated data
// (aad), which is authenticated but not stored.
//
// NewAEADCipher returns the default, AES-256-GCM over a Keyring. A consumer
// replaces it wholesale by implementing this interface, for example over a
// key management service; nothing else in the library assumes AES. An
// implementation must be safe for concurrent use, must make Open fail when aad
// differs from what Seal was given, and should produce a different value each
// time it seals the same plaintext.
//
//go:generate mockgen -source=aead.go -package=seal_test -destination=cipher_mock_test.go -typed
type Cipher interface {
	// Seal encrypts plaintext under the active key, authenticating aad.
	Seal(plaintext, aad []byte) ([]byte, error)

	// Open decrypts sealed, failing unless aad is exactly what Seal was given,
	// and reports the id of the key that opened it, so a caller can tell a
	// value sealed under a retired key and re-seal it.
	Open(sealed, aad []byte) (plaintext []byte, keyID string, err error)

	// ActiveKeyID returns the id of the key Seal uses now.
	ActiveKeyID() (string, error)
}

// aeadCipher is the default Cipher.
type aeadCipher struct {
	kr Keyring
}

// NewAEADCipher returns the default Cipher: AES-256-GCM with a fresh random
// 96-bit nonce for every seal, drawn from crypto/rand, over the keys of kr.
// A consumer who wants another algorithm or a key management service
// implements Cipher instead; one who keeps the keys elsewhere supplies their
// own Keyring.
//
// It returns an error matching ErrInvalidConfiguration when kr is nil, typed
// nil included, so a cipher wired without keys fails at start-up rather than on
// the first seal or open.
//
// Values are stored as an envelope naming the key that sealed them, so kr may
// gain an active key and keep the old one as retired without making stored
// values unreadable. The envelope's header, key id included, is authenticated
// together with aad, so a value whose key id was rewritten does not open even
// under a keyring that returns the same bytes for two ids.
//
// kr is asked for a key on every call and is never cached. A key that is not
// 32 bytes, or an active key id outside [A-Za-z0-9._-]{1,64}, fails the call
// with ErrInvalidConfiguration; the cipher never falls back to a shorter key or
// to storing plaintext.
//
// Open returns ErrDecryptionFailed for every value that does not open — wrong
// key, wrong aad, altered or truncated bytes, or bytes that were never sealed —
// and ErrUnknownKeyID, never matching ErrDecryptionFailed, when the value
// names a key kr does not hold. With ErrUnknownKeyID it still returns the id
// the value names, so an operator can tell which key to restore; that id is
// read from the stored value and is never part of the error's text (see
// ErrUnknownKeyID). A failure of kr itself is returned behind fixed text,
// matching the ring's error through errors.Is and errors.As. No error carries
// key bytes or plaintext.
//
// Limit: a random 96-bit nonce is safe for about 2^32 seals under one key;
// past that, the chance of a repeated nonce, which breaks GCM's
// confidentiality and integrity for that key, is no longer negligible. Rotate
// the active key well before a key has sealed that many values.
func NewAEADCipher(kr Keyring) (Cipher, error) {
	if nilcheck.IsNil(kr) {
		return nil, fmt.Errorf("%w: the cipher has no keyring", ErrInvalidConfiguration)
	}

	return &aeadCipher{kr: kr}, nil
}

// Seal encrypts plaintext under the active key and returns the envelope.
func (c *aeadCipher) Seal(plaintext, aad []byte) ([]byte, error) {
	id, key, err := c.active()
	if err != nil {
		return nil, err
	}

	aead, err := newAEAD(key)
	if err != nil {
		return nil, err
	}

	// The nonce is generated by the AEAD and written ahead of the ciphertext,
	// which is exactly the envelope's body. The header is authenticated with
	// the caller's aad, so a rewritten key id fails the tag.
	header := encodeHeader(id, len(plaintext))

	return aead.Seal(header, nil, plaintext, additionalData(header, aad)), nil
}

// Open decrypts an envelope, reporting the id of the key that opened it.
func (c *aeadCipher) Open(sealed, aad []byte) ([]byte, string, error) {
	id, header, body, ok := decodeEnvelope(sealed)
	if !ok {
		return nil, "", ErrDecryptionFailed
	}

	key, err := c.kr.ByID(id)
	if errors.Is(err, ErrUnknownKeyID) {
		return nil, id, diag.Wrap(err, "seal: unknown key id: the keyring does not hold the key the value was sealed under",
			ErrUnknownKeyID)
	}
	if err != nil {
		return nil, "", diag.Wrap(err, "seal: the keyring could not provide the key the value was sealed under")
	}

	aead, err := newAEAD(key)
	if err != nil {
		return nil, "", err
	}

	plaintext, err := aead.Open(nil, nil, body, additionalData(header, aad))
	if err != nil {
		return nil, "", ErrDecryptionFailed
	}

	return plaintext, id, nil
}

// ActiveKeyID returns the id of the keyring's active key.
func (c *aeadCipher) ActiveKeyID() (string, error) {
	id, _, err := c.active()

	return id, err
}

// active asks the keyring for its active key, and refuses an id the envelope
// cannot carry. It is the one place a keyring's active key is checked, so
// Seal and ActiveKeyID can never disagree about it.
func (c *aeadCipher) active() (string, []byte, error) {
	id, key, err := c.kr.Active()
	if err != nil {
		return "", nil, diag.Wrap(err, "seal: the keyring could not provide the active key")
	}
	if !validKeyID(id) {
		return "", nil, fmt.Errorf("%w: the active key id must be 1 to %d of A-Z, a-z, 0-9, '.', '_' or '-'",
			ErrInvalidConfiguration, maxKeyIDLen)
	}

	return id, key, nil
}

// newAEAD returns AES-256-GCM over key, generating a random nonce on each
// seal. A key of any other length is refused, so a consumer's keyring cannot
// quietly downgrade the cipher to AES-128 or AES-192.
func newAEAD(key []byte) (cipher.AEAD, error) {
	if len(key) != KeySize {
		return nil, fmt.Errorf("%w: a key must be %d bytes, got %d", ErrInvalidConfiguration, KeySize, len(key))
	}

	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, diag.Wrap(err, "seal: the key could not be used", ErrInvalidConfiguration)
	}

	aead, err := cipher.NewGCMWithRandomNonce(block)
	if err != nil {
		return nil, diag.Wrap(err, "seal: the key could not be used", ErrInvalidConfiguration)
	}

	return aead, nil
}
