// Code generated by MockGen. DO NOT EDIT.
// Source: aead.go
//
// Generated by this command:
//
//	mockgen -source=aead.go -package=seal_test -destination=cipher_mock_test.go -typed
//

// Package seal_test is a generated GoMock package.
package seal_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCipher is a mock of Cipher interface.
type MockCipher struct {
	ctrl     *gomock.Controller
	recorder *MockCipherMockRecorder
	isgomock struct{}
}

// MockCipherMockRecorder is the mock recorder for MockCipher.
type MockCipherMockRecorder struct {
	mock *MockCipher
}

// NewMockCipher creates a new mock instance.
func NewMockCipher(ctrl *gomock.Controller) *MockCipher {
	mock := &MockCipher{ctrl: ctrl}
	mock.recorder = &MockCipherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCipher) EXPECT() *MockCipherMockRecorder {
	return m.recorder
}

// ActiveKeyID mocks base method.
func (m *MockCipher) ActiveKeyID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveKeyID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveKeyID indicates an expected call of ActiveKeyID.
func (mr *MockCipherMockRecorder) ActiveKeyID() *MockCipherActiveKeyIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveKeyID", reflect.TypeOf((*MockCipher)(nil).ActiveKeyID))
	return &MockCipherActiveKeyIDCall{Call: call}
}

// MockCipherActiveKeyIDCall wrap *gomock.Call
type MockCipherActiveKeyIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCipherActiveKeyIDCall) Return(arg0 string, arg1 error) *MockCipherActiveKeyIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCipherActiveKeyIDCall) Do(f func() (string, error)) *MockCipherActiveKeyIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCipherActiveKeyIDCall) DoAndReturn(f func() (string, error)) *MockCipherActiveKeyIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Open mocks base method.
func (m *MockCipher) Open(sealed, aad []byte) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", sealed, aad)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Open indicates an expected call of Open.
func (mr *MockCipherMockRecorder) Open(sealed, aad any) *MockCipherOpenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockCipher)(nil).Open), sealed, aad)
	return &MockCipherOpenCall{Call: call}
}

// MockCipherOpenCall wrap *gomock.Call
type MockCipherOpenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCipherOpenCall) Return(plaintext []byte, keyID string, err error) *MockCipherOpenCall {
	c.Call = c.Call.Return(plaintext, keyID, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCipherOpenCall) Do(f func([]byte, []byte) ([]byte, string, error)) *MockCipherOpenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCipherOpenCall) DoAndReturn(f func([]byte, []byte) ([]byte, string, error)) *MockCipherOpenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Seal mocks base method.
func (m *MockCipher) Seal(plaintext, aad []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seal", plaintext, aad)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seal indicates an expected call of Seal.
func (mr *MockCipherMockRecorder) Seal(plaintext, aad any) *MockCipherSealCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seal", reflect.TypeOf((*MockCipher)(nil).Seal), plaintext, aad)
	return &MockCipherSealCall{Call: call}
}

// MockCipherSealCall wrap *gomock.Call
type MockCipherSealCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCipherSealCall) Return(arg0 []byte, arg1 error) *MockCipherSealCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCipherSealCall) Do(f func([]byte, []byte) ([]byte, error)) *MockCipherSealCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCipherSealCall) DoAndReturn(f func([]byte, []byte) ([]byte, error)) *MockCipherSealCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
