// Code generated by MockGen. DO NOT EDIT.
// Source: ../mfa/store.go
//
// Generated by this command:
//
//	mockgen -source=../mfa/store.go -package=seal_test -destination=enrolmentstore_mock_test.go -typed -exclude_interfaces=DeviceProofStore
//

// Package seal_test is a generated GoMock package.
package seal_test

import (
	context "context"
	reflect "reflect"
	time "time"

	identity "github.com/kartaladev/scrty/identity"
	mfa "github.com/kartaladev/scrty/mfa"
	gomock "go.uber.org/mock/gomock"
)

// MockEnrolmentStore is a mock of EnrolmentStore interface.
type MockEnrolmentStore struct {
	ctrl     *gomock.Controller
	recorder *MockEnrolmentStoreMockRecorder
	isgomock struct{}
}

// MockEnrolmentStoreMockRecorder is the mock recorder for MockEnrolmentStore.
type MockEnrolmentStoreMockRecorder struct {
	mock *MockEnrolmentStore
}

// NewMockEnrolmentStore creates a new mock instance.
func NewMockEnrolmentStore(ctrl *gomock.Controller) *MockEnrolmentStore {
	mock := &MockEnrolmentStore{ctrl: ctrl}
	mock.recorder = &MockEnrolmentStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrolmentStore) EXPECT() *MockEnrolmentStoreMockRecorder {
	return m.recorder
}

// AcceptStep mocks base method.
func (m *MockEnrolmentStore) AcceptStep(ctx context.Context, user identity.UserID, step int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptStep", ctx, user, step)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptStep indicates an expected call of AcceptStep.
func (mr *MockEnrolmentStoreMockRecorder) AcceptStep(ctx, user, step any) *MockEnrolmentStoreAcceptStepCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptStep", reflect.TypeOf((*MockEnrolmentStore)(nil).AcceptStep), ctx, user, step)
	return &MockEnrolmentStoreAcceptStepCall{Call: call}
}

// MockEnrolmentStoreAcceptStepCall wrap *gomock.Call
type MockEnrolmentStoreAcceptStepCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrolmentStoreAcceptStepCall) Return(arg0 bool, arg1 error) *MockEnrolmentStoreAcceptStepCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrolmentStoreAcceptStepCall) Do(f func(context.Context, identity.UserID, int64) (bool, error)) *MockEnrolmentStoreAcceptStepCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrolmentStoreAcceptStepCall) DoAndReturn(f func(context.Context, identity.UserID, int64) (bool, error)) *MockEnrolmentStoreAcceptStepCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Confirm mocks base method.
func (m *MockEnrolmentStore) Confirm(ctx context.Context, user identity.UserID, step int64, at time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, user, step, at)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Confirm indicates an expected call of Confirm.
func (mr *MockEnrolmentStoreMockRecorder) Confirm(ctx, user, step, at any) *MockEnrolmentStoreConfirmCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockEnrolmentStore)(nil).Confirm), ctx, user, step, at)
	return &MockEnrolmentStoreConfirmCall{Call: call}
}

// MockEnrolmentStoreConfirmCall wrap *gomock.Call
type MockEnrolmentStoreConfirmCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrolmentStoreConfirmCall) Return(arg0 bool, arg1 error) *MockEnrolmentStoreConfirmCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrolmentStoreConfirmCall) Do(f func(context.Context, identity.UserID, int64, time.Time) (bool, error)) *MockEnrolmentStoreConfirmCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrolmentStoreConfirmCall) DoAndReturn(f func(context.Context, identity.UserID, int64, time.Time) (bool, error)) *MockEnrolmentStoreConfirmCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockEnrolmentStore) Delete(ctx context.Context, user identity.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEnrolmentStoreMockRecorder) Delete(ctx, user any) *MockEnrolmentStoreDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEnrolmentStore)(nil).Delete), ctx, user)
	return &MockEnrolmentStoreDeleteCall{Call: call}
}

// MockEnrolmentStoreDeleteCall wrap *gomock.Call
type MockEnrolmentStoreDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrolmentStoreDeleteCall) Return(arg0 error) *MockEnrolmentStoreDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrolmentStoreDeleteCall) Do(f func(context.Context, identity.UserID) error) *MockEnrolmentStoreDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrolmentStoreDeleteCall) DoAndReturn(f func(context.Context, identity.UserID) error) *MockEnrolmentStoreDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockEnrolmentStore) Get(ctx context.Context, user identity.UserID) (mfa.Enrolment, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, user)
	ret0, _ := ret[0].(mfa.Enrolment)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockEnrolmentStoreMockRecorder) Get(ctx, user any) *MockEnrolmentStoreGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEnrolmentStore)(nil).Get), ctx, user)
	return &MockEnrolmentStoreGetCall{Call: call}
}

// MockEnrolmentStoreGetCall wrap *gomock.Call
type MockEnrolmentStoreGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrolmentStoreGetCall) Return(arg0 mfa.Enrolment, arg1 bool, arg2 error) *MockEnrolmentStoreGetCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrolmentStoreGetCall) Do(f func(context.Context, identity.UserID) (mfa.Enrolment, bool, error)) *MockEnrolmentStoreGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrolmentStoreGetCall) DoAndReturn(f func(context.Context, identity.UserID) (mfa.Enrolment, bool, error)) *MockEnrolmentStoreGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutPending mocks base method.
func (m *MockEnrolmentStore) PutPending(ctx context.Context, e mfa.Enrolment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutPending", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutPending indicates an expected call of PutPending.
func (mr *MockEnrolmentStoreMockRecorder) PutPending(ctx, e any) *MockEnrolmentStorePutPendingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutPending", reflect.TypeOf((*MockEnrolmentStore)(nil).PutPending), ctx, e)
	return &MockEnrolmentStorePutPendingCall{Call: call}
}

// MockEnrolmentStorePutPendingCall wrap *gomock.Call
type MockEnrolmentStorePutPendingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrolmentStorePutPendingCall) Return(arg0 error) *MockEnrolmentStorePutPendingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrolmentStorePutPendingCall) Do(f func(context.Context, mfa.Enrolment) error) *MockEnrolmentStorePutPendingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrolmentStorePutPendingCall) DoAndReturn(f func(context.Context, mfa.Enrolment) error) *MockEnrolmentStorePutPendingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
