// Code generated by MockGen. DO NOT EDIT.
// Source: keyring.go
//
// Generated by this command:
//
//	mockgen -source=keyring.go -package=seal_test -destination=keyring_mock_test.go -typed
//

// Package seal_test is a generated GoMock package.
package seal_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKeyring is a mock of Keyring interface.
type MockKeyring struct {
	ctrl     *gomock.Controller
	recorder *MockKeyringMockRecorder
	isgomock struct{}
}

// MockKeyringMockRecorder is the mock recorder for MockKeyring.
type MockKeyringMockRecorder struct {
	mock *MockKeyring
}

// NewMockKeyring creates a new mock instance.
func NewMockKeyring(ctrl *gomock.Controller) *MockKeyring {
	mock := &MockKeyring{ctrl: ctrl}
	mock.recorder = &MockKeyringMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyring) EXPECT() *MockKeyringMockRecorder {
	return m.recorder
}

// Active mocks base method.
func (m *MockKeyring) Active() (string, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Active")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Active indicates an expected call of Active.
func (mr *MockKeyringMockRecorder) Active() *MockKeyringActiveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Active", reflect.TypeOf((*MockKeyring)(nil).Active))
	return &MockKeyringActiveCall{Call: call}
}

// MockKeyringActiveCall wrap *gomock.Call
type MockKeyringActiveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyringActiveCall) Return(id string, key []byte, err error) *MockKeyringActiveCall {
	c.Call = c.Call.Return(id, key, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyringActiveCall) Do(f func() (string, []byte, error)) *MockKeyringActiveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyringActiveCall) DoAndReturn(f func() (string, []byte, error)) *MockKeyringActiveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ByID mocks base method.
func (m *MockKeyring) ByID(id string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockKeyringMockRecorder) ByID(id any) *MockKeyringByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockKeyring)(nil).ByID), id)
	return &MockKeyringByIDCall{Call: call}
}

// MockKeyringByIDCall wrap *gomock.Call
type MockKeyringByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyringByIDCall) Return(arg0 []byte, arg1 error) *MockKeyringByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyringByIDCall) Do(f func(string) ([]byte, error)) *MockKeyringByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyringByIDCall) DoAndReturn(f func(string) ([]byte, error)) *MockKeyringByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
