// Code generated by MockGen. DO NOT EDIT.
// Source: mfa.go
//
// Generated by this command:
//
//	mockgen -source=mfa.go -package=seal_test -destination=mfa_mock_test.go -typed
//

// Package seal_test is a generated GoMock package.
package seal_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockEnrolmentResealer is a mock of EnrolmentResealer interface.
type MockEnrolmentResealer struct {
	ctrl     *gomock.Controller
	recorder *MockEnrolmentResealerMockRecorder
	isgomock struct{}
}

// MockEnrolmentResealerMockRecorder is the mock recorder for MockEnrolmentResealer.
type MockEnrolmentResealerMockRecorder struct {
	mock *MockEnrolmentResealer
}

// NewMockEnrolmentResealer creates a new mock instance.
func NewMockEnrolmentResealer(ctrl *gomock.Controller) *MockEnrolmentResealer {
	mock := &MockEnrolmentResealer{ctrl: ctrl}
	mock.recorder = &MockEnrolmentResealerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrolmentResealer) EXPECT() *MockEnrolmentResealerMockRecorder {
	return m.recorder
}

// ResealEnrolmentSecret mocks base method.
func (m *MockEnrolmentResealer) ResealEnrolmentSecret(ctx context.Context, user identity.UserID, old, resealed []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResealEnrolmentSecret", ctx, user, old, resealed)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResealEnrolmentSecret indicates an expected call of ResealEnrolmentSecret.
func (mr *MockEnrolmentResealerMockRecorder) ResealEnrolmentSecret(ctx, user, old, resealed any) *MockEnrolmentResealerResealEnrolmentSecretCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResealEnrolmentSecret", reflect.TypeOf((*MockEnrolmentResealer)(nil).ResealEnrolmentSecret), ctx, user, old, resealed)
	return &MockEnrolmentResealerResealEnrolmentSecretCall{Call: call}
}

// MockEnrolmentResealerResealEnrolmentSecretCall wrap *gomock.Call
type MockEnrolmentResealerResealEnrolmentSecretCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEnrolmentResealerResealEnrolmentSecretCall) Return(arg0 error) *MockEnrolmentResealerResealEnrolmentSecretCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEnrolmentResealerResealEnrolmentSecretCall) Do(f func(context.Context, identity.UserID, []byte, []byte) error) *MockEnrolmentResealerResealEnrolmentSecretCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEnrolmentResealerResealEnrolmentSecretCall) DoAndReturn(f func(context.Context, identity.UserID, []byte, []byte) error) *MockEnrolmentResealerResealEnrolmentSecretCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
