// Code generated by MockGen. DO NOT EDIT.
// Source: signingkey.go
//
// Generated by this command:
//
//	mockgen -source=signingkey.go -package=seal_test -destination=signingkey_mock_test.go -typed
//

// Package seal_test is a generated GoMock package.
package seal_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSigningKeyResealer is a mock of SigningKeyResealer interface.
type MockSigningKeyResealer struct {
	ctrl     *gomock.Controller
	recorder *MockSigningKeyResealerMockRecorder
	isgomock struct{}
}

// MockSigningKeyResealerMockRecorder is the mock recorder for MockSigningKeyResealer.
type MockSigningKeyResealerMockRecorder struct {
	mock *MockSigningKeyResealer
}

// NewMockSigningKeyResealer creates a new mock instance.
func NewMockSigningKeyResealer(ctrl *gomock.Controller) *MockSigningKeyResealer {
	mock := &MockSigningKeyResealer{ctrl: ctrl}
	mock.recorder = &MockSigningKeyResealerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSigningKeyResealer) EXPECT() *MockSigningKeyResealerMockRecorder {
	return m.recorder
}

// ResealSigningKey mocks base method.
func (m *MockSigningKeyResealer) ResealSigningKey(ctx context.Context, kid string, old, resealed []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResealSigningKey", ctx, kid, old, resealed)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResealSigningKey indicates an expected call of ResealSigningKey.
func (mr *MockSigningKeyResealerMockRecorder) ResealSigningKey(ctx, kid, old, resealed any) *MockSigningKeyResealerResealSigningKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResealSigningKey", reflect.TypeOf((*MockSigningKeyResealer)(nil).ResealSigningKey), ctx, kid, old, resealed)
	return &MockSigningKeyResealerResealSigningKeyCall{Call: call}
}

// MockSigningKeyResealerResealSigningKeyCall wrap *gomock.Call
type MockSigningKeyResealerResealSigningKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSigningKeyResealerResealSigningKeyCall) Return(arg0 error) *MockSigningKeyResealerResealSigningKeyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSigningKeyResealerResealSigningKeyCall) Do(f func(context.Context, string, []byte, []byte) error) *MockSigningKeyResealerResealSigningKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSigningKeyResealerResealSigningKeyCall) DoAndReturn(f func(context.Context, string, []byte, []byte) error) *MockSigningKeyResealerResealSigningKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
