// Code generated by MockGen. DO NOT EDIT.
// Source: bearer.go
//
// Generated by this command:
//
//	mockgen -source=bearer.go -package=authenticate_test -destination=bearercredentials_mock_test.go -typed
//

// Package authenticate_test is a generated GoMock package.
package authenticate_test

import (
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockBearerCredentials is a mock of BearerCredentials interface.
type MockBearerCredentials struct {
	ctrl     *gomock.Controller
	recorder *MockBearerCredentialsMockRecorder
	isgomock struct{}
}

// MockBearerCredentialsMockRecorder is the mock recorder for MockBearerCredentials.
type MockBearerCredentialsMockRecorder struct {
	mock *MockBearerCredentials
}

// NewMockBearerCredentials creates a new mock instance.
func NewMockBearerCredentials(ctrl *gomock.Controller) *MockBearerCredentials {
	mock := &MockBearerCredentials{ctrl: ctrl}
	mock.recorder = &MockBearerCredentialsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBearerCredentials) EXPECT() *MockBearerCredentialsMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockBearerCredentials) Cleanup() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup")
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockBearerCredentialsMockRecorder) Cleanup() *MockBearerCredentialsCleanupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockBearerCredentials)(nil).Cleanup))
	return &MockBearerCredentialsCleanupCall{Call: call}
}

// MockBearerCredentialsCleanupCall wrap *gomock.Call
type MockBearerCredentialsCleanupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBearerCredentialsCleanupCall) Return(arg0 error) *MockBearerCredentialsCleanupCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBearerCredentialsCleanupCall) Do(f func() error) *MockBearerCredentialsCleanupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBearerCredentialsCleanupCall) DoAndReturn(f func() error) *MockBearerCredentialsCleanupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Token mocks base method.
func (m *MockBearerCredentials) Token() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(string)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockBearerCredentialsMockRecorder) Token() *MockBearerCredentialsTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockBearerCredentials)(nil).Token))
	return &MockBearerCredentialsTokenCall{Call: call}
}

// MockBearerCredentialsTokenCall wrap *gomock.Call
type MockBearerCredentialsTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBearerCredentialsTokenCall) Return(arg0 string) *MockBearerCredentialsTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBearerCredentialsTokenCall) Do(f func() string) *MockBearerCredentialsTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBearerCredentialsTokenCall) DoAndReturn(f func() string) *MockBearerCredentialsTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Type mocks base method.
func (m *MockBearerCredentials) Type() identity.CredentialsType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(identity.CredentialsType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockBearerCredentialsMockRecorder) Type() *MockBearerCredentialsTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockBearerCredentials)(nil).Type))
	return &MockBearerCredentialsTypeCall{Call: call}
}

// MockBearerCredentialsTypeCall wrap *gomock.Call
type MockBearerCredentialsTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBearerCredentialsTypeCall) Return(arg0 identity.CredentialsType) *MockBearerCredentialsTypeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBearerCredentialsTypeCall) Do(f func() identity.CredentialsType) *MockBearerCredentialsTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBearerCredentialsTypeCall) DoAndReturn(f func() identity.CredentialsType) *MockBearerCredentialsTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
