// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/identity (interfaces: UserLoader)
//
// Generated by this command:
//
//	mockgen -destination=userloader_mock_test.go -package=authenticate_test -typed github.com/kartaladev/scrty/identity UserLoader
//

// Package authenticate_test is a generated GoMock package.
package authenticate_test

import (
	context "context"
	reflect "reflect"

	identity "github.com/kartaladev/scrty/identity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserLoader is a mock of UserLoader interface.
type MockUserLoader struct {
	ctrl     *gomock.Controller
	recorder *MockUserLoaderMockRecorder
	isgomock struct{}
}

// MockUserLoaderMockRecorder is the mock recorder for MockUserLoader.
type MockUserLoaderMockRecorder struct {
	mock *MockUserLoader
}

// NewMockUserLoader creates a new mock instance.
func NewMockUserLoader(ctrl *gomock.Controller) *MockUserLoader {
	mock := &MockUserLoader{ctrl: ctrl}
	mock.recorder = &MockUserLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserLoader) EXPECT() *MockUserLoaderMockRecorder {
	return m.recorder
}

// LoadByUserID mocks base method.
func (m *MockUserLoader) LoadByUserID(ctx context.Context, id identity.UserID) (*identity.Details, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadByUserID", ctx, id)
	ret0, _ := ret[0].(*identity.Details)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadByUserID indicates an expected call of LoadByUserID.
func (mr *MockUserLoaderMockRecorder) LoadByUserID(ctx, id any) *MockUserLoaderLoadByUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadByUserID", reflect.TypeOf((*MockUserLoader)(nil).LoadByUserID), ctx, id)
	return &MockUserLoaderLoadByUserIDCall{Call: call}
}

// MockUserLoaderLoadByUserIDCall wrap *gomock.Call
type MockUserLoaderLoadByUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserLoaderLoadByUserIDCall) Return(arg0 *identity.Details, arg1 error) *MockUserLoaderLoadByUserIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserLoaderLoadByUserIDCall) Do(f func(context.Context, identity.UserID) (*identity.Details, error)) *MockUserLoaderLoadByUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserLoaderLoadByUserIDCall) DoAndReturn(f func(context.Context, identity.UserID) (*identity.Details, error)) *MockUserLoaderLoadByUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LoadByUsername mocks base method.
func (m *MockUserLoader) LoadByUsername(ctx context.Context, username string) (*identity.Details, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadByUsername", ctx, username)
	ret0, _ := ret[0].(*identity.Details)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadByUsername indicates an expected call of LoadByUsername.
func (mr *MockUserLoaderMockRecorder) LoadByUsername(ctx, username any) *MockUserLoaderLoadByUsernameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadByUsername", reflect.TypeOf((*MockUserLoader)(nil).LoadByUsername), ctx, username)
	return &MockUserLoaderLoadByUsernameCall{Call: call}
}

// MockUserLoaderLoadByUsernameCall wrap *gomock.Call
type MockUserLoaderLoadByUsernameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserLoaderLoadByUsernameCall) Return(arg0 *identity.Details, arg1 error) *MockUserLoaderLoadByUsernameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserLoaderLoadByUsernameCall) Do(f func(context.Context, string) (*identity.Details, error)) *MockUserLoaderLoadByUsernameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserLoaderLoadByUsernameCall) DoAndReturn(f func(context.Context, string) (*identity.Details, error)) *MockUserLoaderLoadByUsernameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
