// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kartaladev/scrty/token (interfaces: Verifier)
//
// Generated by this command:
//
//	mockgen -destination=verifier_mock_test.go -package=authenticate_test -typed github.com/kartaladev/scrty/token Verifier
//

// Package authenticate_test is a generated GoMock package.
package authenticate_test

import (
	context "context"
	reflect "reflect"

	token "github.com/kartaladev/scrty/token"
	gomock "go.uber.org/mock/gomock"
)

// MockVerifier is a mock of Verifier interface.
type MockVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockVerifierMockRecorder
	isgomock struct{}
}

// MockVerifierMockRecorder is the mock recorder for MockVerifier.
type MockVerifierMockRecorder struct {
	mock *MockVerifier
}

// NewMockVerifier creates a new mock instance.
func NewMockVerifier(ctrl *gomock.Controller) *MockVerifier {
	mock := &MockVerifier{ctrl: ctrl}
	mock.recorder = &MockVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifier) EXPECT() *MockVerifierMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockVerifier) Verify(ctx context.Context, arg1 string) (*token.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, arg1)
	ret0, _ := ret[0].(*token.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockVerifierMockRecorder) Verify(ctx, arg1 any) *MockVerifierVerifyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockVerifier)(nil).Verify), ctx, arg1)
	return &MockVerifierVerifyCall{Call: call}
}

// MockVerifierVerifyCall wrap *gomock.Call
type MockVerifierVerifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVerifierVerifyCall) Return(arg0 *token.Claims, arg1 error) *MockVerifierVerifyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVerifierVerifyCall) Do(f func(context.Context, string) (*token.Claims, error)) *MockVerifierVerifyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVerifierVerifyCall) DoAndReturn(f func(context.Context, string) (*token.Claims, error)) *MockVerifierVerifyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
