// Code generated by MockGen. DO NOT EDIT.
// Source: encrypted.go
//
// Generated by this command:
//
//	mockgen -source=encrypted.go -package=session_test -destination=cipher_mock_test.go -typed
//

// Package session_test is a generated GoMock package.
package session_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCipher is a mock of Cipher interface.
type MockCipher struct {
	ctrl     *gomock.Controller
	recorder *MockCipherMockRecorder
	isgomock struct{}
}

// MockCipherMockRecorder is the mock recorder for MockCipher.
type MockCipherMockRecorder struct {
	mock *MockCipher
}

// NewMockCipher creates a new mock instance.
func NewMockCipher(ctrl *gomock.Controller) *MockCipher {
	mock := &MockCipher{ctrl: ctrl}
	mock.recorder = &MockCipherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCipher) EXPECT() *MockCipherMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockCipher) Open(ciphertext, additionalData []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ciphertext, additionalData)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockCipherMockRecorder) Open(ciphertext, additionalData any) *MockCipherOpenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockCipher)(nil).Open), ciphertext, additionalData)
	return &MockCipherOpenCall{Call: call}
}

// MockCipherOpenCall wrap *gomock.Call
type MockCipherOpenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCipherOpenCall) Return(arg0 []byte, arg1 error) *MockCipherOpenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCipherOpenCall) Do(f func([]byte, []byte) ([]byte, error)) *MockCipherOpenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCipherOpenCall) DoAndReturn(f func([]byte, []byte) ([]byte, error)) *MockCipherOpenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Seal mocks base method.
func (m *MockCipher) Seal(plaintext, additionalData []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seal", plaintext, additionalData)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seal indicates an expected call of Seal.
func (mr *MockCipherMockRecorder) Seal(plaintext, additionalData any) *MockCipherSealCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seal", reflect.TypeOf((*MockCipher)(nil).Seal), plaintext, additionalData)
	return &MockCipherSealCall{Call: call}
}

// MockCipherSealCall wrap *gomock.Call
type MockCipherSealCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCipherSealCall) Return(arg0 []byte, arg1 error) *MockCipherSealCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCipherSealCall) Do(f func([]byte, []byte) ([]byte, error)) *MockCipherSealCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCipherSealCall) DoAndReturn(f func([]byte, []byte) ([]byte, error)) *MockCipherSealCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
