// Code generated by MockGen. DO NOT EDIT.
// Source: record.go
//
// Generated by this command:
//
//	mockgen -source=record.go -package=signingkey_test -destination=keystore_mock_test.go -typed
//

// Package signingkey_test is a generated GoMock package.
package signingkey_test

import (
	context "context"
	reflect "reflect"

	signingkey "github.com/kartaladev/scrty/signingkey"
	gomock "go.uber.org/mock/gomock"
)

// MockKeyStore is a mock of KeyStore interface.
type MockKeyStore struct {
	ctrl     *gomock.Controller
	recorder *MockKeyStoreMockRecorder
	isgomock struct{}
}

// MockKeyStoreMockRecorder is the mock recorder for MockKeyStore.
type MockKeyStoreMockRecorder struct {
	mock *MockKeyStore
}

// NewMockKeyStore creates a new mock instance.
func NewMockKeyStore(ctrl *gomock.Controller) *MockKeyStore {
	mock := &MockKeyStore{ctrl: ctrl}
	mock.recorder = &MockKeyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyStore) EXPECT() *MockKeyStoreMockRecorder {
	return m.recorder
}

// LoadAll mocks base method.
func (m *MockKeyStore) LoadAll(ctx context.Context) ([]signingkey.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAll", ctx)
	ret0, _ := ret[0].([]signingkey.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAll indicates an expected call of LoadAll.
func (mr *MockKeyStoreMockRecorder) LoadAll(ctx any) *MockKeyStoreLoadAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAll", reflect.TypeOf((*MockKeyStore)(nil).LoadAll), ctx)
	return &MockKeyStoreLoadAllCall{Call: call}
}

// MockKeyStoreLoadAllCall wrap *gomock.Call
type MockKeyStoreLoadAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyStoreLoadAllCall) Return(arg0 []signingkey.Record, arg1 error) *MockKeyStoreLoadAllCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyStoreLoadAllCall) Do(f func(context.Context) ([]signingkey.Record, error)) *MockKeyStoreLoadAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyStoreLoadAllCall) DoAndReturn(f func(context.Context) ([]signingkey.Record, error)) *MockKeyStoreLoadAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Store mocks base method.
func (m *MockKeyStore) Store(ctx context.Context, rec signingkey.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockKeyStoreMockRecorder) Store(ctx, rec any) *MockKeyStoreStoreCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockKeyStore)(nil).Store), ctx, rec)
	return &MockKeyStoreStoreCall{Call: call}
}

// MockKeyStoreStoreCall wrap *gomock.Call
type MockKeyStoreStoreCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockKeyStoreStoreCall) Return(arg0 error) *MockKeyStoreStoreCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockKeyStoreStoreCall) Do(f func(context.Context, signingkey.Record) error) *MockKeyStoreStoreCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockKeyStoreStoreCall) DoAndReturn(f func(context.Context, signingkey.Record) error) *MockKeyStoreStoreCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
