// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/id/generator.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/id/generator.go -package=onetime_test -destination=idgenerator_mock_test.go -typed
//

// Package onetime_test is a generated GoMock package.
package onetime_test

import (
	reflect "reflect"

	id "github.com/kartaladev/scrty/pkg/id"
	gomock "go.uber.org/mock/gomock"
)

// MockGenerator is a mock of Generator interface.
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
	isgomock struct{}
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator.
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance.
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockGenerator) NewID() (id.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(id.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewID indicates an expected call of NewID.
func (mr *MockGeneratorMockRecorder) NewID() *MockGeneratorNewIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockGenerator)(nil).NewID))
	return &MockGeneratorNewIDCall{Call: call}
}

// MockGeneratorNewIDCall wrap *gomock.Call
type MockGeneratorNewIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGeneratorNewIDCall) Return(arg0 id.ID, arg1 error) *MockGeneratorNewIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGeneratorNewIDCall) Do(f func() (id.ID, error)) *MockGeneratorNewIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGeneratorNewIDCall) DoAndReturn(f func() (id.ID, error)) *MockGeneratorNewIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
