// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -package=onetime_test -destination=mocks_test.go -typed
//

// Package onetime_test is a generated GoMock package.
package onetime_test

import (
	context "context"
	reflect "reflect"
	time "time"

	onetime "github.com/kartaladev/scrty/onetime"
	id "github.com/kartaladev/scrty/pkg/id"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockStore) Consume(ctx context.Context, tokenID id.ID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, tokenID, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockStoreMockRecorder) Consume(ctx, tokenID, at any) *MockStoreConsumeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockStore)(nil).Consume), ctx, tokenID, at)
	return &MockStoreConsumeCall{Call: call}
}

// MockStoreConsumeCall wrap *gomock.Call
type MockStoreConsumeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreConsumeCall) Return(arg0 error) *MockStoreConsumeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreConsumeCall) Do(f func(context.Context, id.ID, time.Time) error) *MockStoreConsumeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreConsumeCall) DoAndReturn(f func(context.Context, id.ID, time.Time) error) *MockStoreConsumeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CountRecentBySubject mocks base method.
func (m *MockStore) CountRecentBySubject(ctx context.Context, purpose, subject string, since time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecentBySubject", ctx, purpose, subject, since)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecentBySubject indicates an expected call of CountRecentBySubject.
func (mr *MockStoreMockRecorder) CountRecentBySubject(ctx, purpose, subject, since any) *MockStoreCountRecentBySubjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecentBySubject", reflect.TypeOf((*MockStore)(nil).CountRecentBySubject), ctx, purpose, subject, since)
	return &MockStoreCountRecentBySubjectCall{Call: call}
}

// MockStoreCountRecentBySubjectCall wrap *gomock.Call
type MockStoreCountRecentBySubjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreCountRecentBySubjectCall) Return(arg0 int, arg1 error) *MockStoreCountRecentBySubjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreCountRecentBySubjectCall) Do(f func(context.Context, string, string, time.Time) (int, error)) *MockStoreCountRecentBySubjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreCountRecentBySubjectCall) DoAndReturn(f func(context.Context, string, string, time.Time) (int, error)) *MockStoreCountRecentBySubjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByID mocks base method.
func (m *MockStore) FindByID(ctx context.Context, tokenID id.ID) (*onetime.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, tokenID)
	ret0, _ := ret[0].(*onetime.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockStoreMockRecorder) FindByID(ctx, tokenID any) *MockStoreFindByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockStore)(nil).FindByID), ctx, tokenID)
	return &MockStoreFindByIDCall{Call: call}
}

// MockStoreFindByIDCall wrap *gomock.Call
type MockStoreFindByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreFindByIDCall) Return(arg0 *onetime.Token, arg1 error) *MockStoreFindByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreFindByIDCall) Do(f func(context.Context, id.ID) (*onetime.Token, error)) *MockStoreFindByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreFindByIDCall) DoAndReturn(f func(context.Context, id.ID) (*onetime.Token, error)) *MockStoreFindByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockStore) Insert(ctx context.Context, tok onetime.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, tok)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockStoreMockRecorder) Insert(ctx, tok any) *MockStoreInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockStore)(nil).Insert), ctx, tok)
	return &MockStoreInsertCall{Call: call}
}

// MockStoreInsertCall wrap *gomock.Call
type MockStoreInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreInsertCall) Return(arg0 error) *MockStoreInsertCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreInsertCall) Do(f func(context.Context, onetime.Token) error) *MockStoreInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreInsertCall) DoAndReturn(f func(context.Context, onetime.Token) error) *MockStoreInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockReaper is a mock of Reaper interface.
type MockReaper struct {
	ctrl     *gomock.Controller
	recorder *MockReaperMockRecorder
	isgomock struct{}
}

// MockReaperMockRecorder is the mock recorder for MockReaper.
type MockReaperMockRecorder struct {
	mock *MockReaper
}

// NewMockReaper creates a new mock instance.
func NewMockReaper(ctrl *gomock.Controller) *MockReaper {
	mock := &MockReaper{ctrl: ctrl}
	mock.recorder = &MockReaperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReaper) EXPECT() *MockReaperMockRecorder {
	return m.recorder
}

// DeleteExpiredBefore mocks base method.
func (m *MockReaper) DeleteExpiredBefore(ctx context.Context, purpose string, retainSince time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredBefore", ctx, purpose, retainSince)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredBefore indicates an expected call of DeleteExpiredBefore.
func (mr *MockReaperMockRecorder) DeleteExpiredBefore(ctx, purpose, retainSince any) *MockReaperDeleteExpiredBeforeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredBefore", reflect.TypeOf((*MockReaper)(nil).DeleteExpiredBefore), ctx, purpose, retainSince)
	return &MockReaperDeleteExpiredBeforeCall{Call: call}
}

// MockReaperDeleteExpiredBeforeCall wrap *gomock.Call
type MockReaperDeleteExpiredBeforeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReaperDeleteExpiredBeforeCall) Return(arg0 int, arg1 error) *MockReaperDeleteExpiredBeforeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReaperDeleteExpiredBeforeCall) Do(f func(context.Context, string, time.Time) (int, error)) *MockReaperDeleteExpiredBeforeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReaperDeleteExpiredBeforeCall) DoAndReturn(f func(context.Context, string, time.Time) (int, error)) *MockReaperDeleteExpiredBeforeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
